"""
Generated by Data Preprocessing Script Library
Template : file_split_by_value  |  PS-07
Purpose  : Split a single file into N output files — one per distinct value
           found in SPLIT_COLUMN.  Null/NaN values are written to a separate
           {SPLIT_COLUMN}_NULL file.
Contract : preprocess(input_path: str) -> list
"""
from __future__ import annotations

import csv as _csv
import json as _json
import os
import re as _re
import tempfile as _tempfile
import zipfile as _zipfile
from pathlib import Path as _Path

import pandas as pd

# ── Configuration (substituted at generation time) ────────────────────────────
SPLIT_COLUMN         = "Country Code"
OUTPUT_DIR           = ""
OUTPUT_FORMAT        = "csv"
FILENAME_TEMPLATE    = "customers_{value}.csv"
INCLUDE_SPLIT_COLUMN = True
# ─────────────────────────────────────────────────────────────────────────────


# ── Embedded File Loader ──────────────────────────────────────────────────────
_ENCODINGS = ["utf-8", "cp1252", "latin-1"]


def _load_file(file_path: str) -> pd.DataFrame:
    ext = _Path(file_path).suffix.lower()
    if ext == ".zip":
        return _load_zip(file_path)
    if ext == ".xlsx":
        return pd.read_excel(file_path, engine="openpyxl")
    if ext == ".xls":
        return pd.read_excel(file_path, engine="xlrd")
    if ext == ".json":
        return _load_json(file_path)
    if ext == ".xml":
        return _load_xml(file_path)
    if ext in (".html", ".htm"):
        tables = pd.read_html(file_path)
        return tables[0] if tables else pd.DataFrame()
    return _load_delimited(file_path)


def _load_delimited(file_path: str) -> pd.DataFrame:
    for enc in _ENCODINGS:
        try:
            with open(file_path, "r", encoding=enc, errors="replace") as fh:
                sample = fh.read(8192)
            try:
                sep = _csv.Sniffer().sniff(sample).delimiter
            except _csv.Error:
                sep = ","
            return pd.read_csv(
                file_path, sep=sep, encoding=enc,
                on_bad_lines="skip", low_memory=False,
            )
        except Exception:
            continue
    raise ValueError(f"Cannot load delimited file: {file_path}")


def _load_json(file_path: str) -> pd.DataFrame:
    with open(file_path, "r", encoding="utf-8") as fh:
        data = _json.load(fh)
    return pd.json_normalize(data if isinstance(data, list) else [data])


def _load_xml(file_path: str) -> pd.DataFrame:
    try:
        import lxml.etree as _ET
        root = _ET.parse(file_path).getroot()
    except ImportError:
        import xml.etree.ElementTree as _ET  # type: ignore
        root = _ET.parse(file_path).getroot()
    records = [
        {el.tag: el.text for el in child.iter() if el.text and el.text.strip()}
        for child in root
    ]
    return pd.DataFrame(records)


def _load_zip(file_path: str) -> pd.DataFrame:
    _supported = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}
    with _tempfile.TemporaryDirectory() as tmp_dir:
        with _zipfile.ZipFile(file_path, "r") as z:
            names = [n for n in z.namelist() if _Path(n).suffix.lower() in _supported]
            for name in names:
                z.extract(name, tmp_dir)
        if names:
            return _load_file(os.path.join(tmp_dir, names[0]))
    raise ValueError(f"No loadable file found inside ZIP: {file_path}")


def _write_output(df: pd.DataFrame, out_path: str, fmt: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _fmt = fmt.lower()
    if _fmt == "csv":
        df.to_csv(out_path, index=False)
    elif _fmt in ("xlsx", "excel"):
        df.to_excel(out_path, index=False, engine="openpyxl")
    elif _fmt == "json":
        df.to_json(out_path, orient="records", indent=2)
    elif _fmt == "parquet":
        df.to_parquet(out_path, index=False)
    elif _fmt == "tsv":
        df.to_csv(out_path, sep="\t", index=False)
    else:
        df.to_csv(out_path, index=False)
    return out_path


def _safe_filename(value: str) -> str:
    """Replace filesystem-unsafe characters with underscores."""
    return _re.sub(r'[\\/:*?"<>|\s]', "_", str(value))

# ─────────────────────────────────────────────────────────────────────────────


def _process_one_file(df: pd.DataFrame, src_basename: str, out_dir: str) -> list:
    """
    Apply split-by-value logic to one DataFrame.
    If SPLIT_COLUMN is absent the file is written as-is (preserving its name).
    """
    paths: list = []

    if SPLIT_COLUMN not in df.columns:
        stem = _Path(src_basename).stem
        out_path = os.path.join(out_dir, f"{stem}.{OUTPUT_FORMAT.lower()}")
        paths.append(_write_output(df, out_path, OUTPUT_FORMAT))
        return paths

    stem = _Path(src_basename).stem
    orig_out = os.path.join(out_dir, f"{stem}.{OUTPUT_FORMAT.lower()}")
    paths.append(_write_output(df, orig_out, OUTPUT_FORMAT))

    null_mask   = df[SPLIT_COLUMN].isna()
    non_null_df = df[~null_mask]
    null_df     = df[null_mask]

    for value in non_null_df[SPLIT_COLUMN].unique():
        subset = non_null_df[non_null_df[SPLIT_COLUMN] == value].copy()
        if not INCLUDE_SPLIT_COLUMN:
            subset = subset.drop(columns=[SPLIT_COLUMN])
        safe_val = _safe_filename(value)
        filename = FILENAME_TEMPLATE.format(split_column=SPLIT_COLUMN, value=safe_val)
        paths.append(_write_output(subset, os.path.join(out_dir, filename), OUTPUT_FORMAT))

    if not null_df.empty:
        null_subset = null_df.copy()
        if not INCLUDE_SPLIT_COLUMN:
            null_subset = null_subset.drop(columns=[SPLIT_COLUMN])
        null_filename = f"{SPLIT_COLUMN}_NULL.{OUTPUT_FORMAT.lower()}"
        paths.append(_write_output(null_subset, os.path.join(out_dir, null_filename), OUTPUT_FORMAT))

    return paths


def preprocess(input_path: str) -> list:
    """
    Split *input_path* into one file per distinct value in SPLIT_COLUMN.
    Rows where SPLIT_COLUMN is null/NaN are written to a separate _NULL file.

    If *input_path* is a ZIP, ALL files inside are extracted first.
    Files that contain SPLIT_COLUMN are split by value.
    Files that do NOT contain SPLIT_COLUMN are written as-is to OUTPUT_DIR.

    Parameters
    ----------
    input_path : str | list
        Path to the source file or ZIP archive.

    Returns
    -------
    list
        List of absolute paths to all written output files.
    """
    if isinstance(input_path, list):
        input_path = input_path[0]

    _out_dir = OUTPUT_DIR if OUTPUT_DIR else os.path.dirname(os.path.abspath(input_path))
    os.makedirs(_out_dir, exist_ok=True)
    output_paths: list = []

    if _Path(input_path).suffix.lower() == ".zip":
        _supported = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}
        with _tempfile.TemporaryDirectory() as tmp_dir:
            with _zipfile.ZipFile(input_path, "r") as z:
                names = [n for n in z.namelist() if _Path(n).suffix.lower() in _supported]
                for name in names:
                    z.extract(name, tmp_dir)
            for name in names:
                df = _load_file(os.path.join(tmp_dir, name))
                output_paths.extend(_process_one_file(df, os.path.basename(name), _out_dir))
        return output_paths

    df = _load_file(input_path)
    output_paths.extend(_process_one_file(df, os.path.basename(input_path), _out_dir))
    return output_paths


import os as _os

# ─────────────────────────────────────────────────────────────────────────────
# ── Run Configuration ───────────────────────────────────────────────────────
# ── Set BASE_LOCATION to your input folder. File names are resolved from it. 
# ─────────────────────────────────────────────────────────────────────────────
BASE_LOCATION = r"C:/Users/91917/Desktop/github/preprocessing_library/test_data/test2"

INPUT_FILE = _os.path.join(BASE_LOCATION, "test_batch.zip")

if __name__ == "__main__":
    result = preprocess(INPUT_FILE)
    print(f"Output: {result}")
