"""
Generated by Data Preprocessing Script Library
Template : file_join_multi  |  PS-04
Purpose  : Chain-join three or more files sequentially.
           BASE_FILENAME (or input_paths[0]) is the base; JOIN_STEPS describes
           each subsequent join.
Contract : preprocess(input_paths: list) -> str

JOIN_STEPS format (Python list literal injected at generation time):

  Preferred — resolve by filename (safe with dir-scan, order-independent):
    [
        {"filename": "products.csv",  "join_key": "Product_ID",  "join_type": "left"},
        {"filename": "categories.csv","join_key": "Category_ID", "join_type": "inner"},
    ]

  Legacy — resolve by position (fragile if directory has extra files):
    [
        {"file_index": 1, "join_key": "Product_ID",  "join_type": "left"},
        {"file_index": 2, "join_key": "Category_ID", "join_type": "inner"},
    ]

  Both keys are optional per-step: "left_suffix" (default "_x"), "right_suffix" (default "_y")
  "filename" takes priority over "file_index" when both are present.
"""
from __future__ import annotations

import csv as _csv
import json as _json
import os
import tempfile as _tempfile
import zipfile as _zipfile
from pathlib import Path as _Path

import pandas as pd

# ── Configuration (substituted at generation time) ────────────────────────────
BASE_FILENAME   = "{{BASE_FILENAME}}"   # filename of the base file; "" = use input_paths[0]
JOIN_STEPS      = {{JOIN_STEPS}}
OUTPUT_DIR      = "{{OUTPUT_DIR}}"
OUTPUT_FILENAME = "{{OUTPUT_FILENAME}}"
OUTPUT_FORMAT   = "{{OUTPUT_FORMAT}}"
# ─────────────────────────────────────────────────────────────────────────────


# ── Embedded File Loader ──────────────────────────────────────────────────────
_ENCODINGS = ["utf-8", "cp1252", "latin-1"]


def _load_file(file_path: str) -> pd.DataFrame:
    ext = _Path(file_path).suffix.lower()
    if ext == ".zip":
        return _load_zip(file_path)
    if ext == ".xlsx":
        return pd.read_excel(file_path, engine="openpyxl")
    if ext == ".xls":
        return pd.read_excel(file_path, engine="xlrd")
    if ext == ".json":
        return _load_json(file_path)
    if ext == ".xml":
        return _load_xml(file_path)
    if ext in (".html", ".htm"):
        tables = pd.read_html(file_path)
        return tables[0] if tables else pd.DataFrame()
    return _load_delimited(file_path)


def _load_delimited(file_path: str) -> pd.DataFrame:
    for enc in _ENCODINGS:
        try:
            with open(file_path, "r", encoding=enc, errors="replace") as fh:
                sample = fh.read(8192)
            try:
                sep = _csv.Sniffer().sniff(sample).delimiter
            except _csv.Error:
                sep = ","
            return pd.read_csv(
                file_path, sep=sep, encoding=enc,
                on_bad_lines="skip", low_memory=False,
            )
        except Exception:
            continue
    raise ValueError(f"Cannot load delimited file: {file_path}")


def _load_json(file_path: str) -> pd.DataFrame:
    with open(file_path, "r", encoding="utf-8") as fh:
        data = _json.load(fh)
    return pd.json_normalize(data if isinstance(data, list) else [data])


def _load_xml(file_path: str) -> pd.DataFrame:
    try:
        import lxml.etree as _ET
        root = _ET.parse(file_path).getroot()
    except ImportError:
        import xml.etree.ElementTree as _ET  # type: ignore
        root = _ET.parse(file_path).getroot()
    records = [
        {el.tag: el.text for el in child.iter() if el.text and el.text.strip()}
        for child in root
    ]
    return pd.DataFrame(records)


def _load_zip(file_path: str) -> pd.DataFrame:
    _supported = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}
    with _zipfile.ZipFile(file_path, "r") as z:
        for name in z.namelist():
            if _Path(name).suffix.lower() in _supported:
                with _tempfile.TemporaryDirectory() as tmp_dir:
                    z.extract(name, tmp_dir)
                    return _load_file(os.path.join(tmp_dir, name))
    raise ValueError(f"No loadable file found inside ZIP: {file_path}")


def _write_output(df: pd.DataFrame, out_path: str, fmt: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _fmt = fmt.lower()
    if _fmt == "csv":
        df.to_csv(out_path, index=False)
    elif _fmt in ("xlsx", "excel"):
        df.to_excel(out_path, index=False, engine="openpyxl")
    elif _fmt == "json":
        df.to_json(out_path, orient="records", indent=2)
    elif _fmt == "parquet":
        df.to_parquet(out_path, index=False)
    elif _fmt == "tsv":
        df.to_csv(out_path, sep="\t", index=False)
    else:
        df.to_csv(out_path, index=False)
    return out_path

# ─────────────────────────────────────────────────────────────────────────────


def preprocess(input_paths: list) -> str:
    """
    Start with BASE_FILENAME (or input_paths[0]) as the base DataFrame, then
    for each step in JOIN_STEPS load the file by 'filename' (preferred) or
    'file_index' (legacy) and join it onto the cumulative result.

    Parameters
    ----------
    input_paths : list[str]
        List of file paths from the directory scan.  The base file is resolved
        by BASE_FILENAME if set, otherwise input_paths[0] is used.  Each
        JOIN_STEPS entry resolves its file by 'filename' (basename match) or
        'file_index' (positional fallback).

    Returns
    -------
    str
        Absolute path to the fully merged output file.
    """
    if not input_paths:
        raise ValueError("input_paths is empty.")

    # Resolve base file by name or fall back to first path
    if BASE_FILENAME:
        base_path = next(
            (p for p in input_paths if _Path(p).name == BASE_FILENAME), input_paths[0]
        )
    else:
        base_path = input_paths[0]

    result = _load_file(base_path)

    for step_num, step in enumerate(JOIN_STEPS, start=1):
        filename   = step.get("filename", "")
        file_index = step.get("file_index")
        join_key   = step.get("join_key")
        join_type  = step.get("join_type", "left")
        sfx_left   = step.get("left_suffix",  "_x")
        sfx_right  = step.get("right_suffix", "_y")

        if join_key is None:
            raise ValueError(
                f"JOIN_STEPS[{step_num}] must contain 'join_key'."
            )

        # Resolve step file: by filename (preferred) or file_index (legacy)
        if filename:
            other_path = next(
                (p for p in input_paths if _Path(p).name == filename), None
            )
            if other_path is None:
                raise ValueError(
                    f"JOIN_STEPS[{step_num}] specifies filename='{filename}' "
                    f"but no matching file was found in input_paths."
                )
        elif file_index is not None:
            if file_index >= len(input_paths):
                raise IndexError(
                    f"JOIN_STEPS[{step_num}] references file_index={file_index} "
                    f"but input_paths has only {len(input_paths)} entries."
                )
            other_path = input_paths[file_index]
        else:
            raise ValueError(
                f"JOIN_STEPS[{step_num}] must contain 'filename' or 'file_index'."
            )

        other = _load_file(other_path)
        result = result.merge(
            other,
            on=join_key,
            how=join_type,
            suffixes=(sfx_left, sfx_right),
        )

    _out_dir = OUTPUT_DIR if OUTPUT_DIR else os.path.dirname(os.path.abspath(base_path))
    out_path = os.path.join(_out_dir, OUTPUT_FILENAME)
    return _write_output(result, out_path, OUTPUT_FORMAT)
