"""
Generated by Data Preprocessing Script Library
Template : file_join_multi_key  |  PS-05
Purpose  : Join two files on a composite (multi-column) key.
           input_paths[0] = left file
           input_paths[1] = right file
Contract : preprocess(input_paths: list) -> str
"""
from __future__ import annotations

import csv as _csv
import json as _json
import os
import tempfile as _tempfile
import zipfile as _zipfile
from pathlib import Path as _Path

import pandas as pd

# ── Configuration (substituted at generation time) ────────────────────────────
JOIN_KEYS       = {{JOIN_KEYS}}           # shared key columns (used when LEFT_KEYS/RIGHT_KEYS are empty)
LEFT_KEYS       = {{LEFT_KEYS}}           # override: key columns in the LEFT file  (empty = use JOIN_KEYS)
RIGHT_KEYS      = {{RIGHT_KEYS}}          # override: key columns in the RIGHT file (empty = use JOIN_KEYS)
JOIN_TYPE       = "{{JOIN_TYPE}}"
LEFT_SUFFIX     = "{{LEFT_SUFFIX}}"
RIGHT_SUFFIX    = "{{RIGHT_SUFFIX}}"
LEFT_FILENAME   = "{{LEFT_FILENAME}}"    # file name for the left (primary) file
RIGHT_FILENAME  = "{{RIGHT_FILENAME}}"   # file name for the right file
OUTPUT_DIR      = "{{OUTPUT_DIR}}"
OUTPUT_FILENAME = "{{OUTPUT_FILENAME}}"
OUTPUT_FORMAT   = "{{OUTPUT_FORMAT}}"
# ─────────────────────────────────────────────────────────────────────────────


# ── Embedded File Loader ──────────────────────────────────────────────────────
_ENCODINGS = ["utf-8", "cp1252", "latin-1"]


def _load_file(file_path: str) -> pd.DataFrame:
    ext = _Path(file_path).suffix.lower()
    if ext == ".zip":
        return _load_zip(file_path)
    if ext == ".xlsx":
        return pd.read_excel(file_path, engine="openpyxl")
    if ext == ".xls":
        return pd.read_excel(file_path, engine="xlrd")
    if ext == ".json":
        return _load_json(file_path)
    if ext == ".xml":
        return _load_xml(file_path)
    if ext in (".html", ".htm"):
        tables = pd.read_html(file_path)
        return tables[0] if tables else pd.DataFrame()
    return _load_delimited(file_path)


def _load_delimited(file_path: str) -> pd.DataFrame:
    for enc in _ENCODINGS:
        try:
            with open(file_path, "r", encoding=enc, errors="replace") as fh:
                sample = fh.read(8192)
            try:
                sep = _csv.Sniffer().sniff(sample).delimiter
            except _csv.Error:
                sep = ","
            return pd.read_csv(
                file_path, sep=sep, encoding=enc,
                on_bad_lines="skip", low_memory=False,
            )
        except Exception:
            continue
    raise ValueError(f"Cannot load delimited file: {file_path}")


def _load_json(file_path: str) -> pd.DataFrame:
    with open(file_path, "r", encoding="utf-8") as fh:
        data = _json.load(fh)
    return pd.json_normalize(data if isinstance(data, list) else [data])


def _load_xml(file_path: str) -> pd.DataFrame:
    try:
        import lxml.etree as _ET
        root = _ET.parse(file_path).getroot()
    except ImportError:
        import xml.etree.ElementTree as _ET  # type: ignore
        root = _ET.parse(file_path).getroot()
    records = [
        {el.tag: el.text for el in child.iter() if el.text and el.text.strip()}
        for child in root
    ]
    return pd.DataFrame(records)


def _load_zip(file_path: str) -> pd.DataFrame:
    _supported = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}
    with _zipfile.ZipFile(file_path, "r") as z:
        for name in z.namelist():
            if _Path(name).suffix.lower() in _supported:
                with _tempfile.TemporaryDirectory() as tmp_dir:
                    z.extract(name, tmp_dir)
                    return _load_file(os.path.join(tmp_dir, name))
    raise ValueError(f"No loadable file found inside ZIP: {file_path}")


def _write_output(df: pd.DataFrame, out_path: str, fmt: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _fmt = fmt.lower()
    if _fmt == "csv":
        df.to_csv(out_path, index=False)
    elif _fmt in ("xlsx", "excel"):
        df.to_excel(out_path, index=False, engine="openpyxl")
    elif _fmt == "json":
        df.to_json(out_path, orient="records", indent=2)
    elif _fmt == "parquet":
        df.to_parquet(out_path, index=False)
    elif _fmt == "tsv":
        df.to_csv(out_path, sep="\t", index=False)
    else:
        df.to_csv(out_path, index=False)
    return out_path

# ─────────────────────────────────────────────────────────────────────────────


def _find_input_file(input_paths: list, filename: str, fallback_idx: int = 0) -> str:
    """Return the path in *input_paths* whose basename matches *filename*.
    Falls back to input_paths[fallback_idx] if no match is found."""
    for p in input_paths:
        if _Path(p).name == filename:
            return p
    return input_paths[fallback_idx]


def preprocess(input_paths: list) -> str:
    """
    Join LEFT_FILENAME and RIGHT_FILENAME on all columns in JOIN_KEYS
    simultaneously (composite key join).

    Parameters
    ----------
    input_paths : list[str]
        Must contain the two files whose names match LEFT_FILENAME and
        RIGHT_FILENAME. Order does not matter — files are found by name.

    Returns
    -------
    str
        Absolute path to the merged output file.
    """
    if len(input_paths) < 2:
        raise ValueError(
            f"file_join_multi_key requires exactly 2 input files; got {len(input_paths)}."
        )

    left_path  = _find_input_file(input_paths, LEFT_FILENAME,  0)
    right_path = _find_input_file(input_paths, RIGHT_FILENAME, 1)
    left  = _load_file(left_path)
    right = _load_file(right_path)

    # Resolve effective join keys:
    # LEFT_KEYS / RIGHT_KEYS override JOIN_KEYS when different column names are used.
    left_keys  = LEFT_KEYS  if LEFT_KEYS  else JOIN_KEYS
    right_keys = RIGHT_KEYS if RIGHT_KEYS else JOIN_KEYS

    if len(left_keys) != len(right_keys):
        raise ValueError(
            f"LEFT_KEYS ({left_keys}) and RIGHT_KEYS ({right_keys}) must have the same length."
        )

    missing_left  = [k for k in left_keys  if k not in left.columns]
    missing_right = [k for k in right_keys if k not in right.columns]
    if missing_left:
        raise KeyError(
            f"Join keys {missing_left} not found in left file ({LEFT_FILENAME}). "
            f"Available columns: {list(left.columns)}"
        )
    if missing_right:
        raise KeyError(
            f"Join keys {missing_right} not found in right file ({RIGHT_FILENAME}). "
            f"Available columns: {list(right.columns)}"
        )

    # Same key names on both sides → use on=; different names → use left_on/right_on
    if left_keys == right_keys:
        merged = left.merge(
            right,
            on=left_keys,
            how=JOIN_TYPE,
            suffixes=(LEFT_SUFFIX, RIGHT_SUFFIX),
        )
    else:
        merged = left.merge(
            right,
            left_on=left_keys,
            right_on=right_keys,
            how=JOIN_TYPE,
            suffixes=(LEFT_SUFFIX, RIGHT_SUFFIX),
        )
        # Drop the duplicate right key columns (pandas keeps them when using left_on/right_on)
        cols_to_drop = [k for k in right_keys if k in merged.columns and k not in left_keys]
        if cols_to_drop:
            merged = merged.drop(columns=cols_to_drop)

    _out_dir = OUTPUT_DIR if OUTPUT_DIR else os.path.dirname(os.path.abspath(input_paths[0]))
    out_path = os.path.join(_out_dir, OUTPUT_FILENAME)
    return _write_output(merged, out_path, OUTPUT_FORMAT)
