"""
Generated by Data Preprocessing Script Library
Template : file_union_zip  |  PS-02Z
Purpose  : Extract ALL files from one or more ZIP archives to the output
           directory, then vertically stack the file named INNER_FILE from
           each ZIP into one consolidated output.
           Non-ZIP inputs are used directly (no extraction needed).
           If INNER_FILE is "" the first supported file in each ZIP is used.
Contract : preprocess(input_paths: list) -> list
           input_paths[0..n] = ZIP file paths (or plain file paths)

Input patterns
--------------
1. One or more ZIP paths:
   preprocess(["/data/jan.zip", "/data/feb.zip"])
2. Single ZIP path (string or single-item list — both accepted):
   preprocess("/data/data.zip")
   preprocess(["/data/data.zip"])

Column mismatches
-----------------
Output columns are the UNION of all columns across all unioned files (first-seen
order). Missing values are filled with NaN.
"""
from __future__ import annotations

import csv as _csv
import json as _json
import os
import zipfile as _zipfile
from pathlib import Path as _Path

import pandas as pd

# ── Configuration (substituted at generation time) ────────────────────────────
INNER_FILE        = "{{INNER_FILE}}"         # file inside each ZIP to union; "" = first supported
OUTPUT_DIR        = "{{OUTPUT_DIR}}"
OUTPUT_FILENAME   = "{{OUTPUT_FILENAME}}"
OUTPUT_FORMAT     = "{{OUTPUT_FORMAT}}"
ADD_SOURCE_TAG    = {{ADD_SOURCE_TAG}}
SOURCE_TAG_COLUMN = "{{SOURCE_TAG_COLUMN}}"
# ─────────────────────────────────────────────────────────────────────────────


# ── Embedded File Loader ──────────────────────────────────────────────────────
_ENCODINGS = ["utf-8", "cp1252", "latin-1"]


def _load_file(file_path: str) -> pd.DataFrame:
    ext = _Path(file_path).suffix.lower()
    if ext == ".xlsx":
        return pd.read_excel(file_path, engine="openpyxl")
    if ext == ".xls":
        return pd.read_excel(file_path, engine="xlrd")
    if ext == ".json":
        return _load_json(file_path)
    if ext == ".xml":
        return _load_xml(file_path)
    if ext in (".html", ".htm"):
        tables = pd.read_html(file_path)
        return tables[0] if tables else pd.DataFrame()
    return _load_delimited(file_path)


def _load_delimited(file_path: str) -> pd.DataFrame:
    for enc in _ENCODINGS:
        try:
            with open(file_path, "r", encoding=enc, errors="replace") as fh:
                sample = fh.read(8192)
            try:
                sep = _csv.Sniffer().sniff(sample).delimiter
            except _csv.Error:
                sep = ","
            return pd.read_csv(
                file_path, sep=sep, encoding=enc,
                on_bad_lines="skip", low_memory=False,
            )
        except Exception:
            continue
    raise ValueError(f"Cannot load delimited file: {file_path}")


def _load_json(file_path: str) -> pd.DataFrame:
    with open(file_path, "r", encoding="utf-8") as fh:
        data = _json.load(fh)
    return pd.json_normalize(data if isinstance(data, list) else [data])


def _load_xml(file_path: str) -> pd.DataFrame:
    try:
        import lxml.etree as _ET
        root = _ET.parse(file_path).getroot()
    except ImportError:
        import xml.etree.ElementTree as _ET  # type: ignore
        root = _ET.parse(file_path).getroot()
    records = [
        {el.tag: el.text for el in child.iter() if el.text and el.text.strip()}
        for child in root
    ]
    return pd.DataFrame(records)


def _write_output(df: pd.DataFrame, out_path: str, fmt: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _fmt = fmt.lower()
    if _fmt == "csv":
        df.to_csv(out_path, index=False)
    elif _fmt in ("xlsx", "excel"):
        df.to_excel(out_path, index=False, engine="openpyxl")
    elif _fmt == "json":
        df.to_json(out_path, orient="records", indent=2)
    elif _fmt == "parquet":
        df.to_parquet(out_path, index=False)
    elif _fmt == "tsv":
        df.to_csv(out_path, sep="\t", index=False)
    else:
        df.to_csv(out_path, index=False)
    return out_path

# ─────────────────────────────────────────────────────────────────────────────


def _dedup_column_names(cols: list) -> list:
    seen: dict = {}
    out: list = []
    for c in cols:
        base = str(c)
        n = seen.get(base, 0)
        out.append(base if n == 0 else f"{base}.{n}")
        seen[base] = n + 1
    return out


def _ensure_string_unique_columns(df: pd.DataFrame) -> pd.DataFrame:
    cols = [str(c) for c in df.columns.tolist()]
    if len(cols) == len(set(cols)):
        df.columns = cols
        return df
    df = df.copy()
    df.columns = _dedup_column_names(cols)
    return df


def _union_align_columns(frames: list) -> list:
    """Union of all columns across frames; missing values filled with NaN."""
    if not frames:
        return frames
    ordered_cols: list = []
    normalized: list = []
    for df in frames:
        df = _ensure_string_unique_columns(df)
        normalized.append(df)
        for c in df.columns.tolist():
            if c not in ordered_cols:
                ordered_cols.append(c)
    return [df.reindex(columns=ordered_cols) for df in normalized]


def _resolve_and_extract(input_paths: list, out_dir: str) -> tuple:
    """
    For each input path:
      - ZIP  → extract ALL files to out_dir; pick INNER_FILE (or first supported)
               for the union.
      - File → use directly for the union (no extraction).
    Returns (union_file_paths, all_extracted_paths).
    """
    os.makedirs(out_dir, exist_ok=True)
    _supported = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}
    union_files: list = []
    all_extracted: list = []

    for raw in input_paths:
        path = str(raw).strip()
        if _Path(path).suffix.lower() == ".zip":
            name_map: dict = {}
            with _zipfile.ZipFile(path, "r") as zf:
                for member in zf.namelist():
                    fname = os.path.basename(member)
                    if not fname:
                        continue
                    dest = os.path.join(out_dir, fname)
                    with zf.open(member) as src, open(dest, "wb") as dst:
                        dst.write(src.read())
                    all_extracted.append(dest)
                    name_map[fname.lower()] = dest

            if INNER_FILE:
                if INNER_FILE.lower() not in name_map:
                    raise ValueError(f"'{INNER_FILE}' not found inside ZIP: {path}")
                union_files.append(name_map[INNER_FILE.lower()])
            else:
                picked = next(
                    (p for n, p in name_map.items()
                     if _Path(n).suffix.lower() in _supported),
                    None,
                )
                if picked is None:
                    raise ValueError(f"No supported file found inside ZIP: {path}")
                union_files.append(picked)
        else:
            union_files.append(path)

    return union_files, all_extracted


def preprocess(input_paths: list) -> list:
    """
    Extract ALL files from each ZIP input to OUTPUT_DIR, then vertically
    stack the INNER_FILE from each ZIP into one consolidated output.

    Parameters
    ----------
    input_paths : list[str] | str
        One or more ZIP file paths (or plain file paths).
        A bare string is wrapped into a single-element list automatically.

    Returns
    -------
    list[str]
        All extracted files from every ZIP + the merged union output file.
    """
    if isinstance(input_paths, str):
        input_paths = [input_paths]
    elif not isinstance(input_paths, list):
        input_paths = list(input_paths)

    if not input_paths:
        raise ValueError("input_paths is empty — at least one file is required.")

    _out_dir = OUTPUT_DIR if OUTPUT_DIR else os.path.dirname(
        os.path.abspath(str(input_paths[0]))
    )

    union_files, all_extracted = _resolve_and_extract(input_paths, _out_dir)

    frames: list = []
    for path in union_files:
        df = _load_file(path)
        df = _ensure_string_unique_columns(df)
        frames.append(df)

    if ADD_SOURCE_TAG:
        for i, path in enumerate(union_files):
            frames[i] = frames[i].copy()
            frames[i][SOURCE_TAG_COLUMN] = _Path(path).name

    frames = _union_align_columns(frames)
    combined = pd.concat(frames, ignore_index=True, sort=False)

    out_path = os.path.join(_out_dir, OUTPUT_FILENAME)
    return all_extracted + [_write_output(combined, out_path, OUTPUT_FORMAT)]

# ── __main__ block is appended by the Gradio app at generation time ───────────
