"""
Generated by Data Preprocessing Script Library
Template : file_rename_columns  |  PS-11
Purpose  : Rename columns according to COLUMN_MAPPING (source → target).
           Optionally drops columns whose source name is not in the mapping.
Contract : preprocess(input_path: str) -> list
"""
from __future__ import annotations

import csv as _csv
import json as _json
import os
import tempfile as _tempfile
import zipfile as _zipfile
from pathlib import Path as _Path

import pandas as pd

# ── Configuration (substituted at generation time) ────────────────────────────
COLUMN_MAPPING  = {{COLUMN_MAPPING}}
DROP_UNMAPPED   = {{DROP_UNMAPPED}}
OUTPUT_DIR      = "{{OUTPUT_DIR}}"
OUTPUT_FILENAME = "{{OUTPUT_FILENAME}}"
OUTPUT_FORMAT   = "{{OUTPUT_FORMAT}}"
# ─────────────────────────────────────────────────────────────────────────────


# ── Embedded File Loader ──────────────────────────────────────────────────────
_ENCODINGS = ["utf-8", "cp1252", "latin-1"]


def _load_file(file_path: str) -> pd.DataFrame:
    ext = _Path(file_path).suffix.lower()
    if ext == ".zip":
        return _load_zip(file_path)
    if ext == ".xlsx":
        return pd.read_excel(file_path, engine="openpyxl")
    if ext == ".xls":
        return pd.read_excel(file_path, engine="xlrd")
    if ext == ".json":
        return _load_json(file_path)
    if ext == ".xml":
        return _load_xml(file_path)
    if ext in (".html", ".htm"):
        tables = pd.read_html(file_path)
        return tables[0] if tables else pd.DataFrame()
    return _load_delimited(file_path)


def _load_delimited(file_path: str) -> pd.DataFrame:
    for enc in _ENCODINGS:
        try:
            with open(file_path, "r", encoding=enc, errors="replace") as fh:
                sample = fh.read(8192)
            try:
                sep = _csv.Sniffer().sniff(sample).delimiter
            except _csv.Error:
                sep = ","
            return pd.read_csv(
                file_path, sep=sep, encoding=enc,
                on_bad_lines="skip", low_memory=False,
            )
        except Exception:
            continue
    raise ValueError(f"Cannot load delimited file: {file_path}")


def _load_json(file_path: str) -> pd.DataFrame:
    with open(file_path, "r", encoding="utf-8") as fh:
        data = _json.load(fh)
    return pd.json_normalize(data if isinstance(data, list) else [data])


def _load_xml(file_path: str) -> pd.DataFrame:
    try:
        import lxml.etree as _ET
        root = _ET.parse(file_path).getroot()
    except ImportError:
        import xml.etree.ElementTree as _ET  # type: ignore
        root = _ET.parse(file_path).getroot()
    records = [
        {el.tag: el.text for el in child.iter() if el.text and el.text.strip()}
        for child in root
    ]
    return pd.DataFrame(records)


def _load_zip(file_path: str) -> pd.DataFrame:
    _supported = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}
    with _tempfile.TemporaryDirectory() as tmp_dir:
        with _zipfile.ZipFile(file_path, "r") as z:
            names = [n for n in z.namelist() if _Path(n).suffix.lower() in _supported]
            for name in names:
                z.extract(name, tmp_dir)
        if names:
            return _load_file(os.path.join(tmp_dir, names[0]))
    raise ValueError(f"No loadable file found inside ZIP: {file_path}")


def _write_output(df: pd.DataFrame, out_path: str, fmt: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _fmt = fmt.lower()
    if _fmt == "csv":
        df.to_csv(out_path, index=False)
    elif _fmt in ("xlsx", "excel"):
        df.to_excel(out_path, index=False, engine="openpyxl")
    elif _fmt == "json":
        df.to_json(out_path, orient="records", indent=2)
    elif _fmt == "parquet":
        df.to_parquet(out_path, index=False)
    elif _fmt == "tsv":
        df.to_csv(out_path, sep="\t", index=False)
    else:
        df.to_csv(out_path, index=False)
    return out_path

# ─────────────────────────────────────────────────────────────────────────────


def preprocess(input_path: str) -> list:
    """
    Rename columns using COLUMN_MAPPING.  Source columns not present in the
    file are silently skipped.  If DROP_UNMAPPED is True, columns whose
    source name is not a key in COLUMN_MAPPING are dropped from the output.

    Parameters
    ----------
    input_path : str
        Path to the source file.

    Returns
    -------
    list
        Absolute path to the renamed output file.
    """
    if isinstance(input_path, list):
        input_path = input_path[0]

    _out_dir = OUTPUT_DIR if OUTPUT_DIR else os.path.dirname(os.path.abspath(input_path))
    os.makedirs(_out_dir, exist_ok=True)

    if _Path(input_path).suffix.lower() == ".zip":
        _supported = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}
        output_paths: list = []
        with _tempfile.TemporaryDirectory() as tmp_dir:
            with _zipfile.ZipFile(input_path, "r") as z:
                names = [n for n in z.namelist() if _Path(n).suffix.lower() in _supported]
                for name in names:
                    z.extract(name, tmp_dir)
            for name in names:
                df = _load_file(os.path.join(tmp_dir, name))
                stem = _Path(os.path.basename(name)).stem
                rename_map = {src: tgt for src, tgt in COLUMN_MAPPING.items() if src in df.columns}
                df = df.rename(columns=rename_map)
                if DROP_UNMAPPED:
                    keep_cols = list(COLUMN_MAPPING.values())
                    df = df[[c for c in keep_cols if c in df.columns]]
                out_path = os.path.join(_out_dir, f"{stem}.{OUTPUT_FORMAT.lower()}")
                output_paths.append(_write_output(df, out_path, OUTPUT_FORMAT))
        return output_paths

    df = _load_file(input_path)

    # Only rename columns that actually exist in the DataFrame
    rename_map = {src: tgt for src, tgt in COLUMN_MAPPING.items() if src in df.columns}
    df = df.rename(columns=rename_map)

    if DROP_UNMAPPED:
        # Keep only the target (renamed) column names
        keep_cols = list(COLUMN_MAPPING.values())
        df = df[[c for c in keep_cols if c in df.columns]]

    out_path = os.path.join(_out_dir, OUTPUT_FILENAME)
    return [_write_output(df, out_path, OUTPUT_FORMAT)]
