"""
Generated by Data Preprocessing Script Library
Template : file_cast_types  |  PS-13
Purpose  : Cast columns to target data types and apply formatting standards.
           Produces a type-safe output file and a cast error report.
Contract : preprocess(input_path: str) -> str

TYPE_RULES format (Python list literal injected at generation time):
    [
        {"column": "Invoice_Date",   "target_type": "date",    "format": "%d/%m/%Y"},
        {"column": "Invoice_Amount", "target_type": "float"},
        {"column": "Account_Number", "target_type": "string"},
        {"column": "Is_Active",      "target_type": "boolean"},
        {"column": "Qty",            "target_type": "integer"},
    ]

Supported target_type values : string | integer | float | date | boolean
ON_ERROR options              : nullify | keep_original | drop_row
"""
from __future__ import annotations

import csv as _csv
import json as _json
import os
import tempfile as _tempfile
import zipfile as _zipfile
from pathlib import Path as _Path

import pandas as pd

# ── Configuration (substituted at generation time) ────────────────────────────
TYPE_RULES                 = {{TYPE_RULES}}
STRIP_CURRENCY             = {{STRIP_CURRENCY}}
TRIM_STRINGS               = {{TRIM_STRINGS}}
ON_ERROR                   = "{{ON_ERROR}}"
OUTPUT_DIR                 = "{{OUTPUT_DIR}}"
OUTPUT_FILENAME            = "{{OUTPUT_FILENAME}}"
CAST_ERROR_REPORT_FILENAME = "{{CAST_ERROR_REPORT_FILENAME}}"
OUTPUT_FORMAT              = "{{OUTPUT_FORMAT}}"
# ─────────────────────────────────────────────────────────────────────────────


# ── Embedded File Loader ──────────────────────────────────────────────────────
_ENCODINGS = ["utf-8", "cp1252", "latin-1"]


def _load_file(file_path: str) -> pd.DataFrame:
    ext = _Path(file_path).suffix.lower()
    if ext == ".zip":
        return _load_zip(file_path)
    if ext == ".xlsx":
        return pd.read_excel(file_path, engine="openpyxl")
    if ext == ".xls":
        return pd.read_excel(file_path, engine="xlrd")
    if ext == ".json":
        return _load_json(file_path)
    if ext == ".xml":
        return _load_xml(file_path)
    if ext in (".html", ".htm"):
        tables = pd.read_html(file_path)
        return tables[0] if tables else pd.DataFrame()
    return _load_delimited(file_path)


def _load_delimited(file_path: str) -> pd.DataFrame:
    for enc in _ENCODINGS:
        try:
            with open(file_path, "r", encoding=enc, errors="replace") as fh:
                sample = fh.read(8192)
            try:
                sep = _csv.Sniffer().sniff(sample).delimiter
            except _csv.Error:
                sep = ","
            return pd.read_csv(
                file_path, sep=sep, encoding=enc,
                on_bad_lines="skip", low_memory=False,
            )
        except Exception:
            continue
    raise ValueError(f"Cannot load delimited file: {file_path}")


def _load_json(file_path: str) -> pd.DataFrame:
    with open(file_path, "r", encoding="utf-8") as fh:
        data = _json.load(fh)
    return pd.json_normalize(data if isinstance(data, list) else [data])


def _load_xml(file_path: str) -> pd.DataFrame:
    try:
        import lxml.etree as _ET
        root = _ET.parse(file_path).getroot()
    except ImportError:
        import xml.etree.ElementTree as _ET  # type: ignore
        root = _ET.parse(file_path).getroot()
    records = [
        {el.tag: el.text for el in child.iter() if el.text and el.text.strip()}
        for child in root
    ]
    return pd.DataFrame(records)


def _load_zip(file_path: str) -> pd.DataFrame:
    _supported = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}
    with _zipfile.ZipFile(file_path, "r") as z:
        for name in z.namelist():
            if _Path(name).suffix.lower() in _supported:
                with _tempfile.TemporaryDirectory() as tmp_dir:
                    z.extract(name, tmp_dir)
                    return _load_file(os.path.join(tmp_dir, name))
    raise ValueError(f"No loadable file found inside ZIP: {file_path}")


def _write_output(df: pd.DataFrame, out_path: str, fmt: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _fmt = fmt.lower()
    if _fmt == "csv":
        df.to_csv(out_path, index=False)
    elif _fmt in ("xlsx", "excel"):
        df.to_excel(out_path, index=False, engine="openpyxl")
    elif _fmt == "json":
        df.to_json(out_path, orient="records", indent=2)
    elif _fmt == "parquet":
        df.to_parquet(out_path, index=False)
    elif _fmt == "tsv":
        df.to_csv(out_path, sep="\t", index=False)
    else:
        df.to_csv(out_path, index=False)
    return out_path

# ─────────────────────────────────────────────────────────────────────────────

_BOOL_TRUE  = {"true", "yes", "1", "y", "t"}
_BOOL_FALSE = {"false", "no", "0", "n", "f"}


def preprocess(input_path: str) -> str:
    """
    Cast each column specified in TYPE_RULES to its target type.
    Failed casts are logged to CAST_ERROR_REPORT_FILENAME.
    ON_ERROR controls what happens to rows with cast failures:
        nullify       — replace failed value with NaN/NaT
        keep_original — leave the original value unchanged
        drop_row      — remove the row from the output

    Parameters
    ----------
    input_path : str
        Path to the source file.

    Returns
    -------
    str
        Absolute path to the typed output file.
    """
    df = _load_file(input_path)

    # Global string trimming (applied before type casting)
    if TRIM_STRINGS:
        for col in df.select_dtypes(include=["object"]).columns:
            df[col] = df[col].astype(str).str.strip().replace("nan", pd.NA)

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    error_records: list[dict] = []

    for rule in TYPE_RULES:
        col         = rule.get("column", "")
        target_type = rule.get("target_type", "string")

        if col not in df.columns:
            continue

        original = df[col].copy()

        # ── string ───────────────────────────────────────────────────────────
        if target_type == "string":
            df[col] = df[col].astype(str).str.strip().replace("nan", pd.NA)

        # ── integer / float ───────────────────────────────────────────────────
        elif target_type in ("integer", "float"):
            if STRIP_CURRENCY:
                df[col] = (
                    df[col].astype(str)
                    .str.replace(r"[£$€,\s]", "", regex=True)
                    .replace("nan", pd.NA)
                )
            numeric   = pd.to_numeric(df[col], errors="coerce")
            fail_mask = numeric.isna() & original.notna() & (
                original.astype(str).str.strip().replace("nan", "") != ""
            )
            if fail_mask.any():
                for idx in df.index[fail_mask]:
                    error_records.append({
                        "row_index":      idx,
                        "column":         col,
                        "original_value": original.at[idx],
                        "target_type":    target_type,
                        "error":          "cast_failed",
                    })
                if ON_ERROR == "nullify":
                    df[col] = numeric
                elif ON_ERROR == "drop_row":
                    df = df[~fail_mask].reset_index(drop=True)
                    numeric = pd.to_numeric(df[col], errors="coerce")
                    df[col] = numeric
                # keep_original: leave df[col] as-is for failed rows
                else:
                    df.loc[~fail_mask, col] = numeric[~fail_mask]
            else:
                df[col] = numeric

            if target_type == "integer" and col in df.columns:
                df[col] = df[col].astype("Int64")

        # ── date ──────────────────────────────────────────────────────────────
        elif target_type == "date":
            date_fmt  = rule.get("format", None)
            converted = pd.to_datetime(df[col], format=date_fmt, errors="coerce", dayfirst=False)
            fail_mask = converted.isna() & original.notna() & (
                original.astype(str).str.strip().replace("nan", "") != ""
            )
            if fail_mask.any():
                for idx in df.index[fail_mask]:
                    error_records.append({
                        "row_index":      idx,
                        "column":         col,
                        "original_value": original.at[idx],
                        "target_type":    target_type,
                        "error":          f"cast_failed (expected format: {date_fmt})",
                    })
                if ON_ERROR == "nullify":
                    df[col] = converted
                elif ON_ERROR == "keep_original":
                    df.loc[~fail_mask, col] = converted[~fail_mask]
                elif ON_ERROR == "drop_row":
                    df = df[~fail_mask].reset_index(drop=True)
                    df[col] = pd.to_datetime(df[col], format=date_fmt, errors="coerce")
            else:
                df[col] = converted

        # ── boolean ───────────────────────────────────────────────────────────
        elif target_type == "boolean":
            str_col = df[col].astype(str).str.lower().str.strip()
            df[col] = str_col.map(
                lambda v: True if v in _BOOL_TRUE else (False if v in _BOOL_FALSE else pd.NA)
            )

    # Write cast error report
    if error_records:
        err_df = pd.DataFrame(error_records)
        _write_output(err_df, os.path.join(OUTPUT_DIR, CAST_ERROR_REPORT_FILENAME), OUTPUT_FORMAT)

    _out_dir = OUTPUT_DIR if OUTPUT_DIR else os.path.dirname(os.path.abspath(input_path))
    out_path = os.path.join(_out_dir, OUTPUT_FILENAME)
    return _write_output(df, out_path, OUTPUT_FORMAT)
