"""
Generated by Data Preprocessing Script Library
Template : file_column_split  |  PS-19
Purpose  : Split one file into multiple output files based on the values in a
           specified column.  A single template handles all split/filter-by-value
           patterns: single-value splits, multi-value groups, and multi-group
           splits — all through configuration.
Contract : preprocess(input_paths: list) -> list

GROUPS format
-------------
A list of dicts.  Each dict:
  {"label":           "group_name",       # unique internal label
   "values":          ["A", "B"],         # values that map to this group
   "output_filename": "group_a_b.csv"}    # output file name for this group

NULL_HANDLING options   (rows where SPLIT_COLUMN is null/NaN)
---------------------
  "separate_file"              → write null rows to NULL_FILENAME
  "merge_into_group:<label>"   → add null rows to the named group
  "merge_into_remaining"       → treat null rows as unmatched/remaining
  "ignore"                     → discard null rows

REMAINING_HANDLING options   (rows whose value matched no group)
--------------------------
  "separate_file"              → write unmatched rows to REMAINING_FILENAME
  "merge_into_group:<label>"   → add unmatched rows to the named group
  "ignore"                     → discard unmatched rows
"""
from __future__ import annotations

import csv as _csv
import json as _json
import os
import tempfile as _tempfile
import zipfile as _zipfile
from pathlib import Path as _Path

import pandas as pd

# ── Configuration (substituted at generation time) ────────────────────────────
SPLIT_COLUMN       = "{{SPLIT_COLUMN}}"
GROUPS             = {{GROUPS}}
CASE_SENSITIVE     = {{CASE_SENSITIVE}}    # False = case-insensitive value matching
INCLUDE_SPLIT_COLUMN = {{INCLUDE_SPLIT_COLUMN}}  # keep SPLIT_COLUMN in output files
NULL_HANDLING      = "{{NULL_HANDLING}}"   # separate_file | merge_into_group:<label> | merge_into_remaining | ignore
NULL_FILENAME      = "{{NULL_FILENAME}}"   # used when NULL_HANDLING = "separate_file"
REMAINING_HANDLING = "{{REMAINING_HANDLING}}"  # separate_file | merge_into_group:<label> | ignore
REMAINING_FILENAME = "{{REMAINING_FILENAME}}"  # used when REMAINING_HANDLING = "separate_file"
OUTPUT_DIR         = "{{OUTPUT_DIR}}"
OUTPUT_FORMAT      = "{{OUTPUT_FORMAT}}"
# ─────────────────────────────────────────────────────────────────────────────


# ── Embedded File Loader ──────────────────────────────────────────────────────
_ENCODINGS = ["utf-8", "cp1252", "latin-1"]


def _load_file(file_path: str) -> pd.DataFrame:
    ext = _Path(file_path).suffix.lower()
    if ext == ".zip":
        return _load_zip(file_path)
    if ext == ".xlsx":
        return pd.read_excel(file_path, engine="openpyxl")
    if ext == ".xls":
        return pd.read_excel(file_path, engine="xlrd")
    if ext == ".json":
        return _load_json(file_path)
    if ext == ".xml":
        return _load_xml(file_path)
    if ext in (".html", ".htm"):
        tables = pd.read_html(file_path)
        return tables[0] if tables else pd.DataFrame()
    return _load_delimited(file_path)


def _load_delimited(file_path: str) -> pd.DataFrame:
    for enc in _ENCODINGS:
        try:
            with open(file_path, "r", encoding=enc, errors="replace") as fh:
                sample = fh.read(8192)
            try:
                sep = _csv.Sniffer().sniff(sample).delimiter
            except _csv.Error:
                sep = ","
            return pd.read_csv(
                file_path, sep=sep, encoding=enc,
                on_bad_lines="skip", low_memory=False,
            )
        except Exception:
            continue
    raise ValueError(f"Cannot load delimited file: {file_path}")


def _load_json(file_path: str) -> pd.DataFrame:
    with open(file_path, "r", encoding="utf-8") as fh:
        data = _json.load(fh)
    return pd.json_normalize(data if isinstance(data, list) else [data])


def _load_xml(file_path: str) -> pd.DataFrame:
    try:
        import lxml.etree as _ET
        root = _ET.parse(file_path).getroot()
    except ImportError:
        import xml.etree.ElementTree as _ET  # type: ignore
        root = _ET.parse(file_path).getroot()
    records = [
        {el.tag: el.text for el in child.iter() if el.text and el.text.strip()}
        for child in root
    ]
    return pd.DataFrame(records)


def _load_zip(file_path: str) -> pd.DataFrame:
    _supported = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}
    with _zipfile.ZipFile(file_path, "r") as z:
        for name in z.namelist():
            if _Path(name).suffix.lower() in _supported:
                with _tempfile.TemporaryDirectory() as tmp_dir:
                    extracted = z.extract(name, tmp_dir)
                    return _load_file(extracted)
    raise ValueError(f"No loadable file found inside ZIP: {file_path}")


def _write_output(df: pd.DataFrame, out_path: str, fmt: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _fmt = fmt.lower()
    if _fmt == "csv":
        df.to_csv(out_path, index=False)
    elif _fmt in ("xlsx", "excel"):
        df.to_excel(out_path, index=False, engine="openpyxl")
    elif _fmt == "json":
        df.to_json(out_path, orient="records", indent=2)
    elif _fmt == "parquet":
        df.to_parquet(out_path, index=False)
    elif _fmt == "tsv":
        df.to_csv(out_path, sep="\t", index=False)
    else:
        df.to_csv(out_path, index=False)
    return out_path

# ─────────────────────────────────────────────────────────────────────────────


def _normalise(val: str) -> str:
    return val if CASE_SENSITIVE else val.lower()


def preprocess(input_paths: list) -> list:
    """
    Split the input file into multiple output files based on SPLIT_COLUMN values.

    Routing logic
    -------------
    1. Rows where SPLIT_COLUMN is null/NaN → routed by NULL_HANDLING.
    2. Remaining rows matched against each group's values list (first-match-wins,
       respecting CASE_SENSITIVE).  Matched rows → that group's output file.
    3. Rows that matched no group → routed by REMAINING_HANDLING.

    Parameters
    ----------
    input_paths : list[str] | str
        Single input file path.

    Returns
    -------
    list[str]
        Paths to all written output files (one per non-empty group / null / remaining).
    """
    if isinstance(input_paths, str):
        input_paths = [input_paths]
    elif not isinstance(input_paths, list):
        input_paths = list(input_paths)

    if not input_paths:
        raise ValueError("input_paths is empty.")

    file_path = input_paths[0]
    _out_dir = OUTPUT_DIR if OUTPUT_DIR else os.path.dirname(os.path.abspath(file_path))

    df = _load_file(file_path)

    if SPLIT_COLUMN not in df.columns:
        raise KeyError(
            f"SPLIT_COLUMN '{SPLIT_COLUMN}' not found. "
            f"Available columns: {list(df.columns)}"
        )

    # ── Separate null rows ────────────────────────────────────────────────────
    null_mask = df[SPLIT_COLUMN].isna()
    null_df   = df[null_mask].copy()
    work_df   = df[~null_mask].copy()

    # ── Build normalised lookup for each group ────────────────────────────────
    # Each group entry: {"label": str, "values": [str], "output_filename": str}
    group_value_sets: list[set] = []
    for group in GROUPS:
        raw_vals = group.get("values", [])
        group_value_sets.append({_normalise(str(v)) for v in raw_vals})

    # ── Assign each non-null row to the first matching group ──────────────────
    col_str = work_df[SPLIT_COLUMN].astype(str)
    if not CASE_SENSITIVE:
        col_normalised = col_str.str.lower()
    else:
        col_normalised = col_str

    group_frames: dict[str, pd.DataFrame] = {
        str(g["label"]): pd.DataFrame(columns=work_df.columns)
        for g in GROUPS
    }
    assigned = pd.Series(False, index=work_df.index)

    for i, group in enumerate(GROUPS):
        label   = str(group["label"])
        val_set = group_value_sets[i]
        mask    = col_normalised.isin(val_set) & ~assigned
        group_frames[label] = work_df[mask].copy()
        assigned |= mask

    remaining_df = work_df[~assigned].copy()

    # ── Apply null handling ───────────────────────────────────────────────────
    if NULL_HANDLING == "separate_file":
        pass
    elif NULL_HANDLING.startswith("merge_into_group:"):
        target = NULL_HANDLING.split(":", 1)[1].strip()
        if target in group_frames:
            group_frames[target] = pd.concat(
                [group_frames[target], null_df], ignore_index=True
            )
        null_df = pd.DataFrame()
    elif NULL_HANDLING == "merge_into_remaining":
        remaining_df = pd.concat([remaining_df, null_df], ignore_index=True)
        null_df = pd.DataFrame()
    else:  # "ignore"
        null_df = pd.DataFrame()

    # ── Apply remaining handling ──────────────────────────────────────────────
    if REMAINING_HANDLING == "separate_file":
        pass
    elif REMAINING_HANDLING.startswith("merge_into_group:"):
        target = REMAINING_HANDLING.split(":", 1)[1].strip()
        if target in group_frames:
            group_frames[target] = pd.concat(
                [group_frames[target], remaining_df], ignore_index=True
            )
        remaining_df = pd.DataFrame()
    else:  # "ignore"
        remaining_df = pd.DataFrame()

    # ── Optionally drop the split column ─────────────────────────────────────
    def _maybe_drop_col(frame: pd.DataFrame) -> pd.DataFrame:
        if not INCLUDE_SPLIT_COLUMN and SPLIT_COLUMN in frame.columns:
            return frame.drop(columns=[SPLIT_COLUMN])
        return frame

    # ── Write outputs ─────────────────────────────────────────────────────────
    output_paths: list = []

    for group in GROUPS:
        label    = str(group["label"])
        filename = str(group.get("output_filename", f"{label}.csv"))
        frame    = _maybe_drop_col(group_frames.get(label, pd.DataFrame()))
        if not frame.empty:
            out_path = os.path.join(_out_dir, filename)
            output_paths.append(_write_output(frame, out_path, OUTPUT_FORMAT))

    if not null_df.empty and NULL_HANDLING == "separate_file" and NULL_FILENAME:
        out_path = os.path.join(_out_dir, NULL_FILENAME)
        output_paths.append(_write_output(_maybe_drop_col(null_df), out_path, OUTPUT_FORMAT))

    if not remaining_df.empty and REMAINING_HANDLING == "separate_file" and REMAINING_FILENAME:
        out_path = os.path.join(_out_dir, REMAINING_FILENAME)
        output_paths.append(_write_output(_maybe_drop_col(remaining_df), out_path, OUTPUT_FORMAT))

    return output_paths

# ── __main__ block is appended by the Gradio app at generation time ───────────
