"""
Generated by Data Preprocessing Script Library
Template : file_column_split_zip  |  PS-19Z
Purpose  : Extract ALL files from a ZIP archive to the output directory, then
           split the named inner file into multiple output files based on the
           values in a specified column.
           All other ZIPs found in the same base directory are also extracted.
Contract : preprocess(input_paths: list) -> list
           input_paths[0] = ZIP file path (or plain file path)

GROUPS format
-------------
A list of dicts.  Each dict:
  {"label":           "group_name",       # unique internal label
   "values":          ["A", "B"],         # values that map to this group
   "output_filename": "group_a_b.csv"}    # output file name for this group

NULL_HANDLING / REMAINING_HANDLING options — see file_column_split_template.py
"""
from __future__ import annotations

import csv as _csv
import json as _json
import os
import zipfile as _zipfile
from pathlib import Path as _Path

import pandas as pd

# ── Configuration (substituted at generation time) ────────────────────────────
INNER_FILE         = "{{INNER_FILE}}"      # file inside the ZIP to process; "" = first supported
SPLIT_COLUMN       = "{{SPLIT_COLUMN}}"
GROUPS             = {{GROUPS}}
CASE_SENSITIVE     = {{CASE_SENSITIVE}}
INCLUDE_SPLIT_COLUMN = {{INCLUDE_SPLIT_COLUMN}}
NULL_HANDLING      = "{{NULL_HANDLING}}"
NULL_FILENAME      = "{{NULL_FILENAME}}"
REMAINING_HANDLING = "{{REMAINING_HANDLING}}"
REMAINING_FILENAME = "{{REMAINING_FILENAME}}"
OUTPUT_DIR         = "{{OUTPUT_DIR}}"
OUTPUT_FORMAT      = "{{OUTPUT_FORMAT}}"
# ─────────────────────────────────────────────────────────────────────────────


# ── Embedded File Loader ──────────────────────────────────────────────────────
_ENCODINGS = ["utf-8", "cp1252", "latin-1"]
_SUPPORTED = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}


def _load_file(file_path: str) -> pd.DataFrame:
    ext = _Path(file_path).suffix.lower()
    if ext == ".xlsx":
        return pd.read_excel(file_path, engine="openpyxl")
    if ext == ".xls":
        return pd.read_excel(file_path, engine="xlrd")
    if ext == ".json":
        return _load_json(file_path)
    if ext == ".xml":
        return _load_xml(file_path)
    if ext in (".html", ".htm"):
        tables = pd.read_html(file_path)
        return tables[0] if tables else pd.DataFrame()
    return _load_delimited(file_path)


def _load_delimited(file_path: str) -> pd.DataFrame:
    for enc in _ENCODINGS:
        try:
            with open(file_path, "r", encoding=enc, errors="replace") as fh:
                sample = fh.read(8192)
            try:
                sep = _csv.Sniffer().sniff(sample).delimiter
            except _csv.Error:
                sep = ","
            return pd.read_csv(
                file_path, sep=sep, encoding=enc,
                on_bad_lines="skip", low_memory=False,
            )
        except Exception:
            continue
    raise ValueError(f"Cannot load delimited file: {file_path}")


def _load_json(file_path: str) -> pd.DataFrame:
    with open(file_path, "r", encoding="utf-8") as fh:
        data = _json.load(fh)
    return pd.json_normalize(data if isinstance(data, list) else [data])


def _load_xml(file_path: str) -> pd.DataFrame:
    try:
        import lxml.etree as _ET
        root = _ET.parse(file_path).getroot()
    except ImportError:
        import xml.etree.ElementTree as _ET  # type: ignore
        root = _ET.parse(file_path).getroot()
    records = [
        {el.tag: el.text for el in child.iter() if el.text and el.text.strip()}
        for child in root
    ]
    return pd.DataFrame(records)


def _write_output(df: pd.DataFrame, out_path: str, fmt: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _fmt = fmt.lower()
    if _fmt == "csv":
        df.to_csv(out_path, index=False)
    elif _fmt in ("xlsx", "excel"):
        df.to_excel(out_path, index=False, engine="openpyxl")
    elif _fmt == "json":
        df.to_json(out_path, orient="records", indent=2)
    elif _fmt == "parquet":
        df.to_parquet(out_path, index=False)
    elif _fmt == "tsv":
        df.to_csv(out_path, sep="\t", index=False)
    else:
        df.to_csv(out_path, index=False)
    return out_path

# ─────────────────────────────────────────────────────────────────────────────


def _normalise(val: str) -> str:
    return val if CASE_SENSITIVE else val.lower()


def _extract_zip_all(zip_path: str, out_dir: str) -> dict:
    """Extract every file in the ZIP to out_dir; return {lower_name: dest_path}."""
    name_map: dict = {}
    with _zipfile.ZipFile(zip_path, "r") as zf:
        for member in zf.namelist():
            fname = os.path.basename(member)
            if not fname:
                continue
            dest = os.path.join(out_dir, fname)
            with zf.open(member) as src, open(dest, "wb") as dst:
                dst.write(src.read())
            name_map[fname.lower()] = dest
    return name_map


def preprocess(input_paths: list) -> list:
    """
    Extract ALL files from the input ZIP to OUTPUT_DIR, scan the base directory
    for any additional ZIPs and extract those too, then split the INNER_FILE
    (or first supported file) into multiple output files based on SPLIT_COLUMN.

    Parameters
    ----------
    input_paths : list[str] | str
        Single ZIP file path (or plain file path).

    Returns
    -------
    list[str]
        All extracted files + paths to all written split output files.
    """
    if isinstance(input_paths, str):
        input_paths = [input_paths]
    elif not isinstance(input_paths, list):
        input_paths = list(input_paths)

    if not input_paths:
        raise ValueError("input_paths is empty.")

    zip_path = input_paths[0]
    _out_dir = OUTPUT_DIR if OUTPUT_DIR else os.path.dirname(os.path.abspath(zip_path))
    os.makedirs(_out_dir, exist_ok=True)

    all_extracted: list = []

    # ── Scan base directory for additional ZIPs ───────────────────────────────
    _input_abs = {os.path.abspath(zip_path)}
    _base = str(_Path(zip_path).parent)
    try:
        for _fname in os.listdir(_base):
            if not _fname.lower().endswith(".zip"):
                continue
            _zip_full = os.path.join(_base, _fname)
            if os.path.abspath(_zip_full) in _input_abs:
                continue
            try:
                for _dest in _extract_zip_all(_zip_full, _out_dir).values():
                    all_extracted.append(_dest)
            except _zipfile.BadZipFile:
                pass
    except OSError:
        pass

    # ── Extract the primary input ZIP (or copy plain file) ───────────────────
    if _Path(zip_path).suffix.lower() == ".zip":
        name_map = _extract_zip_all(zip_path, _out_dir)
        all_extracted.extend(name_map.values())

        if INNER_FILE:
            if INNER_FILE.lower() not in name_map:
                raise ValueError(f"'{INNER_FILE}' not found inside ZIP: {zip_path}")
            file_path = name_map[INNER_FILE.lower()]
        else:
            file_path = next(
                (p for n, p in name_map.items() if _Path(n).suffix.lower() in _SUPPORTED),
                None,
            )
            if file_path is None:
                raise ValueError(f"No supported file found inside ZIP: {zip_path}")
    else:
        _dest = os.path.join(_out_dir, os.path.basename(zip_path))
        if os.path.abspath(zip_path) != os.path.abspath(_dest):
            with open(zip_path, "rb") as _s, open(_dest, "wb") as _d:
                _d.write(_s.read())
        all_extracted.append(_dest)
        file_path = _dest

    # ── Load and validate ─────────────────────────────────────────────────────
    df = _load_file(file_path)

    if SPLIT_COLUMN not in df.columns:
        raise KeyError(
            f"SPLIT_COLUMN '{SPLIT_COLUMN}' not found. "
            f"Available columns: {list(df.columns)}"
        )

    # ── Separate null rows ────────────────────────────────────────────────────
    null_mask = df[SPLIT_COLUMN].isna()
    null_df   = df[null_mask].copy()
    work_df   = df[~null_mask].copy()

    # ── Build normalised lookup for each group ────────────────────────────────
    group_value_sets: list[set] = []
    for group in GROUPS:
        raw_vals = group.get("values", [])
        group_value_sets.append({_normalise(str(v)) for v in raw_vals})

    # ── Assign each non-null row to the first matching group ──────────────────
    col_str = work_df[SPLIT_COLUMN].astype(str)
    col_normalised = col_str if CASE_SENSITIVE else col_str.str.lower()

    group_frames: dict[str, pd.DataFrame] = {
        str(g["label"]): pd.DataFrame(columns=work_df.columns)
        for g in GROUPS
    }
    assigned = pd.Series(False, index=work_df.index)

    for i, group in enumerate(GROUPS):
        label   = str(group["label"])
        val_set = group_value_sets[i]
        mask    = col_normalised.isin(val_set) & ~assigned
        group_frames[label] = work_df[mask].copy()
        assigned |= mask

    remaining_df = work_df[~assigned].copy()

    # ── Apply null handling ───────────────────────────────────────────────────
    if NULL_HANDLING == "separate_file":
        pass
    elif NULL_HANDLING.startswith("merge_into_group:"):
        target = NULL_HANDLING.split(":", 1)[1].strip()
        if target in group_frames:
            group_frames[target] = pd.concat(
                [group_frames[target], null_df], ignore_index=True
            )
        null_df = pd.DataFrame()
    elif NULL_HANDLING == "merge_into_remaining":
        remaining_df = pd.concat([remaining_df, null_df], ignore_index=True)
        null_df = pd.DataFrame()
    else:  # "ignore"
        null_df = pd.DataFrame()

    # ── Apply remaining handling ──────────────────────────────────────────────
    if REMAINING_HANDLING == "separate_file":
        pass
    elif REMAINING_HANDLING.startswith("merge_into_group:"):
        target = REMAINING_HANDLING.split(":", 1)[1].strip()
        if target in group_frames:
            group_frames[target] = pd.concat(
                [group_frames[target], remaining_df], ignore_index=True
            )
        remaining_df = pd.DataFrame()
    else:  # "ignore"
        remaining_df = pd.DataFrame()

    # ── Optionally drop the split column ─────────────────────────────────────
    def _maybe_drop_col(frame: pd.DataFrame) -> pd.DataFrame:
        if not INCLUDE_SPLIT_COLUMN and SPLIT_COLUMN in frame.columns:
            return frame.drop(columns=[SPLIT_COLUMN])
        return frame

    # ── Write outputs ─────────────────────────────────────────────────────────
    output_paths: list = []

    for group in GROUPS:
        label    = str(group["label"])
        filename = str(group.get("output_filename", f"{label}.csv"))
        frame    = _maybe_drop_col(group_frames.get(label, pd.DataFrame()))
        if not frame.empty:
            out_path = os.path.join(_out_dir, filename)
            output_paths.append(_write_output(frame, out_path, OUTPUT_FORMAT))

    if not null_df.empty and NULL_HANDLING == "separate_file" and NULL_FILENAME:
        out_path = os.path.join(_out_dir, NULL_FILENAME)
        output_paths.append(_write_output(_maybe_drop_col(null_df), out_path, OUTPUT_FORMAT))

    if not remaining_df.empty and REMAINING_HANDLING == "separate_file" and REMAINING_FILENAME:
        out_path = os.path.join(_out_dir, REMAINING_FILENAME)
        output_paths.append(_write_output(_maybe_drop_col(remaining_df), out_path, OUTPUT_FORMAT))

    return all_extracted + output_paths

# ── __main__ block is appended by the Gradio app at generation time ───────────
