"""
Generated by Data Preprocessing Script Library
Template : file_rank_filter  |  PS-16
Purpose  : Assign a row-level rank within each group (or globally if
           PARTITION_BY is empty), then optionally keep only the top-N
           ranked rows per group and route the rest to a separate file.

Contract : preprocess(input_path: str) -> str

Ranking behaviour
-----------------
PARTITION_BY     : Columns to group by before ranking.
                   Empty list [] → rank across the entire file (no grouping).
RANK_BY_COLUMN   : The column whose values determine the rank order.
RANK_ORDER       : 'asc'  → rank 1 = smallest value
                   'desc' → rank 1 = largest value
RANK_METHOD      : row_number  — unique sequential rank, ties broken by row position
                   rank        — tied rows share the same rank (min/standard competition)
                   dense_rank  — like rank but no gaps in rank sequence

Filtering behaviour
-------------------
KEEP_TOP_N = 1  → keep only the single best row per group
KEEP_TOP_N = 3  → keep top-3 rows per group
KEEP_TOP_N = 0  → keep ALL rows; just add the RANK_COLUMN_NAME column, no filtering

DISCARD_FILENAME
    Non-empty string → rows that don't make the cut are written to this file
    Empty string ""  → non-top-N rows are silently dropped (not written anywhere)
"""
from __future__ import annotations

import csv as _csv
import json as _json
import os
import tempfile as _tempfile
import zipfile as _zipfile
from pathlib import Path as _Path

import pandas as pd

# ── Configuration (substituted at generation time) ────────────────────────────
PARTITION_BY     = {{PARTITION_BY}}
RANK_BY_COLUMN   = "{{RANK_BY_COLUMN}}"
RANK_ORDER       = "{{RANK_ORDER}}"
RANK_METHOD      = "{{RANK_METHOD}}"
RANK_COLUMN_NAME = "{{RANK_COLUMN_NAME}}"
KEEP_TOP_N       = {{KEEP_TOP_N}}
DISCARD_FILENAME = "{{DISCARD_FILENAME}}"
OUTPUT_DIR       = "{{OUTPUT_DIR}}"
OUTPUT_FILENAME  = "{{OUTPUT_FILENAME}}"
OUTPUT_FORMAT    = "{{OUTPUT_FORMAT}}"
# ─────────────────────────────────────────────────────────────────────────────


# ── Embedded File Loader ──────────────────────────────────────────────────────
_ENCODINGS = ["utf-8", "cp1252", "latin-1"]


def _load_file(file_path: str) -> pd.DataFrame:
    ext = _Path(file_path).suffix.lower()
    if ext == ".zip":
        return _load_zip(file_path)
    if ext == ".xlsx":
        return pd.read_excel(file_path, engine="openpyxl")
    if ext == ".xls":
        return pd.read_excel(file_path, engine="xlrd")
    if ext == ".json":
        return _load_json(file_path)
    if ext == ".xml":
        return _load_xml(file_path)
    if ext in (".html", ".htm"):
        tables = pd.read_html(file_path)
        return tables[0] if tables else pd.DataFrame()
    return _load_delimited(file_path)


def _load_delimited(file_path: str) -> pd.DataFrame:
    for enc in _ENCODINGS:
        try:
            with open(file_path, "r", encoding=enc, errors="replace") as fh:
                sample = fh.read(8192)
            try:
                sep = _csv.Sniffer().sniff(sample).delimiter
            except _csv.Error:
                sep = ","
            return pd.read_csv(
                file_path, sep=sep, encoding=enc,
                on_bad_lines="skip", low_memory=False,
            )
        except Exception:
            continue
    raise ValueError(f"Cannot load delimited file: {file_path}")


def _load_json(file_path: str) -> pd.DataFrame:
    with open(file_path, "r", encoding="utf-8") as fh:
        data = _json.load(fh)
    return pd.json_normalize(data if isinstance(data, list) else [data])


def _load_xml(file_path: str) -> pd.DataFrame:
    try:
        import lxml.etree as _ET
        root = _ET.parse(file_path).getroot()
    except ImportError:
        import xml.etree.ElementTree as _ET  # type: ignore
        root = _ET.parse(file_path).getroot()
    records = [
        {el.tag: el.text for el in child.iter() if el.text and el.text.strip()}
        for child in root
    ]
    return pd.DataFrame(records)


def _load_zip(file_path: str) -> pd.DataFrame:
    _supported = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}
    with _zipfile.ZipFile(file_path, "r") as z:
        for name in z.namelist():
            if _Path(name).suffix.lower() in _supported:
                with _tempfile.TemporaryDirectory() as tmp_dir:
                    z.extract(name, tmp_dir)
                    return _load_file(os.path.join(tmp_dir, name))
    raise ValueError(f"No loadable file found inside ZIP: {file_path}")


def _write_output(df: pd.DataFrame, out_path: str, fmt: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _fmt = fmt.lower()
    if _fmt == "csv":
        df.to_csv(out_path, index=False)
    elif _fmt in ("xlsx", "excel"):
        df.to_excel(out_path, index=False, engine="openpyxl")
    elif _fmt == "json":
        df.to_json(out_path, orient="records", indent=2)
    elif _fmt == "parquet":
        df.to_parquet(out_path, index=False)
    elif _fmt == "tsv":
        df.to_csv(out_path, sep="\t", index=False)
    else:
        df.to_csv(out_path, index=False)
    return out_path


# ── Rank method → pandas rank() 'method' argument ────────────────────────────
_RANK_METHOD_MAP = {
    "row_number":  "first",    # unique sequential; ties broken by row order
    "rank":        "min",      # standard competition ranking; ties share lowest rank
    "dense_rank":  "dense",    # no gaps after ties
}

# ─────────────────────────────────────────────────────────────────────────────


def preprocess(input_path: str) -> list:
    """
    Rank rows within each group defined by PARTITION_BY, then optionally
    filter to the top KEEP_TOP_N rows per group.

    Parameters
    ----------
    input_path : str
        Path to the source file.

    Returns
    -------
    str
        Absolute path to the ranked (and optionally filtered) output file.
    """
    df = _load_file(input_path)

    # ── Validate columns ──────────────────────────────────────────────────────
    if RANK_BY_COLUMN not in df.columns:
        raise KeyError(
            f"RANK_BY_COLUMN '{RANK_BY_COLUMN}' not found in file: {input_path}"
        )
    missing_partition = [c for c in PARTITION_BY if c not in df.columns]
    if missing_partition:
        raise KeyError(
            f"PARTITION_BY columns {missing_partition} not found in file: {input_path}"
        )

    # ── Resolve rank method ───────────────────────────────────────────────────
    pandas_method = _RANK_METHOD_MAP.get(RANK_METHOD.lower())
    if pandas_method is None:
        raise ValueError(
            f"Unknown RANK_METHOD '{RANK_METHOD}'. "
            f"Supported: {list(_RANK_METHOD_MAP.keys())}"
        )

    ascending = RANK_ORDER.lower() == "asc"

    # ── Compute rank ──────────────────────────────────────────────────────────
    if PARTITION_BY:
        # Window rank: rank within each group
        df[RANK_COLUMN_NAME] = (
            df.groupby(PARTITION_BY)[RANK_BY_COLUMN]
            .rank(method=pandas_method, ascending=ascending, na_option="bottom")
            .astype(int)
        )
    else:
        # Global rank: no grouping
        df[RANK_COLUMN_NAME] = (
            df[RANK_BY_COLUMN]
            .rank(method=pandas_method, ascending=ascending, na_option="bottom")
            .astype(int)
        )

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # ── Filter by KEEP_TOP_N ──────────────────────────────────────────────────
    if KEEP_TOP_N and KEEP_TOP_N > 0:
        keep_mask    = df[RANK_COLUMN_NAME] <= KEEP_TOP_N
        top_df       = df[keep_mask].copy()
        discarded_df = df[~keep_mask].copy()

        # Write discarded rows if a filename is specified
        if DISCARD_FILENAME:
            _write_output(
                discarded_df,
                os.path.join(OUTPUT_DIR, DISCARD_FILENAME),
                OUTPUT_FORMAT,
            )

        out_df = top_df
    else:
        # KEEP_TOP_N == 0: keep all rows, just add rank column
        out_df = df

    _out_dir = OUTPUT_DIR if OUTPUT_DIR else os.path.dirname(os.path.abspath(input_path))
    out_path = os.path.join(_out_dir, OUTPUT_FILENAME)
    return [_write_output(out_df, out_path, OUTPUT_FORMAT)]
