"""
Generated by Data Preprocessing Script Library
Template : file_denormalize  |  PS-06
Purpose  : Flatten a normalised master-detail relationship into a single wide file.
           input_paths[0] = master file  (e.g. customers)
           input_paths[1] = detail file  (e.g. invoices)
           All detail columns (except JOIN_KEY) are prefixed with DETAIL_PREFIX.
Contract : preprocess(input_paths: list) -> list
"""
from __future__ import annotations

import csv as _csv
import json as _json
import os
import tempfile as _tempfile
import zipfile as _zipfile
from pathlib import Path as _Path

import pandas as pd

# ── Configuration (substituted at generation time) ────────────────────────────
HEADER_FILENAME      = "{{HEADER_FILENAME}}"      # file name for the header (master) file
DETAIL_FILENAME      = "{{DETAIL_FILENAME}}"      # file name for the detail file
LEFT_USECOLS         = {{LEFT_USECOLS}}            # columns to load from HEADER file; [] = all
RIGHT_USECOLS        = {{RIGHT_USECOLS}}           # columns to load from DETAIL file; [] = all
LEFT_INNER_FILE      = "{{LEFT_INNER_FILE}}"       # when HEADER is a ZIP, extract this inner file; "" = first file
RIGHT_INNER_FILE     = "{{RIGHT_INNER_FILE}}"      # when DETAIL is a ZIP, extract this inner file; "" = first file
DEDUP_RIGHT_BY       = "{{DEDUP_RIGHT_BY}}"        # dedup DETAIL file on this column before join; "" = skip
DEDUP_KEEP           = "{{DEDUP_KEEP}}"            # "first" | "last"
JOIN_KEY             = "{{JOIN_KEY}}"
LEFT_KEY             = "{{LEFT_KEY}}"              # override: join key in HEADER file; "" = use JOIN_KEY
RIGHT_KEY            = "{{RIGHT_KEY}}"             # override: join key in DETAIL file; "" = use JOIN_KEY
JOIN_TYPE            = "{{JOIN_TYPE}}"
LEFT_SUFFIX          = "{{LEFT_SUFFIX}}"
RIGHT_SUFFIX         = "{{RIGHT_SUFFIX}}"
DETAIL_PREFIX        = "{{DETAIL_PREFIX}}"
OUTPUT_DROP_COLUMNS  = {{OUTPUT_DROP_COLUMNS}}     # columns to drop from result; [] = keep all
INSERT_COLUMN        = "{{INSERT_COLUMN}}"         # move this column after INSERT_AFTER_COLUMN; "" = skip
INSERT_AFTER_COLUMN  = "{{INSERT_AFTER_COLUMN}}"
OUTPUT_DIR           = "{{OUTPUT_DIR}}"
OUTPUT_FILENAME      = "{{OUTPUT_FILENAME}}"
OUTPUT_FORMAT        = "{{OUTPUT_FORMAT}}"
# ─────────────────────────────────────────────────────────────────────────────


# ── Embedded File Loader ──────────────────────────────────────────────────────
_ENCODINGS = ["utf-8", "cp1252", "latin-1"]


def _load_file(file_path: str, inner_name: str = "") -> pd.DataFrame:
    ext = _Path(file_path).suffix.lower()
    if ext == ".zip":
        return _load_zip(file_path, inner_name)
    if ext == ".xlsx":
        return pd.read_excel(file_path, engine="openpyxl")
    if ext == ".xls":
        return pd.read_excel(file_path, engine="xlrd")
    if ext == ".json":
        return _load_json(file_path)
    if ext == ".xml":
        return _load_xml(file_path)
    if ext in (".html", ".htm"):
        tables = pd.read_html(file_path)
        return tables[0] if tables else pd.DataFrame()
    return _load_delimited(file_path)


def _load_delimited(file_path: str) -> pd.DataFrame:
    for enc in _ENCODINGS:
        try:
            with open(file_path, "r", encoding=enc, errors="replace") as fh:
                sample = fh.read(8192)
            try:
                sep = _csv.Sniffer().sniff(sample).delimiter
            except _csv.Error:
                sep = ","
            return pd.read_csv(
                file_path, sep=sep, encoding=enc,
                on_bad_lines="skip", low_memory=False,
            )
        except Exception:
            continue
    raise ValueError(f"Cannot load delimited file: {file_path}")


def _load_json(file_path: str) -> pd.DataFrame:
    with open(file_path, "r", encoding="utf-8") as fh:
        data = _json.load(fh)
    return pd.json_normalize(data if isinstance(data, list) else [data])


def _load_xml(file_path: str) -> pd.DataFrame:
    try:
        import lxml.etree as _ET
        root = _ET.parse(file_path).getroot()
    except ImportError:
        import xml.etree.ElementTree as _ET  # type: ignore
        root = _ET.parse(file_path).getroot()
    records = [
        {el.tag: el.text for el in child.iter() if el.text and el.text.strip()}
        for child in root
    ]
    return pd.DataFrame(records)


def _load_zip(file_path: str, inner_name: str = "") -> pd.DataFrame:
    _supported = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}
    with _zipfile.ZipFile(file_path, "r") as z:
        names = z.namelist()
        if inner_name:
            for name in names:
                if os.path.basename(name).lower() == inner_name.lower():
                    with _tempfile.TemporaryDirectory() as tmp_dir:
                        extracted = z.extract(name, tmp_dir)
                        return _load_file(extracted)
            raise ValueError(f"'{inner_name}' not found inside ZIP: {file_path}")
        for name in names:
            if _Path(name).suffix.lower() in _supported:
                with _tempfile.TemporaryDirectory() as tmp_dir:
                    extracted = z.extract(name, tmp_dir)
                    return _load_file(extracted)
    raise ValueError(f"No loadable file found inside ZIP: {file_path}")


def _write_output(df: pd.DataFrame, out_path: str, fmt: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _fmt = fmt.lower()
    if _fmt == "csv":
        df.to_csv(out_path, index=False)
    elif _fmt in ("xlsx", "excel"):
        df.to_excel(out_path, index=False, engine="openpyxl")
    elif _fmt == "json":
        df.to_json(out_path, orient="records", indent=2)
    elif _fmt == "parquet":
        df.to_parquet(out_path, index=False)
    elif _fmt == "tsv":
        df.to_csv(out_path, sep="\t", index=False)
    else:
        df.to_csv(out_path, index=False)
    return out_path

# ─────────────────────────────────────────────────────────────────────────────


def _find_input_file(input_paths: list, filename: str, fallback_idx: int = 0) -> str:
    """Return the path in *input_paths* whose basename matches *filename*.
    Falls back to input_paths[fallback_idx] if no match is found."""
    for p in input_paths:
        if _Path(p).name == filename:
            return p
    return input_paths[fallback_idx]


def _apply_usecols(df: pd.DataFrame, usecols: list) -> pd.DataFrame:
    if usecols:
        keep = [c for c in usecols if c in df.columns]
        return df[keep]
    return df


def _drop_columns(df: pd.DataFrame, cols: list) -> pd.DataFrame:
    if cols:
        to_drop = [c for c in cols if c in df.columns]
        return df.drop(columns=to_drop)
    return df


def _insert_column_after(df: pd.DataFrame, col: str, after: str) -> pd.DataFrame:
    if not col or col not in df.columns or not after or after not in df.columns:
        return df
    cols = list(df.columns)
    cols.remove(col)
    idx = cols.index(after)
    cols.insert(idx + 1, col)
    return df[cols]


def _extract_from_zips(
    left_path: str,
    right_path: str,
    left_inner: str,
    right_inner: str,
    out_dir: str,
) -> tuple:
    """
    Extract ALL files from ZIP inputs to *out_dir* (persistent).
    If both paths point to the same ZIP, opens it only once.
    Non-ZIP inputs are copied to *out_dir* so every input file is present there.
    Returns (left_file_path, right_file_path, list_of_all_extracted_paths).
    """
    os.makedirs(out_dir, exist_ok=True)
    _supported = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}
    left_is_zip  = _Path(left_path).suffix.lower()  == ".zip"
    right_is_zip = _Path(right_path).suffix.lower() == ".zip"
    same_zip     = (
        left_is_zip and right_is_zip
        and os.path.abspath(left_path) == os.path.abspath(right_path)
    )
    all_extracted: list = []

    def _extract_zip_all(zip_path: str) -> dict:
        """Extract every file in the ZIP to out_dir; return {lower_name: dest_path}."""
        name_map: dict = {}
        with _zipfile.ZipFile(zip_path, "r") as zf:
            for member in zf.namelist():
                fname = os.path.basename(member)
                if not fname:
                    continue
                dest = os.path.join(out_dir, fname)
                with zf.open(member) as src, open(dest, "wb") as dst:
                    dst.write(src.read())
                all_extracted.append(dest)
                name_map[fname.lower()] = dest
        return name_map

    def _pick(name_map: dict, inner: str, zip_path: str) -> str:
        """Return path for *inner* from the extraction map, or first supported file."""
        if inner:
            if inner.lower() in name_map:
                return name_map[inner.lower()]
            raise ValueError(f"'{inner}' not found inside ZIP: {zip_path}")
        for name, path in name_map.items():
            if _Path(name).suffix.lower() in _supported:
                return path
        raise ValueError(f"No supported file found inside ZIP: {zip_path}")

    if same_zip:
        name_map = _extract_zip_all(left_path)
        lf = _pick(name_map, left_inner, left_path)
        rf = _pick(name_map, right_inner, right_path)
    else:
        if left_is_zip:
            lf = _pick(_extract_zip_all(left_path), left_inner, left_path)
        else:
            _dest = os.path.join(out_dir, os.path.basename(left_path))
            if os.path.abspath(left_path) != os.path.abspath(_dest):
                with open(left_path, "rb") as _s, open(_dest, "wb") as _d:
                    _d.write(_s.read())
            all_extracted.append(_dest)
            lf = _dest
        if right_is_zip:
            rf = _pick(_extract_zip_all(right_path), right_inner, right_path)
        else:
            _dest = os.path.join(out_dir, os.path.basename(right_path))
            if os.path.abspath(right_path) != os.path.abspath(_dest):
                with open(right_path, "rb") as _s, open(_dest, "wb") as _d:
                    _d.write(_s.read())
            all_extracted.append(_dest)
            rf = _dest

    return lf, rf, all_extracted


def preprocess(input_paths: list) -> list:
    """
    Flatten HEADER_FILENAME (master) + DETAIL_FILENAME (detail) into one wide file.
    All detail columns (except JOIN_KEY) are prefixed with DETAIL_PREFIX so
    they can be distinguished from master columns in the output.

    Parameters
    ----------
    input_paths : list[str]
        Must contain the two files whose names match HEADER_FILENAME and
        DETAIL_FILENAME. Order does not matter — files are found by name.

    Returns
    -------
    list[str]
        Extracted input files + flat output file path.
    """
    if isinstance(input_paths, str):
        input_paths = [input_paths, input_paths]
    elif isinstance(input_paths, list) and len(input_paths) == 1:
        input_paths = [input_paths[0], input_paths[0]]

    if len(input_paths) < 2:
        raise ValueError(
            "file_denormalize requires exactly 2 input files: [header/master, detail]."
        )

    header_path = _find_input_file(input_paths, HEADER_FILENAME, 0)
    detail_path = _find_input_file(input_paths, DETAIL_FILENAME, 1)
    _out_dir = OUTPUT_DIR if OUTPUT_DIR else os.path.dirname(os.path.abspath(input_paths[0]))
    header_file, detail_file, extracted_paths = _extract_from_zips(
        header_path, detail_path, LEFT_INNER_FILE, RIGHT_INNER_FILE, _out_dir
    )
    master = _apply_usecols(_load_file(header_file), LEFT_USECOLS)
    detail = _apply_usecols(_load_file(detail_file), RIGHT_USECOLS)

    # Resolve effective join key (LEFT_KEY/RIGHT_KEY override JOIN_KEY for mismatched names)
    left_key  = LEFT_KEY  if LEFT_KEY  else JOIN_KEY
    right_key = RIGHT_KEY if RIGHT_KEY else JOIN_KEY

    if left_key not in master.columns:
        raise KeyError(f"Join key '{left_key}' not found in header file: {HEADER_FILENAME}")
    if right_key not in detail.columns:
        raise KeyError(f"Join key '{right_key}' not found in detail file: {DETAIL_FILENAME}")

    if DEDUP_RIGHT_BY and DEDUP_RIGHT_BY in detail.columns:
        detail = detail.drop_duplicates(subset=DEDUP_RIGHT_BY, keep=DEDUP_KEEP or "first")

    # Prefix all detail columns except the (right) join key
    detail = detail.rename(columns={
        col: f"{DETAIL_PREFIX}{col}"
        for col in detail.columns
        if col != right_key
    })
    prefixed_right_key = right_key  # unchanged after rename (join key not prefixed)

    if left_key == prefixed_right_key:
        result = master.merge(
            detail,
            on=left_key,
            how=JOIN_TYPE,
            suffixes=(LEFT_SUFFIX, RIGHT_SUFFIX),
        )
    else:
        result = master.merge(
            detail,
            left_on=left_key,
            right_on=prefixed_right_key,
            how=JOIN_TYPE,
            suffixes=(LEFT_SUFFIX, RIGHT_SUFFIX),
        )
        if prefixed_right_key in result.columns and prefixed_right_key != left_key:
            result = result.drop(columns=[prefixed_right_key])

    result = _drop_columns(result, OUTPUT_DROP_COLUMNS)
    result = _insert_column_after(result, INSERT_COLUMN, INSERT_AFTER_COLUMN)

    out_path = os.path.join(_out_dir, OUTPUT_FILENAME)
    return extracted_paths + [_write_output(result, out_path, OUTPUT_FORMAT)]
