"""
Generated by Data Preprocessing Script Library
Template : file_handle_nulls  |  PS-12
Purpose  : Detect and handle missing/null values per column.
           Produces a cleaned output file and a null audit report.
Contract : preprocess(input_path: str) -> str

NULL_RULES format (Python list literal injected at generation time):
    [
        {"column": "Invoice_Amount", "strategy": "fill", "fill_value": "0"},
        {"column": "Status",         "strategy": "mode"},
        {"column": "*",              "strategy": "drop_row"},
    ]
    column = "*" applies the strategy to ALL columns.

Supported strategies:
    fill          — fill with rule['fill_value']
    mean          — fill with column mean   (numeric columns only)
    median        — fill with column median (numeric columns only)
    mode          — fill with column mode   (first mode value)
    forward_fill  — propagate previous non-null value downward
    backward_fill — propagate next non-null value upward
    drop_row      — drop any row where this column is null
"""
from __future__ import annotations

import csv as _csv
import json as _json
import os
import tempfile as _tempfile
import zipfile as _zipfile
from pathlib import Path as _Path

import pandas as pd

# ── Configuration (substituted at generation time) ────────────────────────────
NULL_RULES           = {{NULL_RULES}}
NULL_VALUES          = {{NULL_VALUES}}
OUTPUT_DIR           = "{{OUTPUT_DIR}}"
OUTPUT_FILENAME      = "{{OUTPUT_FILENAME}}"
NULL_REPORT_FILENAME = "{{NULL_REPORT_FILENAME}}"
OUTPUT_FORMAT        = "{{OUTPUT_FORMAT}}"
# ─────────────────────────────────────────────────────────────────────────────


# ── Embedded File Loader ──────────────────────────────────────────────────────
_ENCODINGS = ["utf-8", "cp1252", "latin-1"]


def _load_file(file_path: str) -> pd.DataFrame:
    ext = _Path(file_path).suffix.lower()
    if ext == ".zip":
        return _load_zip(file_path)
    if ext == ".xlsx":
        return pd.read_excel(file_path, engine="openpyxl")
    if ext == ".xls":
        return pd.read_excel(file_path, engine="xlrd")
    if ext == ".json":
        return _load_json(file_path)
    if ext == ".xml":
        return _load_xml(file_path)
    if ext in (".html", ".htm"):
        tables = pd.read_html(file_path)
        return tables[0] if tables else pd.DataFrame()
    return _load_delimited(file_path)


def _load_delimited(file_path: str) -> pd.DataFrame:
    for enc in _ENCODINGS:
        try:
            with open(file_path, "r", encoding=enc, errors="replace") as fh:
                sample = fh.read(8192)
            try:
                sep = _csv.Sniffer().sniff(sample).delimiter
            except _csv.Error:
                sep = ","
            return pd.read_csv(
                file_path, sep=sep, encoding=enc,
                on_bad_lines="skip", low_memory=False,
            )
        except Exception:
            continue
    raise ValueError(f"Cannot load delimited file: {file_path}")


def _load_json(file_path: str) -> pd.DataFrame:
    with open(file_path, "r", encoding="utf-8") as fh:
        data = _json.load(fh)
    return pd.json_normalize(data if isinstance(data, list) else [data])


def _load_xml(file_path: str) -> pd.DataFrame:
    try:
        import lxml.etree as _ET
        root = _ET.parse(file_path).getroot()
    except ImportError:
        import xml.etree.ElementTree as _ET  # type: ignore
        root = _ET.parse(file_path).getroot()
    records = [
        {el.tag: el.text for el in child.iter() if el.text and el.text.strip()}
        for child in root
    ]
    return pd.DataFrame(records)


def _load_zip(file_path: str) -> pd.DataFrame:
    _supported = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}
    with _tempfile.TemporaryDirectory() as tmp_dir:
        with _zipfile.ZipFile(file_path, "r") as z:
            names = [n for n in z.namelist() if _Path(n).suffix.lower() in _supported]
            for name in names:
                z.extract(name, tmp_dir)
        if names:
            return _load_file(os.path.join(tmp_dir, names[0]))
    raise ValueError(f"No loadable file found inside ZIP: {file_path}")


def _write_output(df: pd.DataFrame, out_path: str, fmt: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _fmt = fmt.lower()
    if _fmt == "csv":
        df.to_csv(out_path, index=False)
    elif _fmt in ("xlsx", "excel"):
        df.to_excel(out_path, index=False, engine="openpyxl")
    elif _fmt == "json":
        df.to_json(out_path, orient="records", indent=2)
    elif _fmt == "parquet":
        df.to_parquet(out_path, index=False)
    elif _fmt == "tsv":
        df.to_csv(out_path, sep="\t", index=False)
    else:
        df.to_csv(out_path, index=False)
    return out_path


def _apply_null_strategy(df: pd.DataFrame, col: str, rule: dict) -> pd.DataFrame:
    strategy   = rule.get("strategy", "")
    fill_value = rule.get("fill_value", "")

    if strategy == "fill":
        df[col] = df[col].fillna(fill_value)
    elif strategy == "mean":
        numeric = pd.to_numeric(df[col], errors="coerce")
        df[col] = df[col].fillna(numeric.mean())
    elif strategy == "median":
        numeric = pd.to_numeric(df[col], errors="coerce")
        df[col] = df[col].fillna(numeric.median())
    elif strategy == "mode":
        modes = df[col].mode()
        if not modes.empty:
            df[col] = df[col].fillna(modes.iloc[0])
    elif strategy == "forward_fill":
        df[col] = df[col].ffill()
    elif strategy == "backward_fill":
        df[col] = df[col].bfill()
    elif strategy == "drop_row":
        df = df.dropna(subset=[col]).reset_index(drop=True)
    else:
        raise ValueError(
            f"Unknown null strategy '{strategy}'. Supported: fill, mean, median, "
            "mode, forward_fill, backward_fill, drop_row"
        )
    return df

# ─────────────────────────────────────────────────────────────────────────────


def preprocess(input_path: str) -> str:
    """
    Load *input_path*, replace NULL_VALUES string representations with pd.NA,
    write a null audit report, apply NULL_RULES, and write cleaned data.

    Parameters
    ----------
    input_path : str
        Path to the source file.

    Returns
    -------
    list
        Absolute path to the cleaned output file.
    """
    df = _load_file(input_path)

    # Normalise null representations
    if NULL_VALUES:
        df = df.replace(NULL_VALUES, pd.NA)

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Build and write null audit (before cleaning)
    null_counts = df.isnull().sum()
    audit_rows = []
    total_rows = len(df)
    for col, cnt in null_counts.items():
        if cnt > 0:
            audit_rows.append({
                "Column":     col,
                "Null_Count": cnt,
                "Total_Rows": total_rows,
                "Null_Pct":   round(cnt / total_rows * 100, 2) if total_rows else 0,
            })
    audit_df = pd.DataFrame(audit_rows)
    _write_output(audit_df, os.path.join(OUTPUT_DIR, NULL_REPORT_FILENAME), OUTPUT_FORMAT)

    # Apply null-handling rules in order
    for rule in NULL_RULES:
        col = rule.get("column", "")
        if col == "*":
            for c in list(df.columns):
                df = _apply_null_strategy(df, c, rule)
        elif col in df.columns:
            df = _apply_null_strategy(df, col, rule)

    _out_dir = OUTPUT_DIR if OUTPUT_DIR else os.path.dirname(os.path.abspath(input_path))
    out_path = os.path.join(_out_dir, OUTPUT_FILENAME)
    return [_write_output(df, out_path, OUTPUT_FORMAT)]
