"""
Generated by Data Preprocessing Script Library
Template : file_union_zip  |  PS-02Z
Purpose  : Extract a named inner file from each ZIP, vertically stack them (union).
           All ZIP contents are extracted to out_dir.
           Base directories of every input ZIP are scanned for additional ZIPs
           and those are extracted too.
Contract : preprocess(input_paths: list) -> list
"""
from __future__ import annotations

import csv as _csv
import json as _json
import os
import shutil as _shutil
import tempfile as _tempfile
import zipfile as _zipfile
from pathlib import Path as _Path

import pandas as pd

# ── Configuration (substituted at generation time) ────────────────────────────
INNER_FILE        = "{{INNER_FILE}}"        # filename to union from each ZIP; "" = first supported file
OUTPUT_DIR        = "{{OUTPUT_DIR}}"
OUTPUT_FILENAME   = "{{OUTPUT_FILENAME}}"
OUTPUT_FORMAT     = "{{OUTPUT_FORMAT}}"
ADD_SOURCE_TAG    = {{ADD_SOURCE_TAG}}
SOURCE_TAG_COLUMN = "{{SOURCE_TAG_COLUMN}}"
# ─────────────────────────────────────────────────────────────────────────────

_ENCODINGS  = ["utf-8", "cp1252", "latin-1"]
_SUPPORTED  = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}


# ── File loaders ──────────────────────────────────────────────────────────────

def _load_file(file_path: str) -> pd.DataFrame:
    ext = _Path(file_path).suffix.lower()
    if ext == ".xlsx":
        return pd.read_excel(file_path, engine="openpyxl")
    if ext == ".xls":
        return pd.read_excel(file_path, engine="xlrd")
    if ext == ".json":
        with open(file_path, "r", encoding="utf-8") as fh:
            data = _json.load(fh)
        return pd.json_normalize(data if isinstance(data, list) else [data])
    if ext == ".xml":
        try:
            import lxml.etree as _ET
            root = _ET.parse(file_path).getroot()
        except ImportError:
            import xml.etree.ElementTree as _ET  # type: ignore
            root = _ET.parse(file_path).getroot()
        records = [
            {el.tag: el.text for el in child.iter() if el.text and el.text.strip()}
            for child in root
        ]
        return pd.DataFrame(records)
    return _load_delimited(file_path)


def _load_delimited(file_path: str) -> pd.DataFrame:
    for enc in _ENCODINGS:
        try:
            with open(file_path, "r", encoding=enc, errors="replace") as fh:
                sample = fh.read(8192)
            try:
                sep = _csv.Sniffer().sniff(sample).delimiter
            except _csv.Error:
                sep = ","
            return pd.read_csv(file_path, sep=sep, encoding=enc,
                               on_bad_lines="skip", low_memory=False)
        except Exception:
            continue
    raise ValueError(f"Cannot load delimited file: {file_path}")


def _write_output(df: pd.DataFrame, out_path: str, fmt: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _fmt = fmt.lower()
    if _fmt == "csv":
        df.to_csv(out_path, index=False)
    elif _fmt in ("xlsx", "excel"):
        df.to_excel(out_path, index=False, engine="openpyxl")
    elif _fmt == "json":
        df.to_json(out_path, orient="records", indent=2)
    elif _fmt == "parquet":
        df.to_parquet(out_path, index=False)
    elif _fmt == "tsv":
        df.to_csv(out_path, sep="\t", index=False)
    else:
        df.to_csv(out_path, index=False)
    return out_path


# ── ZIP extraction helpers ─────────────────────────────────────────────────────

def _extract_zip_all(zip_path: str, out_dir: str) -> dict:
    """Extract every file from zip_path into out_dir. Returns {lower_name: dest_path}."""
    extracted = {}
    with _zipfile.ZipFile(zip_path, "r") as z:
        for name in z.namelist():
            if name.endswith("/"):
                continue
            dest = os.path.join(out_dir, os.path.basename(name))
            with z.open(name) as src, open(dest, "wb") as dst:
                _shutil.copyfileobj(src, dst)
            extracted[os.path.basename(name).lower()] = dest
    return extracted


def _resolve_and_extract(input_paths: list, out_dir: str):
    """
    For every path in input_paths:
      - If it is a ZIP → extract all its contents to out_dir; remember which
        inner file to use for the union (INNER_FILE or first supported).
      - If it is a plain file → copy to out_dir (avoid self-overwrite).
    Also scan the base directory of every input path for extra ZIPs and extract them.

    Returns:
        all_extracted  : list of all extracted/copied file paths
        union_sources  : list of (file_path, source_label) tuples to be unioned
    """
    os.makedirs(out_dir, exist_ok=True)
    all_extracted: list[str] = []
    union_sources: list[tuple] = []
    scanned_dirs: set = set()
    scanned_zips: set = set()

    for raw_path in input_paths:
        p = raw_path.strip()
        if not p:
            continue

        base_dir = os.path.dirname(os.path.abspath(p))

        # ── Scan base directory for additional ZIPs ────────────────────────
        if base_dir not in scanned_dirs:
            scanned_dirs.add(base_dir)
            for entry in os.scandir(base_dir):
                if entry.name.lower().endswith(".zip") and entry.path not in scanned_zips:
                    if os.path.abspath(entry.path) != os.path.abspath(p):
                        scanned_zips.add(entry.path)
                        extras = _extract_zip_all(entry.path, out_dir)
                        all_extracted.extend(extras.values())

        if _Path(p).suffix.lower() == ".zip":
            scanned_zips.add(os.path.abspath(p))
            extracted = _extract_zip_all(p, out_dir)
            all_extracted.extend(extracted.values())

            # Pick the inner file to union
            if INNER_FILE:
                inner_path = extracted.get(INNER_FILE.lower())
                if inner_path is None:
                    # try case-insensitive match already done; try original name
                    raise ValueError(
                        f"'{INNER_FILE}' not found inside ZIP: {p}. "
                        f"Available: {list(extracted.keys())}"
                    )
            else:
                # first supported file by extension
                inner_path = next(
                    (v for k, v in extracted.items() if _Path(k).suffix.lower() in _SUPPORTED),
                    None,
                )
                if inner_path is None:
                    raise ValueError(f"No supported data file found inside ZIP: {p}")

            union_sources.append((inner_path, os.path.basename(p)))
        else:
            # Plain file — copy to out_dir
            dest = os.path.join(out_dir, os.path.basename(p))
            if os.path.abspath(p) != os.path.abspath(dest):
                _shutil.copy2(p, dest)
            all_extracted.append(dest)
            if _Path(p).suffix.lower() in _SUPPORTED:
                union_sources.append((dest, os.path.basename(p)))

    return all_extracted, union_sources


# ─────────────────────────────────────────────────────────────────────────────

def preprocess(input_paths: list) -> list:
    """
    Extract INNER_FILE from each ZIP in input_paths, union them vertically,
    write the merged result; also extract all other ZIP contents to out_dir.

    Parameters
    ----------
    input_paths : list[str]
        Paths to ZIP files (or plain data files) to union.

    Returns
    -------
    list[str]
        All extracted file paths  +  the merged union output path (last element).
    """
    if isinstance(input_paths, str):
        input_paths = [p.strip() for p in input_paths.split(",") if p.strip()]
    if not input_paths:
        raise ValueError("file_union_zip requires at least one input file.")

    out_dir = OUTPUT_DIR if OUTPUT_DIR else os.path.dirname(os.path.abspath(input_paths[0]))
    os.makedirs(out_dir, exist_ok=True)

    all_extracted, union_sources = _resolve_and_extract(input_paths, out_dir)

    if not union_sources:
        raise ValueError("No data files found to union.")

    frames = []
    for file_path, source_label in union_sources:
        df = _load_file(file_path)
        if ADD_SOURCE_TAG and SOURCE_TAG_COLUMN:
            df[SOURCE_TAG_COLUMN] = source_label
        frames.append(df)

    merged = pd.concat(frames, ignore_index=True, sort=False)

    out_path = os.path.join(out_dir, OUTPUT_FILENAME)
    _write_output(merged, out_path, OUTPUT_FORMAT)

    return all_extracted + [out_path]


if __name__ == "__main__":
    import sys
    _paths = sys.argv[1:] if len(sys.argv) > 1 else []
    result = preprocess(_paths)
    for r in result:
        print(r)
