"""
Generated by Data Preprocessing Script Library
Template : file_zip_extract_join
Purpose  : Extract two named files from a ZIP, optionally pre-process both
           files (column select + dedup), join them on a key column,
           optionally drop unwanted output columns, optionally reorder a
           result column, and write the merged output.
           All other files in the ZIP (excluding SKIP_EXTENSIONS) are
           extracted to the output directory when EXTRACT_OTHER_FILES=True.
Contract : preprocess(input_paths: list) -> list
           input_paths[0] = path to the ZIP file

Parameter guide
---------------
LEFT_FILE_IN_ZIP     : filename of the primary (left) file inside the ZIP
RIGHT_FILE_IN_ZIP    : filename of the secondary (right) file inside the ZIP
SKIP_EXTENSIONS      : file extensions to ignore inside the ZIP, e.g. [".sql", ".rtf"]
EXTRACT_OTHER_FILES  : True  → extract every other file in the ZIP to the output dir
                       False → ignore all files except LEFT_FILE_IN_ZIP and RIGHT_FILE_IN_ZIP

LEFT_USECOLS         : columns to load from the LEFT file; [] = load all columns
RIGHT_USECOLS        : columns to load from the RIGHT file; [] = load all columns

DEDUP_RIGHT_BY       : column to deduplicate the RIGHT file on before joining; "" = skip
DEDUP_KEEP           : which occurrence to keep — "first" or "last"

JOIN_KEY             : shared column name used when both files have the same join column name
LEFT_KEY             : join column name in the LEFT file; "" = use JOIN_KEY
RIGHT_KEY            : join column name in the RIGHT file; "" = use JOIN_KEY
JOIN_TYPE            : "left" | "inner" | "right" | "outer"
LEFT_SUFFIX          : suffix appended to overlapping LEFT columns after merge, e.g. "_left"
RIGHT_SUFFIX         : suffix appended to overlapping RIGHT columns after merge, e.g. "_right"

OUTPUT_DROP_COLUMNS  : columns to drop from the merged result before writing; [] = keep all
INSERT_COLUMN        : after the join, move this column immediately after INSERT_AFTER_COLUMN;
                       "" = skip column reordering
INSERT_AFTER_COLUMN  : anchor column for INSERT_COLUMN repositioning

OUTPUT_FILENAME      : filename for the merged output file
OUTPUT_DIR           : directory to write all output files;
                       "" = same directory as the input ZIP file
"""
from __future__ import annotations

import csv as _csv
import os
import shutil as _shutil
import tempfile as _tempfile
import zipfile as _zipfile

import pandas as _pd

# ── Configuration (substituted at generation time) ────────────────────────────
LEFT_FILE_IN_ZIP    = "{{LEFT_FILE_IN_ZIP}}"
RIGHT_FILE_IN_ZIP   = "{{RIGHT_FILE_IN_ZIP}}"
SKIP_EXTENSIONS     = {{SKIP_EXTENSIONS}}
EXTRACT_OTHER_FILES = {{EXTRACT_OTHER_FILES}}

LEFT_USECOLS        = {{LEFT_USECOLS}}
RIGHT_USECOLS       = {{RIGHT_USECOLS}}

DEDUP_RIGHT_BY      = "{{DEDUP_RIGHT_BY}}"
DEDUP_KEEP          = "{{DEDUP_KEEP}}"

JOIN_KEY            = "{{JOIN_KEY}}"
LEFT_KEY            = "{{LEFT_KEY}}"
RIGHT_KEY           = "{{RIGHT_KEY}}"
JOIN_TYPE           = "{{JOIN_TYPE}}"
LEFT_SUFFIX         = "{{LEFT_SUFFIX}}"
RIGHT_SUFFIX        = "{{RIGHT_SUFFIX}}"

OUTPUT_DROP_COLUMNS = {{OUTPUT_DROP_COLUMNS}}
INSERT_COLUMN       = "{{INSERT_COLUMN}}"
INSERT_AFTER_COLUMN = "{{INSERT_AFTER_COLUMN}}"

OUTPUT_FILENAME     = "{{OUTPUT_FILENAME}}"
OUTPUT_DIR          = "{{OUTPUT_DIR}}"
# ─────────────────────────────────────────────────────────────────────────────


# ── Embedded file reader (delimited text with encoding fallback) ──────────────

_ENCODINGS = ["utf-8", "cp1252", "latin-1"]


def _read_delimited(path: str, usecols: list | None = None) -> _pd.DataFrame:
    for enc in _ENCODINGS:
        try:
            with open(path, "r", encoding=enc, errors="replace", newline="") as fh:
                sample = fh.read(8192)
            try:
                sep = _csv.Sniffer().sniff(sample, delimiters=",|\t;").delimiter
            except _csv.Error:
                sep = ","
            kwargs: dict = dict(
                sep=sep,
                dtype=str,
                encoding=enc,
                on_bad_lines="skip",
                low_memory=False,
            )
            if usecols:
                kwargs["usecols"] = usecols
            return _pd.read_csv(path, **kwargs)
        except Exception:
            continue
    raise ValueError(f"Could not read file: {path}")

# ─────────────────────────────────────────────────────────────────────────────


def preprocess(input_paths: list) -> list:
    """
    Extract LEFT_FILE_IN_ZIP and RIGHT_FILE_IN_ZIP from the ZIP at
    input_paths[0], join them, apply optional post-join transforms, and
    write the merged result.

    Parameters
    ----------
    input_paths : list[str]
        input_paths[0] must be the path to the ZIP file.

    Returns
    -------
    list[str]
        Paths to all files written to the output directory:
        - the right file extracted from the ZIP (passed through as-is)
        - any other extracted passthrough files (when EXTRACT_OTHER_FILES=True)
        - the merged output file (always last)
    """
    if isinstance(input_paths, str):
        input_paths = [input_paths]

    zip_path = input_paths[0]
    if not zip_path.lower().endswith(".zip"):
        raise ValueError(f"Expected a ZIP file, got: {zip_path}")

    target_dir = OUTPUT_DIR if OUTPUT_DIR else (os.path.dirname(os.path.abspath(zip_path)))
    os.makedirs(target_dir, exist_ok=True)

    temp_dir = _tempfile.mkdtemp()
    left_path  = None
    right_path = None
    output_paths: list[str] = []

    _skip_exts = {e.lower() for e in SKIP_EXTENSIONS} if SKIP_EXTENSIONS else set()

    try:
        with _zipfile.ZipFile(zip_path, "r") as zf:
            for member in zf.namelist():
                filename = os.path.basename(member)
                if not filename:
                    continue

                ext = os.path.splitext(filename)[1].lower()
                if ext in _skip_exts:
                    continue

                lower_name = filename.lower()

                # Left file → temp dir (used only for reading, not passed through)
                if lower_name == LEFT_FILE_IN_ZIP.lower():
                    left_path = os.path.join(temp_dir, filename)
                    with zf.open(member) as src, open(left_path, "wb") as dst:
                        dst.write(src.read())
                    continue

                # Right file → target dir (passed through as an output + used for join)
                if lower_name == RIGHT_FILE_IN_ZIP.lower():
                    right_path = os.path.join(target_dir, filename)
                    with zf.open(member) as src, open(right_path, "wb") as dst:
                        dst.write(src.read())
                    output_paths.append(right_path)
                    continue

                # Other files
                if EXTRACT_OTHER_FILES:
                    other_path = os.path.join(target_dir, filename)
                    with zf.open(member) as src, open(other_path, "wb") as dst:
                        dst.write(src.read())
                    output_paths.append(other_path)

        if left_path is None:
            raise ValueError(
                f"'{LEFT_FILE_IN_ZIP}' not found inside ZIP: {zip_path}"
            )
        if right_path is None:
            raise ValueError(
                f"'{RIGHT_FILE_IN_ZIP}' not found inside ZIP: {zip_path}"
            )

        # ── Read files with optional column selection ─────────────────────────
        left_df  = _read_delimited(left_path,  usecols=LEFT_USECOLS  if LEFT_USECOLS  else None)
        right_df = _read_delimited(right_path, usecols=RIGHT_USECOLS if RIGHT_USECOLS else None)

        # ── Optional dedup on right file ──────────────────────────────────────
        if DEDUP_RIGHT_BY:
            right_df = right_df.drop_duplicates(
                subset=[DEDUP_RIGHT_BY], keep=DEDUP_KEEP
            )

        # ── Resolve effective join keys ───────────────────────────────────────
        # LEFT_KEY / RIGHT_KEY override JOIN_KEY when the column names differ
        # between the two files.
        left_key  = LEFT_KEY  if LEFT_KEY  else JOIN_KEY
        right_key = RIGHT_KEY if RIGHT_KEY else JOIN_KEY

        if left_key not in left_df.columns:
            raise KeyError(
                f"Join key '{left_key}' not found in left file ({LEFT_FILE_IN_ZIP}). "
                f"Available columns: {list(left_df.columns)}"
            )
        if right_key not in right_df.columns:
            raise KeyError(
                f"Join key '{right_key}' not found in right file ({RIGHT_FILE_IN_ZIP}). "
                f"Available columns: {list(right_df.columns)}"
            )

        # ── Join ──────────────────────────────────────────────────────────────
        sfx_left  = LEFT_SUFFIX  if LEFT_SUFFIX  else "_left"
        sfx_right = RIGHT_SUFFIX if RIGHT_SUFFIX else "_right"

        if left_key == right_key:
            merged = left_df.merge(
                right_df,
                on=left_key,
                how=JOIN_TYPE,
                suffixes=(sfx_left, sfx_right),
            )
        else:
            merged = left_df.merge(
                right_df,
                left_on=left_key,
                right_on=right_key,
                how=JOIN_TYPE,
                suffixes=(sfx_left, sfx_right),
            )
            # Drop the duplicate right key column when names differ
            if right_key in merged.columns and right_key != left_key:
                merged = merged.drop(columns=[right_key])

        # ── Drop unwanted output columns ──────────────────────────────────────
        if OUTPUT_DROP_COLUMNS:
            drop = [c for c in OUTPUT_DROP_COLUMNS if c in merged.columns]
            if drop:
                merged = merged.drop(columns=drop)

        # ── Optional column reorder ───────────────────────────────────────────
        # Move INSERT_COLUMN to immediately after INSERT_AFTER_COLUMN
        if INSERT_COLUMN and INSERT_AFTER_COLUMN:
            cols = merged.columns.tolist()
            if INSERT_COLUMN in cols and INSERT_AFTER_COLUMN in cols:
                cols.pop(cols.index(INSERT_COLUMN))
                anchor = cols.index(INSERT_AFTER_COLUMN)
                cols.insert(anchor + 1, INSERT_COLUMN)
                merged = merged[cols]

        # ── Write merged output ───────────────────────────────────────────────
        out_path = os.path.join(target_dir, OUTPUT_FILENAME)
        merged.to_csv(
            out_path,
            sep=",",
            index=False,
            encoding="utf-8",
            quoting=_csv.QUOTE_ALL,
        )
        output_paths.append(out_path)
        return output_paths

    finally:
        _shutil.rmtree(temp_dir, ignore_errors=True)


# ── __main__ block is appended by the Gradio app at generation time ───────────
