"""
Generated by Data Preprocessing Script Library
Template : file_column_split_zip  |  PS-19Z
Purpose  : Extract a file from a ZIP, then split it into multiple output files
           by matching a column against configurable value groups (first-match-wins).
           ALL ZIP contents are extracted to out_dir.
           Base directory is also scanned for additional ZIPs and those are extracted.
Contract : preprocess(input_paths: list) -> list
"""
from __future__ import annotations

import csv as _csv
import json as _json
import os
import shutil as _shutil
import zipfile as _zipfile
from pathlib import Path as _Path

import pandas as pd

# ── Configuration (substituted at generation time) ────────────────────────────
INNER_FILE           = "{{INNER_FILE}}"         # filename inside ZIP to split; "" = first supported
SPLIT_COLUMN         = "{{SPLIT_COLUMN}}"
GROUPS               = {{GROUPS}}               # [{"label": "...", "values": [...], "output_filename": "..."}]
CASE_SENSITIVE       = {{CASE_SENSITIVE}}
INCLUDE_SPLIT_COLUMN = {{INCLUDE_SPLIT_COLUMN}}
NULL_HANDLING        = "{{NULL_HANDLING}}"      # separate_file | merge_into_remaining | discard
NULL_FILENAME        = "{{NULL_FILENAME}}"
REMAINING_HANDLING   = "{{REMAINING_HANDLING}}" # separate_file | discard
REMAINING_FILENAME   = "{{REMAINING_FILENAME}}"
OUTPUT_DIR           = "{{OUTPUT_DIR}}"
OUTPUT_FORMAT        = "{{OUTPUT_FORMAT}}"
# ─────────────────────────────────────────────────────────────────────────────

_ENCODINGS = ["utf-8", "cp1252", "latin-1"]
_SUPPORTED = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}


def _normalise(val):
    if CASE_SENSITIVE:
        return str(val)
    return str(val).lower()


def _load_file(file_path: str) -> pd.DataFrame:
    ext = _Path(file_path).suffix.lower()
    if ext == ".xlsx":
        return pd.read_excel(file_path, engine="openpyxl")
    if ext == ".xls":
        return pd.read_excel(file_path, engine="xlrd")
    if ext == ".json":
        with open(file_path, "r", encoding="utf-8") as fh:
            data = _json.load(fh)
        return pd.json_normalize(data if isinstance(data, list) else [data])
    if ext == ".xml":
        try:
            import lxml.etree as _ET
            root = _ET.parse(file_path).getroot()
        except ImportError:
            import xml.etree.ElementTree as _ET  # type: ignore
            root = _ET.parse(file_path).getroot()
        records = [
            {el.tag: el.text for el in child.iter() if el.text and el.text.strip()}
            for child in root
        ]
        return pd.DataFrame(records)
    if ext in (".html", ".htm"):
        tables = pd.read_html(file_path)
        return tables[0] if tables else pd.DataFrame()
    return _load_delimited(file_path)


def _load_delimited(file_path: str) -> pd.DataFrame:
    for enc in _ENCODINGS:
        try:
            with open(file_path, "r", encoding=enc, errors="replace") as fh:
                sample = fh.read(8192)
            try:
                sep = _csv.Sniffer().sniff(sample).delimiter
            except _csv.Error:
                sep = ","
            return pd.read_csv(file_path, sep=sep, encoding=enc,
                               on_bad_lines="skip", low_memory=False)
        except Exception:
            continue
    raise ValueError(f"Cannot load delimited file: {file_path}")


def _write_output(df: pd.DataFrame, out_path: str, fmt: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _fmt = fmt.lower()
    if _fmt == "csv":
        df.to_csv(out_path, index=False)
    elif _fmt in ("xlsx", "excel"):
        df.to_excel(out_path, index=False, engine="openpyxl")
    elif _fmt == "json":
        df.to_json(out_path, orient="records", indent=2)
    elif _fmt == "parquet":
        df.to_parquet(out_path, index=False)
    elif _fmt == "tsv":
        df.to_csv(out_path, sep="\t", index=False)
    else:
        df.to_csv(out_path, index=False)
    return out_path


def _extract_zip_all(zip_path: str, out_dir: str) -> dict:
    """Extract all files from zip_path into out_dir. Returns {lower_basename: dest_path}."""
    extracted = {}
    with _zipfile.ZipFile(zip_path, "r") as z:
        for name in z.namelist():
            if name.endswith("/"):
                continue
            dest = os.path.join(out_dir, os.path.basename(name))
            with z.open(name) as src, open(dest, "wb") as dst:
                import shutil as _sh
                _sh.copyfileobj(src, dst)
            extracted[os.path.basename(name).lower()] = dest
    return extracted


def _extract_from_zip(input_paths: list, out_dir: str):
    """
    Extract the primary ZIP's contents + scan base dir for additional ZIPs.
    Returns (all_extracted, data_file_path).
    """
    os.makedirs(out_dir, exist_ok=True)
    all_extracted: list[str] = []
    scanned_zips: set = set()

    zip_path = input_paths[0].strip()
    abs_zip  = os.path.abspath(zip_path)
    base_dir = os.path.dirname(abs_zip)

    # ── Scan base directory for additional ZIPs ───────────────────────────────
    for entry in os.scandir(base_dir):
        if entry.name.lower().endswith(".zip") and os.path.abspath(entry.path) != abs_zip:
            if entry.path not in scanned_zips:
                scanned_zips.add(entry.path)
                extras = _extract_zip_all(entry.path, out_dir)
                all_extracted.extend(extras.values())

    # ── Extract primary ZIP ───────────────────────────────────────────────────
    if _Path(zip_path).suffix.lower() == ".zip":
        extracted = _extract_zip_all(zip_path, out_dir)
        all_extracted.extend(extracted.values())

        if INNER_FILE:
            data_path = extracted.get(INNER_FILE.lower())
            if data_path is None:
                raise ValueError(
                    f"'{INNER_FILE}' not found inside ZIP: {zip_path}. "
                    f"Available: {list(extracted.keys())}"
                )
        else:
            data_path = next(
                (v for k, v in extracted.items() if _Path(k).suffix.lower() in _SUPPORTED),
                None,
            )
            if data_path is None:
                raise ValueError(f"No supported data file found inside ZIP: {zip_path}")
    else:
        # Plain file fallback
        dest = os.path.join(out_dir, os.path.basename(zip_path))
        if abs_zip != os.path.abspath(dest):
            _shutil.copy2(zip_path, dest)
        all_extracted.append(dest)
        data_path = dest

    return all_extracted, data_path


def preprocess(input_paths: list) -> list:
    """
    Extract INNER_FILE from the input ZIP, split rows by SPLIT_COLUMN value groups,
    write output files; also extract all other ZIP contents to out_dir.

    Returns
    -------
    list[str]  — all extracted paths  +  all split output file paths.
    """
    if isinstance(input_paths, str):
        input_paths = [input_paths]
    if not input_paths:
        raise ValueError("file_column_split_zip requires at least one input file.")

    out_dir = OUTPUT_DIR if OUTPUT_DIR else os.path.dirname(os.path.abspath(input_paths[0]))
    os.makedirs(out_dir, exist_ok=True)

    all_extracted, data_path = _extract_from_zip(input_paths, out_dir)

    df = _load_file(data_path)

    if SPLIT_COLUMN not in df.columns:
        raise KeyError(
            f"SPLIT_COLUMN '{SPLIT_COLUMN}' not found. "
            f"Available columns: {list(df.columns)}"
        )

    output_paths: list[str] = []

    # ── Separate nulls first ──────────────────────────────────────────────────
    null_mask = df[SPLIT_COLUMN].isna()
    null_df   = df[null_mask].copy()
    data_df   = df[~null_mask].copy()

    # ── Build normalised value lookup per group ───────────────────────────────
    group_lookup: list[tuple[set, str]] = []
    for g in GROUPS:
        raw_values = g.get("values", [])
        if isinstance(raw_values, str):
            raw_values = [v.strip() for v in raw_values.split(",") if v.strip()]
        norm_set = {_normalise(v) for v in raw_values}
        group_lookup.append((norm_set, g["output_filename"]))

    # ── First-match-wins assignment ───────────────────────────────────────────
    assigned_mask = pd.Series(False, index=data_df.index)
    for norm_set, out_filename in group_lookup:
        mask = data_df[SPLIT_COLUMN].apply(lambda v: _normalise(v) in norm_set)
        mask = mask & ~assigned_mask
        group_rows = data_df[mask]
        if not group_rows.empty:
            out_df = group_rows if INCLUDE_SPLIT_COLUMN else group_rows.drop(columns=[SPLIT_COLUMN])
            out_path = os.path.join(out_dir, out_filename)
            _write_output(out_df, out_path, OUTPUT_FORMAT)
            output_paths.append(out_path)
        assigned_mask = assigned_mask | mask

    remaining_df = data_df[~assigned_mask].copy()

    # ── Null handling ─────────────────────────────────────────────────────────
    _null_mode = NULL_HANDLING.strip().lower()
    if not null_df.empty:
        if _null_mode == "separate_file" and NULL_FILENAME:
            out_df = null_df if INCLUDE_SPLIT_COLUMN else null_df.drop(columns=[SPLIT_COLUMN])
            out_path = os.path.join(out_dir, NULL_FILENAME)
            _write_output(out_df, out_path, OUTPUT_FORMAT)
            output_paths.append(out_path)
        elif _null_mode == "merge_into_remaining":
            remaining_df = pd.concat([remaining_df, null_df], ignore_index=True)

    # ── Remaining handling ────────────────────────────────────────────────────
    _rem_mode = REMAINING_HANDLING.strip().lower()
    if not remaining_df.empty:
        if _rem_mode == "separate_file" and REMAINING_FILENAME:
            out_df = remaining_df if INCLUDE_SPLIT_COLUMN else remaining_df.drop(columns=[SPLIT_COLUMN])
            out_path = os.path.join(out_dir, REMAINING_FILENAME)
            _write_output(out_df, out_path, OUTPUT_FORMAT)
            output_paths.append(out_path)

    return all_extracted + output_paths


if __name__ == "__main__":
    import sys
    _input = sys.argv[1] if len(sys.argv) > 1 else ""
    result = preprocess([_input] if _input else [])
    for r in result:
        print(r)
