"""
Generated by Data Preprocessing Script Library
Template : file_delta_load_zip  |  PS-15Z
Purpose  : Extract ALL files from two ZIPs, then compare current vs baseline
           and tag rows NEW / CHANGED / DELETED.
           Same ZIP extracted only once. Base directories scanned for additional ZIPs.
Contract : preprocess(input_paths: list) -> list
"""
from __future__ import annotations

import csv as _csv
import json as _json
import os
import shutil as _shutil
import zipfile as _zipfile
from pathlib import Path as _Path

import pandas as pd

# ── Configuration (substituted at generation time) ────────────────────────────
NEW_FILENAME         = "{{NEW_FILENAME}}"
OLD_FILENAME         = "{{OLD_FILENAME}}"
LEFT_USECOLS         = {{LEFT_USECOLS}}
RIGHT_USECOLS        = {{RIGHT_USECOLS}}
LEFT_INNER_FILE      = "{{LEFT_INNER_FILE}}"
RIGHT_INNER_FILE     = "{{RIGHT_INNER_FILE}}"
KEY_COLUMNS          = {{KEY_COLUMNS}}
DELTA_MODE           = "{{DELTA_MODE}}"
COMPARE_COLUMNS      = {{COMPARE_COLUMNS}}
DELTA_STATUS_COLUMN  = "{{DELTA_STATUS_COLUMN}}"
OUTPUT_DROP_COLUMNS  = {{OUTPUT_DROP_COLUMNS}}
INSERT_COLUMN        = "{{INSERT_COLUMN}}"
INSERT_AFTER_COLUMN  = "{{INSERT_AFTER_COLUMN}}"
OUTPUT_DIR           = "{{OUTPUT_DIR}}"
OUTPUT_FILENAME      = "{{OUTPUT_FILENAME}}"
OUTPUT_FORMAT        = "{{OUTPUT_FORMAT}}"
# ─────────────────────────────────────────────────────────────────────────────

_ENCODINGS = ["utf-8", "cp1252", "latin-1"]
_SUPPORTED = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}


def _load_file(file_path: str) -> pd.DataFrame:
    ext = _Path(file_path).suffix.lower()
    if ext == ".xlsx":  return pd.read_excel(file_path, engine="openpyxl")
    if ext == ".xls":   return pd.read_excel(file_path, engine="xlrd")
    if ext == ".json":
        with open(file_path, "r", encoding="utf-8") as fh:
            data = _json.load(fh)
        return pd.json_normalize(data if isinstance(data, list) else [data])
    if ext == ".xml":
        try:
            import lxml.etree as _ET; root = _ET.parse(file_path).getroot()
        except ImportError:
            import xml.etree.ElementTree as _ET; root = _ET.parse(file_path).getroot()  # type: ignore
        return pd.DataFrame([
            {el.tag: el.text for el in c.iter() if el.text and el.text.strip()} for c in root
        ])
    return _load_delimited(file_path)


def _load_delimited(file_path: str) -> pd.DataFrame:
    for enc in _ENCODINGS:
        try:
            with open(file_path, "r", encoding=enc, errors="replace") as fh:
                sample = fh.read(8192)
            try:    sep = _csv.Sniffer().sniff(sample).delimiter
            except: sep = ","
            return pd.read_csv(file_path, sep=sep, encoding=enc,
                               on_bad_lines="skip", low_memory=False)
        except Exception:
            continue
    raise ValueError(f"Cannot load: {file_path}")


def _write_output(df, out_path, fmt):
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _fmt = fmt.lower()
    if _fmt == "csv":              df.to_csv(out_path, index=False)
    elif _fmt in ("xlsx","excel"): df.to_excel(out_path, index=False, engine="openpyxl")
    elif _fmt == "json":           df.to_json(out_path, orient="records", indent=2)
    elif _fmt == "parquet":        df.to_parquet(out_path, index=False)
    elif _fmt == "tsv":            df.to_csv(out_path, sep="\t", index=False)
    else:                          df.to_csv(out_path, index=False)
    return out_path


def _apply_usecols(df, usecols):
    return df[[c for c in usecols if c in df.columns]] if usecols else df

def _drop_columns(df, cols):
    return df.drop(columns=[c for c in cols if c in df.columns]) if cols else df

def _insert_column_after(df, col, after):
    if not col or col not in df.columns or not after or after not in df.columns: return df
    cols = list(df.columns); cols.remove(col); cols.insert(cols.index(after)+1, col)
    return df[cols]


def _extract_zip_all(zip_path: str, out_dir: str) -> dict:
    extracted = {}
    with _zipfile.ZipFile(zip_path, "r") as z:
        for name in z.namelist():
            if name.endswith("/"): continue
            dest = os.path.join(out_dir, os.path.basename(name))
            with z.open(name) as src, open(dest, "wb") as dst:
                _shutil.copyfileobj(src, dst)
            extracted[os.path.basename(name).lower()] = dest
    return extracted


def _pick_inner(extracted, inner_file, label):
    if inner_file:
        p = extracted.get(inner_file.lower())
        if p is None:
            raise ValueError(f"'{inner_file}' not found in ZIP: {label}. Available: {list(extracted.keys())}")
        return p
    p = next((v for k,v in extracted.items() if _Path(k).suffix.lower() in _SUPPORTED), None)
    if p is None: raise ValueError(f"No supported data file in ZIP: {label}")
    return p


def _extract_from_zips(input_paths, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    all_extracted, scanned_dirs, scanned_zips, cache = [], set(), set(), {}

    def _process_zip(zip_path):
        abs_p = os.path.abspath(zip_path)
        if abs_p not in cache:
            ext_map = _extract_zip_all(abs_p, out_dir)
            cache[abs_p] = ext_map; all_extracted.extend(ext_map.values()); scanned_zips.add(abs_p)
        return cache[abs_p]

    def _scan_dir(base_dir):
        if base_dir in scanned_dirs: return
        scanned_dirs.add(base_dir)
        for entry in os.scandir(base_dir):
            if entry.name.lower().endswith(".zip") and os.path.abspath(entry.path) not in scanned_zips:
                _process_zip(entry.path)

    results = []
    for idx, raw_path in enumerate(input_paths[:2]):
        p = raw_path.strip()
        _scan_dir(os.path.dirname(os.path.abspath(p)))
        if _Path(p).suffix.lower() == ".zip":
            ext_map = _process_zip(p)
            data_path = _pick_inner(ext_map, [LEFT_INNER_FILE, RIGHT_INNER_FILE][idx], p)
        else:
            dest = os.path.join(out_dir, os.path.basename(p))
            if os.path.abspath(p) != os.path.abspath(dest): _shutil.copy2(p, dest)
            all_extracted.append(dest); data_path = dest
        results.append(data_path)

    return all_extracted, results[0], results[1]


def preprocess(input_paths: list) -> list:
    if isinstance(input_paths, str):
        if "," in input_paths:
            input_paths = [p.strip() for p in input_paths.split(",")]
        else:
            input_paths = [input_paths, input_paths]
    if isinstance(input_paths, list) and len(input_paths) == 1:
        input_paths = [input_paths[0], input_paths[0]]
    if len(input_paths) < 2:
        raise ValueError("file_delta_load_zip requires 2 input files.")

    out_dir = OUTPUT_DIR if OUTPUT_DIR else os.path.dirname(os.path.abspath(input_paths[0]))
    all_extracted, new_path, old_path = _extract_from_zips(input_paths, out_dir)

    current  = _apply_usecols(_load_file(new_path), LEFT_USECOLS)
    baseline = _apply_usecols(_load_file(old_path), RIGHT_USECOLS)

    compare_cols = COMPARE_COLUMNS if COMPARE_COLUMNS else [
        c for c in current.columns if c not in KEY_COLUMNS
    ]

    # NEW
    merged_new = current.merge(baseline[KEY_COLUMNS].drop_duplicates(),
                               on=KEY_COLUMNS, how="left", indicator=True)
    new_df = merged_new[merged_new["_merge"] == "left_only"].drop(columns=["_merge"]).copy()
    new_df[DELTA_STATUS_COLUMN] = "NEW"

    # DELETED
    merged_del = baseline.merge(current[KEY_COLUMNS].drop_duplicates(),
                                on=KEY_COLUMNS, how="left", indicator=True)
    deleted_df = merged_del[merged_del["_merge"] == "left_only"].drop(columns=["_merge"]).copy()
    deleted_df[DELTA_STATUS_COLUMN] = "DELETED"

    # CHANGED
    common = current.merge(baseline, on=KEY_COLUMNS, how="inner", suffixes=("_new","_old"))
    shared = [c for c in compare_cols if f"{c}_new" in common.columns and f"{c}_old" in common.columns]
    if shared:
        change_mask = pd.Series(False, index=common.index)
        for col in shared:
            differ = common[f"{col}_new"] != common[f"{col}_old"]
            both_nan = common[f"{col}_new"].isna() & common[f"{col}_old"].isna()
            change_mask |= differ & ~both_nan
        changed_keys = common.loc[change_mask, KEY_COLUMNS].drop_duplicates()
        changed_df = current.merge(changed_keys, on=KEY_COLUMNS, how="inner").copy()
        changed_df[DELTA_STATUS_COLUMN] = "CHANGED"
    else:
        changed_df = pd.DataFrame(columns=list(current.columns) + [DELTA_STATUS_COLUMN])

    frames = []
    if DELTA_MODE in ("new_only",     "full_delta"): frames.append(new_df)
    if DELTA_MODE in ("changed_only", "full_delta"): frames.append(changed_df)
    if DELTA_MODE == "full_delta":                   frames.append(deleted_df)

    if not frames:
        raise ValueError(f"Unknown DELTA_MODE '{DELTA_MODE}'. Use: new_only | changed_only | full_delta")

    result = pd.concat(frames, ignore_index=True)
    result = _drop_columns(result, OUTPUT_DROP_COLUMNS)
    result = _insert_column_after(result, INSERT_COLUMN, INSERT_AFTER_COLUMN)

    out_path = os.path.join(out_dir, OUTPUT_FILENAME)
    _write_output(result, out_path, OUTPUT_FORMAT)
    return all_extracted + [out_path]
