"""
Generated by Data Preprocessing Script Library
Template : file_join_filter_agg_zip  |  PS-18Z
Purpose  : Extract ALL files from two ZIPs, then join → WHERE filter →
           group-by aggregate → optional ranking.
           Same ZIP extracted only once. Base directories scanned for additional ZIPs.
Contract : preprocess(input_paths: list) -> list
"""
from __future__ import annotations

import csv as _csv
import json as _json
import os
import shutil as _shutil
import warnings as _warnings
import zipfile as _zipfile
from pathlib import Path as _Path

import pandas as pd

# ── Configuration (substituted at generation time) ────────────────────────────
LEFT_FILENAME        = "{{LEFT_FILENAME}}"
RIGHT_FILENAME       = "{{RIGHT_FILENAME}}"
LEFT_USECOLS         = {{LEFT_USECOLS}}
RIGHT_USECOLS        = {{RIGHT_USECOLS}}
LEFT_INNER_FILE      = "{{LEFT_INNER_FILE}}"
RIGHT_INNER_FILE     = "{{RIGHT_INNER_FILE}}"
DEDUP_RIGHT_BY       = "{{DEDUP_RIGHT_BY}}"
DEDUP_KEEP           = "{{DEDUP_KEEP}}"
JOIN_KEYS            = {{JOIN_KEYS}}
JOIN_TYPE            = "{{JOIN_TYPE}}"
LEFT_SUFFIX          = "{{LEFT_SUFFIX}}"
RIGHT_SUFFIX         = "{{RIGHT_SUFFIX}}"
WHERE_CONDITION      = "{{WHERE_CONDITION}}"
GROUP_BY_COLUMNS     = {{GROUP_BY_COLUMNS}}
AGGREGATIONS         = {{AGGREGATIONS}}
RANK_BY_COLUMN       = "{{RANK_BY_COLUMN}}"
RANK_ORDER           = "{{RANK_ORDER}}"
RANK_COLUMN_NAME     = "{{RANK_COLUMN_NAME}}"
KEEP_TOP_N           = {{KEEP_TOP_N}}
OUTPUT_DROP_COLUMNS  = {{OUTPUT_DROP_COLUMNS}}
INSERT_COLUMN        = "{{INSERT_COLUMN}}"
INSERT_AFTER_COLUMN  = "{{INSERT_AFTER_COLUMN}}"
OUTPUT_DIR           = "{{OUTPUT_DIR}}"
OUTPUT_FILENAME      = "{{OUTPUT_FILENAME}}"
OUTPUT_FORMAT        = "{{OUTPUT_FORMAT}}"
# ─────────────────────────────────────────────────────────────────────────────

_ENCODINGS = ["utf-8", "cp1252", "latin-1"]
_SUPPORTED = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}


def _load_file(file_path: str) -> pd.DataFrame:
    ext = _Path(file_path).suffix.lower()
    if ext == ".xlsx":  return pd.read_excel(file_path, engine="openpyxl")
    if ext == ".xls":   return pd.read_excel(file_path, engine="xlrd")
    if ext == ".json":
        with open(file_path, "r", encoding="utf-8") as fh:
            data = _json.load(fh)
        return pd.json_normalize(data if isinstance(data, list) else [data])
    if ext == ".xml":
        try:
            import lxml.etree as _ET; root = _ET.parse(file_path).getroot()
        except ImportError:
            import xml.etree.ElementTree as _ET; root = _ET.parse(file_path).getroot()  # type: ignore
        return pd.DataFrame([
            {el.tag: el.text for el in c.iter() if el.text and el.text.strip()} for c in root
        ])
    return _load_delimited(file_path)


def _load_delimited(file_path: str) -> pd.DataFrame:
    for enc in _ENCODINGS:
        try:
            with open(file_path, "r", encoding=enc, errors="replace") as fh:
                sample = fh.read(8192)
            try:    sep = _csv.Sniffer().sniff(sample).delimiter
            except: sep = ","
            return pd.read_csv(file_path, sep=sep, encoding=enc,
                               on_bad_lines="skip", low_memory=False)
        except Exception:
            continue
    raise ValueError(f"Cannot load: {file_path}")


def _write_output(df, out_path, fmt):
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _fmt = fmt.lower()
    if _fmt == "csv":              df.to_csv(out_path, index=False)
    elif _fmt in ("xlsx","excel"): df.to_excel(out_path, index=False, engine="openpyxl")
    elif _fmt == "json":           df.to_json(out_path, orient="records", indent=2)
    elif _fmt == "parquet":        df.to_parquet(out_path, index=False)
    elif _fmt == "tsv":            df.to_csv(out_path, sep="\t", index=False)
    else:                          df.to_csv(out_path, index=False)
    return out_path


def _apply_usecols(df, usecols):
    return df[[c for c in usecols if c in df.columns]] if usecols else df

def _drop_columns(df, cols):
    return df.drop(columns=[c for c in cols if c in df.columns]) if cols else df

def _insert_column_after(df, col, after):
    if not col or col not in df.columns or not after or after not in df.columns: return df
    cols = list(df.columns); cols.remove(col); cols.insert(cols.index(after)+1, col)
    return df[cols]


def _extract_zip_all(zip_path: str, out_dir: str) -> dict:
    extracted = {}
    with _zipfile.ZipFile(zip_path, "r") as z:
        for name in z.namelist():
            if name.endswith("/"): continue
            dest = os.path.join(out_dir, os.path.basename(name))
            with z.open(name) as src, open(dest, "wb") as dst:
                _shutil.copyfileobj(src, dst)
            extracted[os.path.basename(name).lower()] = dest
    return extracted


def _pick_inner(extracted, inner_file, label):
    if inner_file:
        p = extracted.get(inner_file.lower())
        if p is None:
            raise ValueError(f"'{inner_file}' not found in ZIP: {label}. Available: {list(extracted.keys())}")
        return p
    p = next((v for k,v in extracted.items() if _Path(k).suffix.lower() in _SUPPORTED), None)
    if p is None: raise ValueError(f"No supported data file in ZIP: {label}")
    return p


def _extract_from_zips(input_paths, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    all_extracted, scanned_dirs, scanned_zips, cache = [], set(), set(), {}

    def _process_zip(zip_path):
        abs_p = os.path.abspath(zip_path)
        if abs_p not in cache:
            ext_map = _extract_zip_all(abs_p, out_dir)
            cache[abs_p] = ext_map; all_extracted.extend(ext_map.values()); scanned_zips.add(abs_p)
        return cache[abs_p]

    def _scan_dir(base_dir):
        if base_dir in scanned_dirs: return
        scanned_dirs.add(base_dir)
        for entry in os.scandir(base_dir):
            if entry.name.lower().endswith(".zip") and os.path.abspath(entry.path) not in scanned_zips:
                _process_zip(entry.path)

    results = []
    for idx, raw_path in enumerate(input_paths[:2]):
        p = raw_path.strip()
        _scan_dir(os.path.dirname(os.path.abspath(p)))
        if _Path(p).suffix.lower() == ".zip":
            ext_map = _process_zip(p)
            data_path = _pick_inner(ext_map, [LEFT_INNER_FILE, RIGHT_INNER_FILE][idx], p)
        else:
            dest = os.path.join(out_dir, os.path.basename(p))
            if os.path.abspath(p) != os.path.abspath(dest): _shutil.copy2(p, dest)
            all_extracted.append(dest); data_path = dest
        results.append(data_path)

    return all_extracted, results[0], results[1]


def _apply_aggregations(df: pd.DataFrame) -> pd.DataFrame:
    if not GROUP_BY_COLUMNS:
        df = df.copy()
        if not AGGREGATIONS:
            df["_row_count"] = len(df)
            return df
        anchor = df.columns[0]
        for item in AGGREGATIONS:
            col     = str(item.get("column","*")).strip()
            func    = str(item.get("function","count")).strip().lower()
            out_col = str(item.get("output_column","") or f"{col}_{func}").strip()
            src = anchor if col in ("*","") or col not in df.columns else col
            df[out_col] = getattr(df[src], func)() if hasattr(df[src], func) else len(df)
        return df

    anchor_cols = [c for c in df.columns if c not in GROUP_BY_COLUMNS]
    anchor = anchor_cols[0] if anchor_cols else df.columns[0]

    if not AGGREGATIONS:
        agg_df = df.groupby(GROUP_BY_COLUMNS, as_index=False, sort=False).size().rename(columns={"size":"_row_count"})
    else:
        agg_spec = {}
        for item in AGGREGATIONS:
            col     = str(item.get("column","*")).strip()
            func    = str(item.get("function","count")).strip().lower()
            out_col = str(item.get("output_column","") or f"{col}_{func}").strip()
            agg_spec[out_col] = (anchor, "count") if col in ("*","") or col not in df.columns else (col, func)
        agg_df = df.groupby(GROUP_BY_COLUMNS).agg(**agg_spec).reset_index()

    agg_cols = [c for c in agg_df.columns if c not in GROUP_BY_COLUMNS]
    return df.merge(agg_df[GROUP_BY_COLUMNS + agg_cols], on=GROUP_BY_COLUMNS, how="left")


def preprocess(input_paths: list) -> list:
    if len(input_paths) < 2:
        raise ValueError("file_join_filter_agg_zip requires 2 input files.")

    out_dir = OUTPUT_DIR if OUTPUT_DIR else os.path.dirname(os.path.abspath(input_paths[0]))
    all_extracted, left_path, right_path = _extract_from_zips(input_paths, out_dir)

    left  = _apply_usecols(_load_file(left_path),  LEFT_USECOLS)
    right = _apply_usecols(_load_file(right_path), RIGHT_USECOLS)

    if DEDUP_RIGHT_BY and DEDUP_RIGHT_BY in right.columns:
        right = right.drop_duplicates(subset=DEDUP_RIGHT_BY, keep=DEDUP_KEEP or "first")

    join_on = JOIN_KEYS[0] if len(JOIN_KEYS) == 1 else JOIN_KEYS
    missing_l = [k for k in JOIN_KEYS if k not in left.columns]
    missing_r = [k for k in JOIN_KEYS if k not in right.columns]
    if missing_l: raise KeyError(f"JOIN_KEYS {missing_l} not in left file.")
    if missing_r: raise KeyError(f"JOIN_KEYS {missing_r} not in right file.")

    joined = left.merge(right, on=join_on, how=JOIN_TYPE,
                        suffixes=(LEFT_SUFFIX, RIGHT_SUFFIX))

    if WHERE_CONDITION:
        try:
            joined = joined.query(WHERE_CONDITION).reset_index(drop=True)
        except Exception as exc:
            _warnings.warn(f"WHERE_CONDITION failed ({exc}). Continuing without filter.")

    result = _apply_aggregations(joined)

    if RANK_BY_COLUMN and RANK_BY_COLUMN in result.columns:
        ascending = RANK_ORDER.strip().lower() == "asc"
        result = result.copy()
        result[RANK_COLUMN_NAME] = result[RANK_BY_COLUMN].rank(method="min", ascending=ascending).astype(int)
        result = result.sort_values(RANK_COLUMN_NAME).reset_index(drop=True)
        if KEEP_TOP_N and KEEP_TOP_N > 0:
            result = result[result[RANK_COLUMN_NAME] <= KEEP_TOP_N].reset_index(drop=True)

    result = _drop_columns(result, OUTPUT_DROP_COLUMNS)
    result = _insert_column_after(result, INSERT_COLUMN, INSERT_AFTER_COLUMN)

    out_path = os.path.join(out_dir, OUTPUT_FILENAME)
    _write_output(result, out_path, OUTPUT_FORMAT)
    return all_extracted + [out_path]
