"""
Generated by Data Preprocessing Script Library
Template : file_split_columns  |  PS-09
Purpose  : Split a wide file (many columns) into multiple narrower files.
           COMMON_KEY_COLUMNS are retained in every output file.
           Each entry in COLUMN_GROUPS defines a subset of columns + filename.
Contract : preprocess(input_path: str) -> list

COLUMN_GROUPS format (Python list literal injected at generation time):
    [
        {"columns": ["Name", "Address", "City"],      "output_filename": "customer_address.csv"},
        {"columns": ["Credit_Limit", "Currency"],     "output_filename": "customer_finance.csv"},
    ]
"""
from __future__ import annotations

import csv as _csv
import json as _json
import os
import tempfile as _tempfile
import zipfile as _zipfile
from pathlib import Path as _Path

import pandas as pd

# ── Configuration (substituted at generation time) ────────────────────────────
COMMON_KEY_COLUMNS = {{COMMON_KEY_COLUMNS}}
COLUMN_GROUPS      = {{COLUMN_GROUPS}}
OUTPUT_DIR         = "{{OUTPUT_DIR}}"
OUTPUT_FORMAT      = "{{OUTPUT_FORMAT}}"
# ─────────────────────────────────────────────────────────────────────────────


# ── Embedded File Loader ──────────────────────────────────────────────────────
_ENCODINGS = ["utf-8", "cp1252", "latin-1"]


def _load_file(file_path: str) -> pd.DataFrame:
    ext = _Path(file_path).suffix.lower()
    if ext == ".zip":
        return _load_zip(file_path)
    if ext == ".xlsx":
        return pd.read_excel(file_path, engine="openpyxl")
    if ext == ".xls":
        return pd.read_excel(file_path, engine="xlrd")
    if ext == ".json":
        return _load_json(file_path)
    if ext == ".xml":
        return _load_xml(file_path)
    if ext in (".html", ".htm"):
        tables = pd.read_html(file_path)
        return tables[0] if tables else pd.DataFrame()
    return _load_delimited(file_path)


def _load_delimited(file_path: str) -> pd.DataFrame:
    for enc in _ENCODINGS:
        try:
            with open(file_path, "r", encoding=enc, errors="replace") as fh:
                sample = fh.read(8192)
            try:
                sep = _csv.Sniffer().sniff(sample).delimiter
            except _csv.Error:
                sep = ","
            return pd.read_csv(
                file_path, sep=sep, encoding=enc,
                on_bad_lines="skip", low_memory=False,
            )
        except Exception:
            continue
    raise ValueError(f"Cannot load delimited file: {file_path}")


def _load_json(file_path: str) -> pd.DataFrame:
    with open(file_path, "r", encoding="utf-8") as fh:
        data = _json.load(fh)
    return pd.json_normalize(data if isinstance(data, list) else [data])


def _load_xml(file_path: str) -> pd.DataFrame:
    try:
        import lxml.etree as _ET
        root = _ET.parse(file_path).getroot()
    except ImportError:
        import xml.etree.ElementTree as _ET  # type: ignore
        root = _ET.parse(file_path).getroot()
    records = [
        {el.tag: el.text for el in child.iter() if el.text and el.text.strip()}
        for child in root
    ]
    return pd.DataFrame(records)


def _load_zip(file_path: str) -> pd.DataFrame:
    _supported = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}
    with _tempfile.TemporaryDirectory() as tmp_dir:
        with _zipfile.ZipFile(file_path, "r") as z:
            names = [n for n in z.namelist() if _Path(n).suffix.lower() in _supported]
            for name in names:
                z.extract(name, tmp_dir)
        if names:
            return _load_file(os.path.join(tmp_dir, names[0]))
    raise ValueError(f"No loadable file found inside ZIP: {file_path}")


def _write_output(df: pd.DataFrame, out_path: str, fmt: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _fmt = fmt.lower()
    if _fmt == "csv":
        df.to_csv(out_path, index=False)
    elif _fmt in ("xlsx", "excel"):
        df.to_excel(out_path, index=False, engine="openpyxl")
    elif _fmt == "json":
        df.to_json(out_path, orient="records", indent=2)
    elif _fmt == "parquet":
        df.to_parquet(out_path, index=False)
    elif _fmt == "tsv":
        df.to_csv(out_path, sep="\t", index=False)
    else:
        df.to_csv(out_path, index=False)
    return out_path

# ─────────────────────────────────────────────────────────────────────────────


def preprocess(input_path: str) -> list:
    """
    Split *input_path* into multiple narrower files.  Each output file
    contains COMMON_KEY_COLUMNS plus the columns defined in its group entry.
    Columns listed in a group but absent from the source are silently skipped.

    Parameters
    ----------
    input_path : str
        Path to the wide source file.

    Returns
    -------
    list
        List of absolute paths to the written output files.
    """
    if isinstance(input_path, list):
        input_path = input_path[0]
    df = _load_file(input_path)
    _out_dir = OUTPUT_DIR if OUTPUT_DIR else os.path.dirname(os.path.abspath(input_path))
    os.makedirs(_out_dir, exist_ok=True)

    # Validate key columns
    missing_keys = [c for c in COMMON_KEY_COLUMNS if c not in df.columns]
    if missing_keys:
        raise KeyError(
            f"COMMON_KEY_COLUMNS {missing_keys} not found in file: {input_path}"
        )

    output_paths: list = []

    for group in COLUMN_GROUPS:
        group_cols      = group.get("columns", [])
        output_filename = group.get("output_filename", "")

        if not output_filename:
            raise ValueError(
                f"Each COLUMN_GROUPS entry must have 'output_filename'. Got: {group}"
            )

        # Merge key columns + group columns, deduplicate, keep order
        select = COMMON_KEY_COLUMNS + [
            c for c in group_cols if c not in COMMON_KEY_COLUMNS
        ]
        # Only keep columns that actually exist
        available = [c for c in select if c in df.columns]

        subset = df[available].copy()
        output_paths.append(_write_output(subset, os.path.join(_out_dir, output_filename), OUTPUT_FORMAT))

    return output_paths
