"""
Generated by Data Preprocessing Script Library
Template : file_join_multi  |  PS-04
Purpose  : Chain-join three or more files sequentially.
           input_paths[0] is the base; JOIN_STEPS describes each subsequent join.
Contract : preprocess(input_paths: list) -> str

JOIN_STEPS format (Python list literal injected at generation time):
    [
        {"file_index": 1, "join_key": "Product_ID",  "join_type": "left"},
        {"file_index": 2, "join_key": "Category_ID", "join_type": "inner"},
    ]
Optional per-step keys: "left_suffix" (default "_x"), "right_suffix" (default "_y")
"""
from __future__ import annotations

import csv as _csv
import json as _json
import os
import tempfile as _tempfile
import zipfile as _zipfile
from pathlib import Path as _Path

import pandas as pd

# ── Configuration (substituted at generation time) ────────────────────────────
JOIN_STEPS      = {{JOIN_STEPS}}
OUTPUT_DIR      = "{{OUTPUT_DIR}}"
OUTPUT_FILENAME = "{{OUTPUT_FILENAME}}"
OUTPUT_FORMAT   = "{{OUTPUT_FORMAT}}"
# ─────────────────────────────────────────────────────────────────────────────


# ── Embedded File Loader ──────────────────────────────────────────────────────
_ENCODINGS = ["utf-8", "cp1252", "latin-1"]


def _load_file(file_path: str) -> pd.DataFrame:
    ext = _Path(file_path).suffix.lower()
    if ext == ".zip":
        return _load_zip(file_path)
    if ext == ".xlsx":
        return pd.read_excel(file_path, engine="openpyxl")
    if ext == ".xls":
        return pd.read_excel(file_path, engine="xlrd")
    if ext == ".json":
        return _load_json(file_path)
    if ext == ".xml":
        return _load_xml(file_path)
    if ext in (".html", ".htm"):
        tables = pd.read_html(file_path)
        return tables[0] if tables else pd.DataFrame()
    return _load_delimited(file_path)


def _load_delimited(file_path: str) -> pd.DataFrame:
    for enc in _ENCODINGS:
        try:
            with open(file_path, "r", encoding=enc, errors="replace") as fh:
                sample = fh.read(8192)
            try:
                sep = _csv.Sniffer().sniff(sample).delimiter
            except _csv.Error:
                sep = ","
            return pd.read_csv(
                file_path, sep=sep, encoding=enc,
                on_bad_lines="skip", low_memory=False,
            )
        except Exception:
            continue
    raise ValueError(f"Cannot load delimited file: {file_path}")


def _load_json(file_path: str) -> pd.DataFrame:
    with open(file_path, "r", encoding="utf-8") as fh:
        data = _json.load(fh)
    return pd.json_normalize(data if isinstance(data, list) else [data])


def _load_xml(file_path: str) -> pd.DataFrame:
    try:
        import lxml.etree as _ET
        root = _ET.parse(file_path).getroot()
    except ImportError:
        import xml.etree.ElementTree as _ET  # type: ignore
        root = _ET.parse(file_path).getroot()
    records = [
        {el.tag: el.text for el in child.iter() if el.text and el.text.strip()}
        for child in root
    ]
    return pd.DataFrame(records)


def _load_zip(file_path: str) -> pd.DataFrame:
    _supported = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}
    with _zipfile.ZipFile(file_path, "r") as z:
        for name in z.namelist():
            if _Path(name).suffix.lower() in _supported:
                with _tempfile.TemporaryDirectory() as tmp_dir:
                    z.extract(name, tmp_dir)
                    return _load_file(os.path.join(tmp_dir, name))
    raise ValueError(f"No loadable file found inside ZIP: {file_path}")


def _write_output(df: pd.DataFrame, out_path: str, fmt: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _fmt = fmt.lower()
    if _fmt == "csv":
        df.to_csv(out_path, index=False)
    elif _fmt in ("xlsx", "excel"):
        df.to_excel(out_path, index=False, engine="openpyxl")
    elif _fmt == "json":
        df.to_json(out_path, orient="records", indent=2)
    elif _fmt == "parquet":
        df.to_parquet(out_path, index=False)
    elif _fmt == "tsv":
        df.to_csv(out_path, sep="\t", index=False)
    else:
        df.to_csv(out_path, index=False)
    return out_path

# ─────────────────────────────────────────────────────────────────────────────


def preprocess(input_paths: list) -> str:
    """
    Start with input_paths[0] as the base DataFrame, then for each step in
    JOIN_STEPS load the file at input_paths[step['file_index']] and join it
    onto the cumulative result.

    Parameters
    ----------
    input_paths : list[str]
        Ordered list of file paths.  index 0 = base; subsequent indices
        referenced by JOIN_STEPS.

    Returns
    -------
    str
        Absolute path to the fully merged output file.
    """
    if not input_paths:
        raise ValueError("input_paths is empty.")

    result = _load_file(input_paths[0])

    for step_num, step in enumerate(JOIN_STEPS, start=1):
        file_index = step.get("file_index")
        join_key   = step.get("join_key")
        join_type  = step.get("join_type", "left")
        sfx_left   = step.get("left_suffix",  "_x")
        sfx_right  = step.get("right_suffix", "_y")

        if file_index is None or join_key is None:
            raise ValueError(
                f"JOIN_STEPS[{step_num}] must contain 'file_index' and 'join_key'."
            )
        if file_index >= len(input_paths):
            raise IndexError(
                f"JOIN_STEPS[{step_num}] references file_index={file_index} "
                f"but input_paths has only {len(input_paths)} entries."
            )

        other = _load_file(input_paths[file_index])
        result = result.merge(
            other,
            on=join_key,
            how=join_type,
            suffixes=(sfx_left, sfx_right),
        )

    _out_dir = OUTPUT_DIR if OUTPUT_DIR else os.path.dirname(os.path.abspath(input_paths[0]))
    out_path = os.path.join(_out_dir, OUTPUT_FILENAME)
    return _write_output(result, out_path, OUTPUT_FORMAT)
