"""
Generated by Data Preprocessing Script Library
Template : file_union  |  PS-02
Purpose  : Vertically stack (union) selected input files into one consolidated file.
            An optional source-tag column tracks which file each row came from.
Contract : preprocess(input_paths: list, output_columns=None) -> list

Input selection
---------------
This template supports two calling patterns:

1) Pass full/relative file paths (classic):
   preprocess(["./a.csv", "./b.csv"])

2) Pass a folder first, then file *names* to pick from that folder:
   preprocess(["./input_folder", "a.csv", "b.csv"])
   (Useful when your orchestration system provides only filenames.)

Column mismatches
----------------
If column names and/or column counts differ between files, the union still works:
- Output columns are the UNION of all columns across all inputs (in first-seen order)
- Missing values are filled with NaN

Optional schema (output_columns)
--------------------------------
If you want to enforce a specific output schema/order, pass ``output_columns`` to
``preprocess``. When provided, each input file will be conformed to that list:
- Missing columns are created (filled with NaN)
- Extra columns are dropped
- If none of the provided column names match an input file, the file is assumed
  to have "different headers" and columns are mapped by POSITION.
"""
from __future__ import annotations

import csv as _csv
import json as _json
import os
import tempfile as _tempfile
import zipfile as _zipfile
from pathlib import Path as _Path

import pandas as pd

# ── Configuration (substituted at generation time) ────────────────────────────
OUTPUT_DIR        = "{{OUTPUT_DIR}}"
OUTPUT_FILENAME   = "{{OUTPUT_FILENAME}}"
OUTPUT_FORMAT     = "{{OUTPUT_FORMAT}}"
ADD_SOURCE_TAG    = {{ADD_SOURCE_TAG}}
SOURCE_TAG_COLUMN = "{{SOURCE_TAG_COLUMN}}"
# ─────────────────────────────────────────────────────────────────────────────


# ── Embedded File Loader ──────────────────────────────────────────────────────
_ENCODINGS = ["utf-8", "cp1252", "latin-1"]


def _load_file(file_path: str) -> pd.DataFrame:
    ext = _Path(file_path).suffix.lower()
    if ext == ".zip":
        return _load_zip(file_path)
    if ext == ".xlsx":
        return pd.read_excel(file_path, engine="openpyxl")
    if ext == ".xls":
        return pd.read_excel(file_path, engine="xlrd")
    if ext == ".json":
        return _load_json(file_path)
    if ext == ".xml":
        return _load_xml(file_path)
    if ext in (".html", ".htm"):
        tables = pd.read_html(file_path)
        return tables[0] if tables else pd.DataFrame()
    return _load_delimited(file_path)


def _load_delimited(file_path: str) -> pd.DataFrame:
    for enc in _ENCODINGS:
        try:
            with open(file_path, "r", encoding=enc, errors="replace") as fh:
                sample = fh.read(8192)
            try:
                sep = _csv.Sniffer().sniff(sample).delimiter
            except _csv.Error:
                sep = ","
            return pd.read_csv(
                file_path, sep=sep, encoding=enc,
                on_bad_lines="skip", low_memory=False,
            )
        except Exception:
            continue
    raise ValueError(f"Cannot load delimited file: {file_path}")


def _load_json(file_path: str) -> pd.DataFrame:
    with open(file_path, "r", encoding="utf-8") as fh:
        data = _json.load(fh)
    return pd.json_normalize(data if isinstance(data, list) else [data])


def _load_xml(file_path: str) -> pd.DataFrame:
    try:
        import lxml.etree as _ET
        root = _ET.parse(file_path).getroot()
    except ImportError:
        import xml.etree.ElementTree as _ET  # type: ignore
        root = _ET.parse(file_path).getroot()
    records = [
        {el.tag: el.text for el in child.iter() if el.text and el.text.strip()}
        for child in root
    ]
    return pd.DataFrame(records)


def _load_zip(file_path: str) -> pd.DataFrame:
    _supported = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}
    with _tempfile.TemporaryDirectory() as tmp_dir:
        with _zipfile.ZipFile(file_path, "r") as z:
            names = [n for n in z.namelist() if _Path(n).suffix.lower() in _supported]
            for name in names:
                z.extract(name, tmp_dir)
        if names:
            return _load_file(os.path.join(tmp_dir, names[0]))
    raise ValueError(f"No loadable file found inside ZIP: {file_path}")


def _write_output(df: pd.DataFrame, out_path: str, fmt: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _fmt = fmt.lower()
    if _fmt == "csv":
        df.to_csv(out_path, index=False)
    elif _fmt in ("xlsx", "excel"):
        df.to_excel(out_path, index=False, engine="openpyxl")
    elif _fmt == "json":
        df.to_json(out_path, orient="records", indent=2)
    elif _fmt == "parquet":
        df.to_parquet(out_path, index=False)
    elif _fmt == "tsv":
        df.to_csv(out_path, sep="\t", index=False)
    else:
        df.to_csv(out_path, index=False)
    return out_path

# ─────────────────────────────────────────────────────────────────────────────


def _expand_zip_inputs(input_paths: list, tmp_dir: str) -> list:
    """Extract ALL supported files from ZIPs to tmp_dir; pass plain files through.
    Scans each path's base directory for neighbour ZIPs. Returns resolved paths."""
    _supported = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}
    _seen: dict = {}
    _resolved: list = []

    def _extract_one_zip(zip_path: str) -> None:
        key = os.path.abspath(zip_path)
        if key in _seen:
            return
        _seen[key] = True
        with _zipfile.ZipFile(zip_path, "r") as z:
            for name in z.namelist():
                if _Path(name).suffix.lower() in _supported:
                    dest = os.path.join(tmp_dir, os.path.basename(name))
                    with z.open(name) as src, open(dest, "wb") as dst:
                        dst.write(src.read())
                    if dest not in _resolved:
                        _resolved.append(dest)
        for entry in os.scandir(os.path.dirname(os.path.abspath(zip_path))):
            if entry.is_file() and entry.name.lower().endswith(".zip"):
                _extract_one_zip(entry.path)

    for p in input_paths:
        if _Path(p).suffix.lower() == ".zip":
            _extract_one_zip(p)
        else:
            if p not in _resolved:
                _resolved.append(p)
            for entry in os.scandir(os.path.dirname(os.path.abspath(p))):
                if entry.is_file() and entry.name.lower().endswith(".zip"):
                    _extract_one_zip(entry.path)

    return _resolved


def _dedup_column_names(cols: list[str]) -> list[str]:
    """Make column names unique by appending .1, .2, ... to duplicates."""
    seen: dict[str, int] = {}
    out: list[str] = []
    for c in cols:
        base = str(c)
        n = seen.get(base, 0)
        out.append(base if n == 0 else f"{base}.{n}")
        seen[base] = n + 1
    return out


def _ensure_string_unique_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Coerce columns to strings and ensure they are unique (safe for reindex/concat)."""
    cols = [str(c) for c in df.columns.tolist()]
    if len(cols) == len(set(cols)):
        df.columns = cols
        return df
    df = df.copy()
    df.columns = _dedup_column_names(cols)
    return df


def _coerce_output_columns(output_columns) -> list[str] | None:
    """
    Normalize output_columns into a list[str] or None.
    Accepts:
    - None
    - list/tuple of column names
    - comma-separated string: "col1,col2,col3"
    - JSON list string: '["col1","col2"]'
    """
    if output_columns is None:
        return None
    if isinstance(output_columns, (list, tuple)):
        cols = [str(c).strip() for c in output_columns]
        cols = [c for c in cols if c]
        return cols or None
    if isinstance(output_columns, str):
        s = output_columns.strip()
        if not s:
            return None
        if s.startswith("[") and s.endswith("]"):
            try:
                parsed = _json.loads(s)
            except Exception:
                parsed = None
            else:
                if isinstance(parsed, list):
                    cols = [str(c).strip() for c in parsed]
                    cols = [c for c in cols if c]
                    return cols or None
        cols = [c.strip() for c in s.split(",")]
        cols = [c for c in cols if c]
        return cols or None
    raise TypeError(
        "output_columns must be a list[str], comma-separated str, JSON list str, or None"
    )


def _resolve_input_paths(input_paths: list) -> list[str]:
    """
    Resolve the user input into concrete file paths.

    Supported patterns:
    - [file1, file2, ...]
    - [input_dir, file_name_1, file_name_2, ...]
    """
    if not input_paths:
        raise ValueError("input_paths is empty — at least one file is required.")

    first = _Path(str(input_paths[0]))
    if first.exists() and first.is_dir():
        if len(input_paths) < 2:
            raise ValueError(
                "If the first element in input_paths is a directory, provide one or more file names after it.\n"
                "Example: preprocess([input_dir, 'a.csv', 'b.csv'])"
            )
        base_dir = first
        candidates = [base_dir / str(name) for name in input_paths[1:]]
    else:
        candidates = [_Path(str(p)) for p in input_paths]

    resolved: list[str] = []
    missing: list[str] = []
    for p in candidates:
        if p.exists() and p.is_file():
            resolved.append(str(p))
        else:
            missing.append(str(p))

    if missing:
        raise FileNotFoundError(f"Union input files not found: {missing}")

    return resolved


def _union_align_columns(
    frames: list[pd.DataFrame],
    output_columns: list[str] | None = None,
) -> list[pd.DataFrame]:
    """
    Align columns across frames so the union always succeeds even if:
    - column names differ
    - column counts differ

    If output_columns is None:
        Strategy: union-of-columns by first-seen order; missing columns filled with NaN.
    If output_columns is provided:
        Strategy: conform each frame to output_columns:
        - missing columns are created (NaN)
        - extra columns are dropped
        - if no column names match, map by position
    """
    if not frames:
        return frames

    if output_columns:
        canonical = [str(c) for c in output_columns]
        aligned: list[pd.DataFrame] = []
        for df in frames:
            df = _ensure_string_unique_columns(df)

            # Try case-insensitive name matching first
            norm_map: dict[str, str] = {}
            for col in df.columns.tolist():
                key = str(col).strip().lower()
                if key not in norm_map:
                    norm_map[key] = str(col)
            rename_map: dict[str, str] = {}
            for c in canonical:
                if c in df.columns:
                    continue
                key = c.strip().lower()
                if key in norm_map:
                    rename_map[norm_map[key]] = c
            if rename_map:
                df = df.rename(columns=rename_map)

            overlap = set(canonical).intersection(set(df.columns))
            if overlap:
                aligned.append(df.reindex(columns=canonical))
                continue

            # No name overlap: assume "different headers" and map by position
            mapped = pd.DataFrame(index=df.index)
            copy_n = min(df.shape[1], len(canonical))
            for i in range(copy_n):
                mapped[canonical[i]] = df.iloc[:, i].values
            for i in range(copy_n, len(canonical)):
                mapped[canonical[i]] = pd.NA
            aligned.append(mapped)

        return aligned

    # Default: union-of-columns
    ordered_cols: list[str] = []
    normalized_frames: list[pd.DataFrame] = []
    for df in frames:
        df = _ensure_string_unique_columns(df)
        normalized_frames.append(df)
        for c in df.columns.tolist():
            if c not in ordered_cols:
                ordered_cols.append(c)

    return [df.reindex(columns=ordered_cols) for df in normalized_frames]


def preprocess(input_paths: list, output_columns=None) -> list:
    """
    Load all files in *input_paths*, optionally tag each row with its source
    filename, concatenate vertically, and write to OUTPUT_DIR/OUTPUT_FILENAME.

    Parameters
    ----------
    input_paths : list[str]
        Either file paths, or [input_dir, filename1, filename2, ...].
    output_columns : list[str] | str | None
        Optional enforced output schema (and column order). If a string is
        provided, it can be a comma-separated list or a JSON list string.

    Returns
    -------
    list
        Absolute path to the unified output file.
    """
    if isinstance(input_paths, str):
        input_paths = [p.strip() for p in input_paths.split(",") if p.strip()]
    if not input_paths:
        raise ValueError("input_paths is empty — at least one file is required.")

    _orig_first = str(input_paths[0])
    _tmp = _tempfile.TemporaryDirectory()
    if any(_Path(str(p)).suffix.lower() == ".zip" for p in input_paths):
        input_paths = _expand_zip_inputs([str(p) for p in input_paths], _tmp.name)

    resolved_paths = _resolve_input_paths(input_paths)
    canonical_cols = _coerce_output_columns(output_columns)

    frames: list[pd.DataFrame] = []
    for path in resolved_paths:
        df = _load_file(path)
        df = _ensure_string_unique_columns(df)
        frames.append(df)
    _tmp.cleanup()

    if canonical_cols:
        frames = _union_align_columns(frames, output_columns=canonical_cols)

        if ADD_SOURCE_TAG:
            for i, (path, df) in enumerate(zip(resolved_paths, frames)):
                df = df.copy()
                df[SOURCE_TAG_COLUMN] = _Path(path).name
                frames[i] = df
            final_cols = list(canonical_cols)
            if SOURCE_TAG_COLUMN not in final_cols:
                final_cols.append(SOURCE_TAG_COLUMN)
            frames = [df.reindex(columns=final_cols) for df in frames]
    else:
        if ADD_SOURCE_TAG:
            for i, path in enumerate(resolved_paths):
                frames[i][SOURCE_TAG_COLUMN] = _Path(path).name
        frames = _union_align_columns(frames)

    combined = pd.concat(frames, ignore_index=True, sort=False)
    _out_dir = OUTPUT_DIR if OUTPUT_DIR else os.path.dirname(os.path.abspath(_orig_first))
    out_path = os.path.join(_out_dir, OUTPUT_FILENAME)
    return [_write_output(combined, out_path, OUTPUT_FORMAT)]
