"""
Generated by Data Preprocessing Script Library
Template : file_join_two_zip  |  PS-03Z
Purpose  : Extract ALL files from two ZIPs to out_dir, then join the inner
           data files on a key column.
           If both inputs are the same ZIP, it is extracted only once.
           Base directories are scanned for additional ZIPs and extracted too.
Contract : preprocess(input_paths: list) -> list
"""
from __future__ import annotations

import csv as _csv
import json as _json
import os
import shutil as _shutil
import zipfile as _zipfile
from pathlib import Path as _Path

import pandas as pd

# ── Configuration (substituted at generation time) ────────────────────────────
LEFT_FILENAME        = "{{LEFT_FILENAME}}"
RIGHT_FILENAME       = "{{RIGHT_FILENAME}}"
LEFT_USECOLS         = {{LEFT_USECOLS}}
RIGHT_USECOLS        = {{RIGHT_USECOLS}}
LEFT_INNER_FILE      = "{{LEFT_INNER_FILE}}"
RIGHT_INNER_FILE     = "{{RIGHT_INNER_FILE}}"
DEDUP_RIGHT_BY       = "{{DEDUP_RIGHT_BY}}"
DEDUP_KEEP           = "{{DEDUP_KEEP}}"
JOIN_KEY             = "{{JOIN_KEY}}"
LEFT_KEY             = "{{LEFT_KEY}}"
RIGHT_KEY            = "{{RIGHT_KEY}}"
JOIN_TYPE            = "{{JOIN_TYPE}}"
LEFT_SUFFIX          = "{{LEFT_SUFFIX}}"
RIGHT_SUFFIX         = "{{RIGHT_SUFFIX}}"
OUTPUT_DROP_COLUMNS  = {{OUTPUT_DROP_COLUMNS}}
INSERT_COLUMN        = "{{INSERT_COLUMN}}"
INSERT_AFTER_COLUMN  = "{{INSERT_AFTER_COLUMN}}"
OUTPUT_DIR           = "{{OUTPUT_DIR}}"
OUTPUT_FILENAME      = "{{OUTPUT_FILENAME}}"
OUTPUT_FORMAT        = "{{OUTPUT_FORMAT}}"
# ─────────────────────────────────────────────────────────────────────────────

_ENCODINGS = ["utf-8", "cp1252", "latin-1"]
_SUPPORTED = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}


def _load_file(file_path: str) -> pd.DataFrame:
    ext = _Path(file_path).suffix.lower()
    if ext == ".xlsx":
        return pd.read_excel(file_path, engine="openpyxl")
    if ext == ".xls":
        return pd.read_excel(file_path, engine="xlrd")
    if ext == ".json":
        with open(file_path, "r", encoding="utf-8") as fh:
            data = _json.load(fh)
        return pd.json_normalize(data if isinstance(data, list) else [data])
    if ext == ".xml":
        try:
            import lxml.etree as _ET
            root = _ET.parse(file_path).getroot()
        except ImportError:
            import xml.etree.ElementTree as _ET  # type: ignore
            root = _ET.parse(file_path).getroot()
        return pd.DataFrame([
            {el.tag: el.text for el in child.iter() if el.text and el.text.strip()}
            for child in root
        ])
    return _load_delimited(file_path)


def _load_delimited(file_path: str) -> pd.DataFrame:
    for enc in _ENCODINGS:
        try:
            with open(file_path, "r", encoding=enc, errors="replace") as fh:
                sample = fh.read(8192)
            try:
                sep = _csv.Sniffer().sniff(sample).delimiter
            except _csv.Error:
                sep = ","
            return pd.read_csv(file_path, sep=sep, encoding=enc,
                               on_bad_lines="skip", low_memory=False)
        except Exception:
            continue
    raise ValueError(f"Cannot load: {file_path}")


def _write_output(df: pd.DataFrame, out_path: str, fmt: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _fmt = fmt.lower()
    if _fmt == "csv":          df.to_csv(out_path, index=False)
    elif _fmt in ("xlsx","excel"): df.to_excel(out_path, index=False, engine="openpyxl")
    elif _fmt == "json":       df.to_json(out_path, orient="records", indent=2)
    elif _fmt == "parquet":    df.to_parquet(out_path, index=False)
    elif _fmt == "tsv":        df.to_csv(out_path, sep="\t", index=False)
    else:                      df.to_csv(out_path, index=False)
    return out_path


def _apply_usecols(df: pd.DataFrame, usecols: list) -> pd.DataFrame:
    if usecols:
        return df[[c for c in usecols if c in df.columns]]
    return df


def _drop_columns(df: pd.DataFrame, cols: list) -> pd.DataFrame:
    if cols:
        return df.drop(columns=[c for c in cols if c in df.columns])
    return df


def _insert_column_after(df: pd.DataFrame, col: str, after: str) -> pd.DataFrame:
    if not col or col not in df.columns or not after or after not in df.columns:
        return df
    cols = list(df.columns)
    cols.remove(col)
    cols.insert(cols.index(after) + 1, col)
    return df[cols]


def _extract_zip_all(zip_path: str, out_dir: str) -> dict:
    """Extract every file from a ZIP into out_dir. Returns {lower_basename: dest_path}."""
    extracted = {}
    with _zipfile.ZipFile(zip_path, "r") as z:
        for name in z.namelist():
            if name.endswith("/"):
                continue
            dest = os.path.join(out_dir, os.path.basename(name))
            with z.open(name) as src, open(dest, "wb") as dst:
                _shutil.copyfileobj(src, dst)
            extracted[os.path.basename(name).lower()] = dest
    return extracted


def _pick_inner(extracted: dict, inner_file: str, zip_label: str) -> str:
    """Return the path of the inner file to use for data loading."""
    if inner_file:
        path = extracted.get(inner_file.lower())
        if path is None:
            raise ValueError(
                f"'{inner_file}' not found inside ZIP: {zip_label}. "
                f"Available: {list(extracted.keys())}"
            )
        return path
    path = next((v for k, v in extracted.items() if _Path(k).suffix.lower() in _SUPPORTED), None)
    if path is None:
        raise ValueError(f"No supported data file found in ZIP: {zip_label}")
    return path


def _extract_from_zips(input_paths: list, out_dir: str):
    """
    Extract ALL contents from left and right ZIPs to out_dir.
    Same ZIP is extracted only once.
    Base directories are scanned for any additional ZIPs.
    Plain files are copied to out_dir.
    Returns (all_extracted, left_data_path, right_data_path).
    """
    os.makedirs(out_dir, exist_ok=True)
    all_extracted: list[str] = []
    scanned_dirs: set = set()
    scanned_zips: set = set()
    cache: dict = {}  # abs_zip_path → extracted dict

    def _process_zip(zip_path: str) -> dict:
        abs_p = os.path.abspath(zip_path)
        if abs_p not in cache:
            ext_map = _extract_zip_all(abs_p, out_dir)
            cache[abs_p] = ext_map
            all_extracted.extend(ext_map.values())
            scanned_zips.add(abs_p)
        return cache[abs_p]

    def _scan_dir(base_dir: str):
        if base_dir in scanned_dirs:
            return
        scanned_dirs.add(base_dir)
        for entry in os.scandir(base_dir):
            if entry.name.lower().endswith(".zip"):
                abs_e = os.path.abspath(entry.path)
                if abs_e not in scanned_zips:
                    _process_zip(abs_e)

    results = []
    inner_files = [LEFT_INNER_FILE, RIGHT_INNER_FILE]
    for idx, raw_path in enumerate(input_paths[:2]):
        p = raw_path.strip()
        _scan_dir(os.path.dirname(os.path.abspath(p)))
        if _Path(p).suffix.lower() == ".zip":
            ext_map = _process_zip(p)
            data_path = _pick_inner(ext_map, inner_files[idx], p)
        else:
            dest = os.path.join(out_dir, os.path.basename(p))
            if os.path.abspath(p) != os.path.abspath(dest):
                _shutil.copy2(p, dest)
            all_extracted.append(dest)
            data_path = dest
        results.append(data_path)

    return all_extracted, results[0], results[1]


def preprocess(input_paths: list) -> list:
    if len(input_paths) < 2:
        raise ValueError("file_join_two_zip requires 2 input files.")

    out_dir = OUTPUT_DIR if OUTPUT_DIR else os.path.dirname(os.path.abspath(input_paths[0]))
    all_extracted, left_path, right_path = _extract_from_zips(input_paths, out_dir)

    left  = _apply_usecols(_load_file(left_path),  LEFT_USECOLS)
    right = _apply_usecols(_load_file(right_path), RIGHT_USECOLS)

    if DEDUP_RIGHT_BY and DEDUP_RIGHT_BY in right.columns:
        right = right.drop_duplicates(subset=DEDUP_RIGHT_BY, keep=DEDUP_KEEP or "first")

    left_key  = LEFT_KEY  if LEFT_KEY  else JOIN_KEY
    right_key = RIGHT_KEY if RIGHT_KEY else JOIN_KEY

    if left_key not in left.columns:
        raise KeyError(f"Join key '{left_key}' not found in left file. Available: {list(left.columns)}")
    if right_key not in right.columns:
        raise KeyError(f"Join key '{right_key}' not found in right file. Available: {list(right.columns)}")

    if left_key == right_key:
        merged = left.merge(right, on=left_key, how=JOIN_TYPE,
                            suffixes=(LEFT_SUFFIX, RIGHT_SUFFIX))
    else:
        merged = left.merge(right, left_on=left_key, right_on=right_key, how=JOIN_TYPE,
                            suffixes=(LEFT_SUFFIX, RIGHT_SUFFIX))
        if right_key in merged.columns and right_key != left_key:
            merged = merged.drop(columns=[right_key])

    merged = _drop_columns(merged, OUTPUT_DROP_COLUMNS)
    merged = _insert_column_after(merged, INSERT_COLUMN, INSERT_AFTER_COLUMN)

    out_path = os.path.join(out_dir, OUTPUT_FILENAME)
    _write_output(merged, out_path, OUTPUT_FORMAT)
    return all_extracted + [out_path]
