"""
Generated by Data Preprocessing Script Library
Template : file_column_split  |  PS-19
Purpose  : Split one file into multiple output files by matching a column
           against configurable value groups (first-match-wins).
           Nulls and unmatched rows are handled separately.
Contract : preprocess(input_paths: list) -> list
"""
from __future__ import annotations

import csv as _csv
import json as _json
import os
import tempfile as _tempfile
import zipfile as _zipfile
from pathlib import Path as _Path

import pandas as pd

# ── Configuration (substituted at generation time) ────────────────────────────
SPLIT_COLUMN        = "{{SPLIT_COLUMN}}"
GROUPS              = {{GROUPS}}            # [{"label": "...", "values": [...], "output_filename": "..."}]
CASE_SENSITIVE      = {{CASE_SENSITIVE}}
INCLUDE_SPLIT_COLUMN = {{INCLUDE_SPLIT_COLUMN}}
NULL_HANDLING       = "{{NULL_HANDLING}}"   # separate_file | merge_into_remaining | discard
NULL_FILENAME       = "{{NULL_FILENAME}}"
REMAINING_HANDLING  = "{{REMAINING_HANDLING}}"  # separate_file | discard
REMAINING_FILENAME  = "{{REMAINING_FILENAME}}"
OUTPUT_DIR          = "{{OUTPUT_DIR}}"
OUTPUT_FORMAT       = "{{OUTPUT_FORMAT}}"
# ─────────────────────────────────────────────────────────────────────────────

_ENCODINGS = ["utf-8", "cp1252", "latin-1"]


def _normalise(val):
    """Normalise a value for comparison based on CASE_SENSITIVE setting."""
    if CASE_SENSITIVE:
        return str(val)
    return str(val).lower()


def _load_file(file_path: str) -> pd.DataFrame:
    ext = _Path(file_path).suffix.lower()
    if ext == ".xlsx":
        return pd.read_excel(file_path, engine="openpyxl")
    if ext == ".xls":
        return pd.read_excel(file_path, engine="xlrd")
    if ext == ".json":
        with open(file_path, "r", encoding="utf-8") as fh:
            data = _json.load(fh)
        return pd.json_normalize(data if isinstance(data, list) else [data])
    if ext == ".xml":
        try:
            import lxml.etree as _ET
            root = _ET.parse(file_path).getroot()
        except ImportError:
            import xml.etree.ElementTree as _ET  # type: ignore
            root = _ET.parse(file_path).getroot()
        records = [
            {el.tag: el.text for el in child.iter() if el.text and el.text.strip()}
            for child in root
        ]
        return pd.DataFrame(records)
    if ext in (".html", ".htm"):
        tables = pd.read_html(file_path)
        return tables[0] if tables else pd.DataFrame()
    return _load_delimited(file_path)


def _load_delimited(file_path: str) -> pd.DataFrame:
    for enc in _ENCODINGS:
        try:
            with open(file_path, "r", encoding=enc, errors="replace") as fh:
                sample = fh.read(8192)
            try:
                sep = _csv.Sniffer().sniff(sample).delimiter
            except _csv.Error:
                sep = ","
            return pd.read_csv(file_path, sep=sep, encoding=enc,
                               on_bad_lines="skip", low_memory=False)
        except Exception:
            continue
    raise ValueError(f"Cannot load delimited file: {file_path}")


def _write_output(df: pd.DataFrame, out_path: str, fmt: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _fmt = fmt.lower()
    if _fmt == "csv":
        df.to_csv(out_path, index=False)
    elif _fmt in ("xlsx", "excel"):
        df.to_excel(out_path, index=False, engine="openpyxl")
    elif _fmt == "json":
        df.to_json(out_path, orient="records", indent=2)
    elif _fmt == "parquet":
        df.to_parquet(out_path, index=False)
    elif _fmt == "tsv":
        df.to_csv(out_path, sep="\t", index=False)
    else:
        df.to_csv(out_path, index=False)
    return out_path


def preprocess(input_paths: list) -> list:
    """
    Split the input file into multiple output files based on SPLIT_COLUMN values.

    Returns
    -------
    list[str]  — paths of all written output files.
    """
    if isinstance(input_paths, str):
        input_paths = [input_paths]
    if not input_paths:
        raise ValueError("file_column_split requires at least one input file.")

    df = _load_file(input_paths[0])

    if SPLIT_COLUMN not in df.columns:
        raise KeyError(
            f"SPLIT_COLUMN '{SPLIT_COLUMN}' not found. "
            f"Available columns: {list(df.columns)}"
        )

    out_dir = OUTPUT_DIR if OUTPUT_DIR else os.path.dirname(os.path.abspath(input_paths[0]))
    os.makedirs(out_dir, exist_ok=True)
    written: list[str] = []

    # ── Separate nulls first ──────────────────────────────────────────────────
    null_mask = df[SPLIT_COLUMN].isna()
    null_df   = df[null_mask].copy()
    data_df   = df[~null_mask].copy()

    # ── Build normalised value lookup per group ───────────────────────────────
    group_lookup: list[tuple[set, str]] = []
    for g in GROUPS:
        raw_values = g.get("values", [])
        if isinstance(raw_values, str):
            raw_values = [v.strip() for v in raw_values.split(",") if v.strip()]
        norm_set = {_normalise(v) for v in raw_values}
        group_lookup.append((norm_set, g["output_filename"]))

    # ── First-match-wins assignment ───────────────────────────────────────────
    assigned_mask = pd.Series(False, index=data_df.index)
    for norm_set, out_filename in group_lookup:
        mask = data_df[SPLIT_COLUMN].apply(lambda v: _normalise(v) in norm_set)
        mask = mask & ~assigned_mask
        group_rows = data_df[mask]
        if not group_rows.empty:
            out_df = group_rows if INCLUDE_SPLIT_COLUMN else group_rows.drop(columns=[SPLIT_COLUMN])
            out_path = os.path.join(out_dir, out_filename)
            _write_output(out_df, out_path, OUTPUT_FORMAT)
            written.append(out_path)
        assigned_mask = assigned_mask | mask

    remaining_df = data_df[~assigned_mask].copy()

    # ── Null handling ─────────────────────────────────────────────────────────
    _null_mode = NULL_HANDLING.strip().lower()
    if not null_df.empty:
        if _null_mode == "separate_file" and NULL_FILENAME:
            out_df = null_df if INCLUDE_SPLIT_COLUMN else null_df.drop(columns=[SPLIT_COLUMN])
            out_path = os.path.join(out_dir, NULL_FILENAME)
            _write_output(out_df, out_path, OUTPUT_FORMAT)
            written.append(out_path)
        elif _null_mode == "merge_into_remaining":
            remaining_df = pd.concat([remaining_df, null_df], ignore_index=True)
        # discard: do nothing

    # ── Remaining handling ────────────────────────────────────────────────────
    _rem_mode = REMAINING_HANDLING.strip().lower()
    if not remaining_df.empty:
        if _rem_mode == "separate_file" and REMAINING_FILENAME:
            out_df = remaining_df if INCLUDE_SPLIT_COLUMN else remaining_df.drop(columns=[SPLIT_COLUMN])
            out_path = os.path.join(out_dir, REMAINING_FILENAME)
            _write_output(out_df, out_path, OUTPUT_FORMAT)
            written.append(out_path)
        # discard: do nothing

    return written


if __name__ == "__main__":
    import sys
    _input = sys.argv[1] if len(sys.argv) > 1 else ""
    result = preprocess([_input] if _input else [])
    for r in result:
        print(r)
