"""
Generated by Data Preprocessing Script Library
Template : file_filter_by_values  |  PS-17
Purpose  : Filter a single column against one or more value lists.
           Each group of values routes its matching rows to a named output file.
           All rows that do NOT match any group (including nulls) are routed to
           OTHERS_FILENAME — or silently dropped if OTHERS_FILENAME is empty.

Contract : preprocess(input_path: str) -> list  (returns list of output file paths)

VALUE_GROUPS format (Python list literal injected at generation time):
    [
        {"values": ["PAID", "SETTLED"],       "output_filename": "paid_settled.csv"},
        {"values": ["OPEN", "PENDING"],        "output_filename": "open_pending.csv"},
        {"values": ["DISPUTED", "ON_HOLD"],    "output_filename": "disputed.csv"},
    ]

Difference from PS-08 (file_filter_to_files)
--------------------------------------------
PS-08 uses arbitrary pandas query() expressions — powerful but requires
query syntax knowledge and can be fragile on column names with spaces.
PS-17 uses simple .isin() value-list matching on one column — safer,
readable, and handles the "everything else → others file" pattern natively.
"""
from __future__ import annotations

import csv as _csv
import json as _json
import os
import tempfile as _tempfile
import zipfile as _zipfile
from pathlib import Path as _Path

import pandas as pd

# ── Configuration (substituted at generation time) ────────────────────────────
FILTER_COLUMN   = "{{FILTER_COLUMN}}"
VALUE_GROUPS    = {{VALUE_GROUPS}}
CASE_SENSITIVE  = {{CASE_SENSITIVE}}
OTHERS_FILENAME = "{{OTHERS_FILENAME}}"
OUTPUT_DIR      = "{{OUTPUT_DIR}}"
OUTPUT_FORMAT   = "{{OUTPUT_FORMAT}}"
# ─────────────────────────────────────────────────────────────────────────────


# ── Embedded File Loader ──────────────────────────────────────────────────────
_ENCODINGS = ["utf-8", "cp1252", "latin-1"]


def _load_file(file_path: str) -> pd.DataFrame:
    ext = _Path(file_path).suffix.lower()
    if ext == ".zip":
        return _load_zip(file_path)
    if ext == ".xlsx":
        return pd.read_excel(file_path, engine="openpyxl")
    if ext == ".xls":
        return pd.read_excel(file_path, engine="xlrd")
    if ext == ".json":
        return _load_json(file_path)
    if ext == ".xml":
        return _load_xml(file_path)
    if ext in (".html", ".htm"):
        tables = pd.read_html(file_path)
        return tables[0] if tables else pd.DataFrame()
    return _load_delimited(file_path)


def _load_delimited(file_path: str) -> pd.DataFrame:
    for enc in _ENCODINGS:
        try:
            with open(file_path, "r", encoding=enc, errors="replace") as fh:
                sample = fh.read(8192)
            try:
                sep = _csv.Sniffer().sniff(sample).delimiter
            except _csv.Error:
                sep = ","
            return pd.read_csv(
                file_path, sep=sep, encoding=enc,
                on_bad_lines="skip", low_memory=False,
            )
        except Exception:
            continue
    raise ValueError(f"Cannot load delimited file: {file_path}")


def _load_json(file_path: str) -> pd.DataFrame:
    with open(file_path, "r", encoding="utf-8") as fh:
        data = _json.load(fh)
    return pd.json_normalize(data if isinstance(data, list) else [data])


def _load_xml(file_path: str) -> pd.DataFrame:
    try:
        import lxml.etree as _ET
        root = _ET.parse(file_path).getroot()
    except ImportError:
        import xml.etree.ElementTree as _ET  # type: ignore
        root = _ET.parse(file_path).getroot()
    records = [
        {el.tag: el.text for el in child.iter() if el.text and el.text.strip()}
        for child in root
    ]
    return pd.DataFrame(records)


def _load_zip(file_path: str) -> pd.DataFrame:
    _supported = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}
    with _zipfile.ZipFile(file_path, "r") as z:
        for name in z.namelist():
            if _Path(name).suffix.lower() in _supported:
                with _tempfile.TemporaryDirectory() as tmp_dir:
                    z.extract(name, tmp_dir)
                    return _load_file(os.path.join(tmp_dir, name))
    raise ValueError(f"No loadable file found inside ZIP: {file_path}")


def _write_output(df: pd.DataFrame, out_path: str, fmt: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _fmt = fmt.lower()
    if _fmt == "csv":
        df.to_csv(out_path, index=False)
    elif _fmt in ("xlsx", "excel"):
        df.to_excel(out_path, index=False, engine="openpyxl")
    elif _fmt == "json":
        df.to_json(out_path, orient="records", indent=2)
    elif _fmt == "parquet":
        df.to_parquet(out_path, index=False)
    elif _fmt == "tsv":
        df.to_csv(out_path, sep="\t", index=False)
    else:
        df.to_csv(out_path, index=False)
    return out_path

# ─────────────────────────────────────────────────────────────────────────────


def _normalise(series: pd.Series) -> pd.Series:
    """Lower-case a string Series for case-insensitive matching."""
    return series.astype(str).str.strip().str.lower()


def _isin_mask(col_series: pd.Series, values: list) -> pd.Series:
    """
    Build a boolean mask for rows where col_series value is in *values*.
    Respects CASE_SENSITIVE flag.  Null rows are never matched.
    """
    null_mask = col_series.isna()
    if CASE_SENSITIVE:
        match_mask = col_series.isin([str(v) for v in values])
    else:
        lowered_col    = _normalise(col_series)
        lowered_values = [str(v).strip().lower() for v in values]
        match_mask     = lowered_col.isin(lowered_values)
    # nulls should never match any group
    return match_mask & ~null_mask


def preprocess(input_path: str) -> list:
    """
    Route rows from *input_path* to separate output files based on whether
    FILTER_COLUMN's value belongs to each group's value list.

    Routing rules
    -------------
    - A row is tested against VALUE_GROUPS in order.
    - It is routed to the FIRST group whose value list contains its value.
    - A row matched by an earlier group is NOT also matched by later groups.
    - Null values in FILTER_COLUMN always go to OTHERS_FILENAME.
    - Rows matching no group go to OTHERS_FILENAME (or are dropped if empty).

    Parameters
    ----------
    input_path : str
        Path to the source file.

    Returns
    -------
    list[str]
        Absolute paths to every output file written.
    """
    if isinstance(input_path, list):
        input_path = input_path[0]

    df = _load_file(input_path)

    if FILTER_COLUMN not in df.columns:
        raise KeyError(
            f"FILTER_COLUMN '{FILTER_COLUMN}' not found in file: {input_path}"
        )
    if not VALUE_GROUPS:
        raise ValueError("VALUE_GROUPS is empty — define at least one group.")

    _out_dir = OUTPUT_DIR if OUTPUT_DIR else os.path.dirname(os.path.abspath(input_path))
    os.makedirs(_out_dir, exist_ok=True)

    output_paths: list = []
    # Track which rows have already been claimed by a group (first-match wins)
    claimed = pd.Series(False, index=df.index)

    for group in VALUE_GROUPS:
        values          = group.get("values", [])
        output_filename = group.get("output_filename", "")

        if not output_filename:
            raise ValueError(
                f"Every VALUE_GROUPS entry must have 'output_filename'. Got: {group}"
            )
        if not values:
            raise ValueError(
                f"Every VALUE_GROUPS entry must have a non-empty 'values' list. Got: {group}"
            )

        # Match only unclaimed rows (first-match-wins)
        match_mask    = _isin_mask(df[FILTER_COLUMN], values) & ~claimed
        matched_rows  = df[match_mask].copy()

        # Mark these rows as claimed before writing
        claimed |= match_mask

        output_paths.append(
            _write_output(
                matched_rows,
                os.path.join(_out_dir, output_filename),
                OUTPUT_FORMAT,
            )
        )

    # All unclaimed rows (no match + nulls) → OTHERS_FILENAME
    others = df[~claimed].copy()
    if OTHERS_FILENAME and not others.empty:
        output_paths.append(
            _write_output(
                others,
                os.path.join(_out_dir, OTHERS_FILENAME),
                OUTPUT_FORMAT,
            )
        )

    return output_paths
