"""
Generated by Data Preprocessing Script Library
Template : file_join_two  |  PS-03
Purpose  : Join exactly two files on a specified key column.
           input_paths[0] = left (primary) file
           input_paths[1] = right file
Contract : preprocess(input_paths: list) -> str
"""
from __future__ import annotations

import csv as _csv
import json as _json
import os
import tempfile as _tempfile
import zipfile as _zipfile
from pathlib import Path as _Path

import pandas as pd

# ── Configuration (substituted at generation time) ────────────────────────────
LEFT_FILENAME        = "{{LEFT_FILENAME}}"        # file name for the left (primary) file
RIGHT_FILENAME       = "{{RIGHT_FILENAME}}"       # file name for the right file
LEFT_USECOLS         = {{LEFT_USECOLS}}            # columns to load from LEFT file; [] = all
RIGHT_USECOLS        = {{RIGHT_USECOLS}}           # columns to load from RIGHT file; [] = all
LEFT_INNER_FILE      = "{{LEFT_INNER_FILE}}"       # when LEFT is a ZIP, extract this inner file; "" = first file
RIGHT_INNER_FILE     = "{{RIGHT_INNER_FILE}}"      # when RIGHT is a ZIP, extract this inner file; "" = first file
DEDUP_RIGHT_BY       = "{{DEDUP_RIGHT_BY}}"        # dedup RIGHT file on this column before join; "" = skip
DEDUP_KEEP           = "{{DEDUP_KEEP}}"            # "first" | "last"
JOIN_KEY             = "{{JOIN_KEY}}"              # shared key column (used when LEFT_KEY/RIGHT_KEY are empty)
LEFT_KEY             = "{{LEFT_KEY}}"              # override: join key in LEFT file; "" = use JOIN_KEY
RIGHT_KEY            = "{{RIGHT_KEY}}"             # override: join key in RIGHT file; "" = use JOIN_KEY
JOIN_TYPE            = "{{JOIN_TYPE}}"
LEFT_SUFFIX          = "{{LEFT_SUFFIX}}"
RIGHT_SUFFIX         = "{{RIGHT_SUFFIX}}"
OUTPUT_DROP_COLUMNS  = {{OUTPUT_DROP_COLUMNS}}     # columns to drop from merged result; [] = keep all
INSERT_COLUMN        = "{{INSERT_COLUMN}}"         # move this column after INSERT_AFTER_COLUMN; "" = skip
INSERT_AFTER_COLUMN  = "{{INSERT_AFTER_COLUMN}}"
OUTPUT_DIR           = "{{OUTPUT_DIR}}"
OUTPUT_FILENAME      = "{{OUTPUT_FILENAME}}"
OUTPUT_FORMAT        = "{{OUTPUT_FORMAT}}"
# ─────────────────────────────────────────────────────────────────────────────


# ── Embedded File Loader ──────────────────────────────────────────────────────
_ENCODINGS = ["utf-8", "cp1252", "latin-1"]


def _load_file(file_path: str, inner_name: str = "") -> pd.DataFrame:
    ext = _Path(file_path).suffix.lower()
    if ext == ".zip":
        return _load_zip(file_path, inner_name)
    if ext == ".xlsx":
        return pd.read_excel(file_path, engine="openpyxl")
    if ext == ".xls":
        return pd.read_excel(file_path, engine="xlrd")
    if ext == ".json":
        return _load_json(file_path)
    if ext == ".xml":
        return _load_xml(file_path)
    if ext in (".html", ".htm"):
        tables = pd.read_html(file_path)
        return tables[0] if tables else pd.DataFrame()
    return _load_delimited(file_path)


def _load_delimited(file_path: str) -> pd.DataFrame:
    for enc in _ENCODINGS:
        try:
            with open(file_path, "r", encoding=enc, errors="replace") as fh:
                sample = fh.read(8192)
            try:
                sep = _csv.Sniffer().sniff(sample).delimiter
            except _csv.Error:
                sep = ","
            return pd.read_csv(
                file_path, sep=sep, encoding=enc,
                on_bad_lines="skip", low_memory=False,
            )
        except Exception:
            continue
    raise ValueError(f"Cannot load delimited file: {file_path}")


def _load_json(file_path: str) -> pd.DataFrame:
    with open(file_path, "r", encoding="utf-8") as fh:
        data = _json.load(fh)
    return pd.json_normalize(data if isinstance(data, list) else [data])


def _load_xml(file_path: str) -> pd.DataFrame:
    try:
        import lxml.etree as _ET
        root = _ET.parse(file_path).getroot()
    except ImportError:
        import xml.etree.ElementTree as _ET  # type: ignore
        root = _ET.parse(file_path).getroot()
    records = [
        {el.tag: el.text for el in child.iter() if el.text and el.text.strip()}
        for child in root
    ]
    return pd.DataFrame(records)


def _load_zip(file_path: str, inner_name: str = "") -> pd.DataFrame:
    _supported = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}
    with _tempfile.TemporaryDirectory() as tmp_dir:
        with _zipfile.ZipFile(file_path, "r") as z:
            supported = [n for n in z.namelist() if _Path(n).suffix.lower() in _supported]
            for name in supported:
                z.extract(name, tmp_dir)
        if inner_name:
            for name in supported:
                if os.path.basename(name).lower() == inner_name.lower():
                    return _load_file(os.path.join(tmp_dir, name))
            raise ValueError(f"'{inner_name}' not found inside ZIP: {file_path}")
        if supported:
            return _load_file(os.path.join(tmp_dir, supported[0]))
    raise ValueError(f"No loadable file found inside ZIP: {file_path}")


def _write_output(df: pd.DataFrame, out_path: str, fmt: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _fmt = fmt.lower()
    if _fmt == "csv":
        df.to_csv(out_path, index=False)
    elif _fmt in ("xlsx", "excel"):
        df.to_excel(out_path, index=False, engine="openpyxl")
    elif _fmt == "json":
        df.to_json(out_path, orient="records", indent=2)
    elif _fmt == "parquet":
        df.to_parquet(out_path, index=False)
    elif _fmt == "tsv":
        df.to_csv(out_path, sep="\t", index=False)
    else:
        df.to_csv(out_path, index=False)
    return out_path

# ─────────────────────────────────────────────────────────────────────────────


def _find_input_file(input_paths: list, filename: str, fallback_idx: int = 0) -> str:
    """Return the path in *input_paths* whose basename matches *filename*.
    Falls back to input_paths[fallback_idx] if no match is found."""
    for p in input_paths:
        if _Path(p).name == filename:
            return p
    return input_paths[fallback_idx]


def _apply_usecols(df: pd.DataFrame, usecols: list) -> pd.DataFrame:
    if usecols:
        keep = [c for c in usecols if c in df.columns]
        return df[keep]
    return df


def _drop_columns(df: pd.DataFrame, cols: list) -> pd.DataFrame:
    if cols:
        to_drop = [c for c in cols if c in df.columns]
        return df.drop(columns=to_drop)
    return df


def _insert_column_after(df: pd.DataFrame, col: str, after: str) -> pd.DataFrame:
    if not col or col not in df.columns or not after or after not in df.columns:
        return df
    cols = list(df.columns)
    cols.remove(col)
    idx = cols.index(after)
    cols.insert(idx + 1, col)
    return df[cols]


def preprocess(input_paths: list) -> str:
    """
    Join LEFT_FILENAME (left) with RIGHT_FILENAME (right) on JOIN_KEY
    using JOIN_TYPE, then write the merged result to OUTPUT_DIR/OUTPUT_FILENAME.

    Parameters
    ----------
    input_paths : list[str]
        Must contain the two files whose names match LEFT_FILENAME and
        RIGHT_FILENAME. Order does not matter — files are found by name.

    Returns
    -------
    str
        Absolute path to the merged output file.
    """
    if len(input_paths) < 2:
        raise ValueError(
            f"file_join_two requires exactly 2 input files; got {len(input_paths)}."
        )

    left_path  = _find_input_file(input_paths, LEFT_FILENAME,  0)
    right_path = _find_input_file(input_paths, RIGHT_FILENAME, 1)
    left  = _apply_usecols(_load_file(left_path,  LEFT_INNER_FILE),  LEFT_USECOLS)
    right = _apply_usecols(_load_file(right_path, RIGHT_INNER_FILE), RIGHT_USECOLS)

    if DEDUP_RIGHT_BY and DEDUP_RIGHT_BY in right.columns:
        right = right.drop_duplicates(subset=DEDUP_RIGHT_BY, keep=DEDUP_KEEP or "first")

    # Resolve effective join keys:
    # LEFT_KEY / RIGHT_KEY override JOIN_KEY when different column names are used.
    left_key  = LEFT_KEY  if LEFT_KEY  else JOIN_KEY
    right_key = RIGHT_KEY if RIGHT_KEY else JOIN_KEY

    if left_key not in left.columns:
        raise KeyError(
            f"Join key '{left_key}' not found in left file ({LEFT_FILENAME}). "
            f"Available columns: {list(left.columns)}"
        )
    if right_key not in right.columns:
        raise KeyError(
            f"Join key '{right_key}' not found in right file ({RIGHT_FILENAME}). "
            f"Available columns: {list(right.columns)}"
        )

    # Same key name on both sides → use on=; different names → use left_on/right_on
    if left_key == right_key:
        merged = left.merge(
            right,
            on=left_key,
            how=JOIN_TYPE,
            suffixes=(LEFT_SUFFIX, RIGHT_SUFFIX),
        )
    else:
        merged = left.merge(
            right,
            left_on=left_key,
            right_on=right_key,
            how=JOIN_TYPE,
            suffixes=(LEFT_SUFFIX, RIGHT_SUFFIX),
        )
        # Drop the duplicate right key column (pandas keeps it as right_key when using left_on/right_on)
        if right_key in merged.columns and right_key != left_key:
            merged = merged.drop(columns=[right_key])

    merged = _drop_columns(merged, OUTPUT_DROP_COLUMNS)
    merged = _insert_column_after(merged, INSERT_COLUMN, INSERT_AFTER_COLUMN)

    _out_dir = OUTPUT_DIR if OUTPUT_DIR else os.path.dirname(os.path.abspath(input_paths[0]))
    out_path = os.path.join(_out_dir, OUTPUT_FILENAME)
    return _write_output(merged, out_path, OUTPUT_FORMAT)
