"""
Generated by Data Preprocessing Script Library
Template : file_join_filter_agg  |  PS-18
Purpose  : Join two files → apply WHERE filter on joined result →
           group-by aggregate (count / sum / mean / etc.) →
           optionally rank the aggregated rows and keep top-N.

Contract : preprocess(input_paths: list) -> str

Steps
-----
1. Load LEFT_FILENAME and RIGHT_FILENAME from input_paths (matched by name).
2. Join on JOIN_KEYS using JOIN_TYPE.
3. Apply WHERE_CONDITION filter (pandas query syntax) on the joined result.
   Leave WHERE_CONDITION = "" to skip filtering.
4. Group by GROUP_BY_COLUMNS and apply AGGREGATIONS.
   If AGGREGATIONS is empty, a row-count per group is produced.
5. Rank by RANK_BY_COLUMN (asc/desc) and optionally keep top KEEP_TOP_N rows.
   Leave RANK_BY_COLUMN = "" to skip ranking.
6. Write the final result to OUTPUT_DIR / OUTPUT_FILENAME.

AGGREGATIONS format
-------------------
A list of dicts.  Each dict:
  {"column": "col_name",      # source column; use "*" for row count
   "function": "count",       # count | sum | mean | min | max | nunique | first | last | std
   "output_column": "result"} # name in the output dataframe

Example:
  [
    {"column": "*",              "function": "count", "output_column": "_row_count"},
    {"column": "invoice_amount", "function": "sum",   "output_column": "total_amount"},
    {"column": "invoice_number", "function": "nunique","output_column": "unique_invoices"},
  ]
"""
from __future__ import annotations

import csv as _csv
import json as _json
import os
import tempfile as _tempfile
import zipfile as _zipfile
from pathlib import Path as _Path

import pandas as pd

# ── Configuration (substituted at generation time) ────────────────────────────
JOIN_KEYS         = {{JOIN_KEYS}}
JOIN_TYPE         = "{{JOIN_TYPE}}"
LEFT_FILENAME     = "{{LEFT_FILENAME}}"    # file name for the left (primary) file
RIGHT_FILENAME    = "{{RIGHT_FILENAME}}"   # file name for the right file
WHERE_CONDITION   = "{{WHERE_CONDITION}}"  # pandas query() on joined result; "" = no filter
GROUP_BY_COLUMNS  = {{GROUP_BY_COLUMNS}}
AGGREGATIONS      = {{AGGREGATIONS}}
RANK_BY_COLUMN    = "{{RANK_BY_COLUMN}}"   # "" = skip ranking
RANK_ORDER        = "{{RANK_ORDER}}"       # asc | desc
RANK_COLUMN_NAME  = "{{RANK_COLUMN_NAME}}"
KEEP_TOP_N        = {{KEEP_TOP_N}}         # 0 = keep all rows
OUTPUT_DIR        = "{{OUTPUT_DIR}}"
OUTPUT_FILENAME   = "{{OUTPUT_FILENAME}}"
OUTPUT_FORMAT     = "{{OUTPUT_FORMAT}}"
# ─────────────────────────────────────────────────────────────────────────────


# ── Embedded File Loader ──────────────────────────────────────────────────────
_ENCODINGS = ["utf-8", "cp1252", "latin-1"]


def _load_file(file_path: str) -> pd.DataFrame:
    ext = _Path(file_path).suffix.lower()
    if ext == ".zip":
        return _load_zip(file_path)
    if ext == ".xlsx":
        return pd.read_excel(file_path, engine="openpyxl")
    if ext == ".xls":
        return pd.read_excel(file_path, engine="xlrd")
    if ext == ".json":
        return _load_json(file_path)
    if ext == ".xml":
        return _load_xml(file_path)
    if ext in (".html", ".htm"):
        tables = pd.read_html(file_path)
        return tables[0] if tables else pd.DataFrame()
    return _load_delimited(file_path)


def _load_delimited(file_path: str) -> pd.DataFrame:
    for enc in _ENCODINGS:
        try:
            with open(file_path, "r", encoding=enc, errors="replace") as fh:
                sample = fh.read(8192)
            try:
                sep = _csv.Sniffer().sniff(sample).delimiter
            except _csv.Error:
                sep = ","
            return pd.read_csv(
                file_path, sep=sep, encoding=enc,
                on_bad_lines="skip", low_memory=False,
            )
        except Exception:
            continue
    raise ValueError(f"Cannot load delimited file: {file_path}")


def _load_json(file_path: str) -> pd.DataFrame:
    with open(file_path, "r", encoding="utf-8") as fh:
        data = _json.load(fh)
    return pd.json_normalize(data if isinstance(data, list) else [data])


def _load_xml(file_path: str) -> pd.DataFrame:
    try:
        import lxml.etree as _ET
        root = _ET.parse(file_path).getroot()
    except ImportError:
        import xml.etree.ElementTree as _ET  # type: ignore
        root = _ET.parse(file_path).getroot()
    records = [
        {el.tag: el.text for el in child.iter() if el.text and el.text.strip()}
        for child in root
    ]
    return pd.DataFrame(records)


def _load_zip(file_path: str) -> pd.DataFrame:
    _supported = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}
    with _zipfile.ZipFile(file_path, "r") as z:
        for name in z.namelist():
            if _Path(name).suffix.lower() in _supported:
                with _tempfile.TemporaryDirectory() as tmp_dir:
                    z.extract(name, tmp_dir)
                    return _load_file(os.path.join(tmp_dir, name))
    raise ValueError(f"No loadable file found inside ZIP: {file_path}")


def _write_output(df: pd.DataFrame, out_path: str, fmt: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _fmt = fmt.lower()
    if _fmt == "csv":
        df.to_csv(out_path, index=False)
    elif _fmt in ("xlsx", "excel"):
        df.to_excel(out_path, index=False, engine="openpyxl")
    elif _fmt == "json":
        df.to_json(out_path, orient="records", indent=2)
    elif _fmt == "parquet":
        df.to_parquet(out_path, index=False)
    elif _fmt == "tsv":
        df.to_csv(out_path, sep="\t", index=False)
    else:
        df.to_csv(out_path, index=False)
    return out_path

# ─────────────────────────────────────────────────────────────────────────────


def _find_input_file(input_paths: list, filename: str, fallback_idx: int = 0) -> str:
    """Return the path in *input_paths* whose basename matches *filename*.
    Falls back to input_paths[fallback_idx] if no match is found."""
    for p in input_paths:
        if _Path(p).name == filename:
            return p
    return input_paths[fallback_idx]


def _apply_aggregations(df: pd.DataFrame) -> pd.DataFrame:
    """
    Compute group-by aggregations and merge the results back onto the original
    rows so that ALL columns from *df* are preserved alongside the new
    aggregated columns.

    If GROUP_BY_COLUMNS is empty, aggregated columns are added as constants
    (same value on every row).  If AGGREGATIONS is empty, a row-count per
    group (_row_count) is added.
    """
    if not GROUP_BY_COLUMNS:
        # No grouping — add whole-dataframe aggregations as constant columns
        if not AGGREGATIONS:
            df = df.copy()
            df["_row_count"] = len(df)
            return df

        df = df.copy()
        _anchor_col = list(df.columns)
        _anchor = _anchor_col[0]
        for item in AGGREGATIONS:
            col     = str(item.get("column", "*")).strip()
            func    = str(item.get("function", "count")).strip().lower()
            out_col = str(item.get("output_column", "") or f"{col}_{func}").strip()
            src = _anchor if (col in ("*", "") or col not in df.columns) else col
            df[out_col] = getattr(df[src], func)() if hasattr(df[src], func) else len(df)
        return df

    # ── Build aggregation spec ────────────────────────────────────────────────
    _anchor_col = [c for c in df.columns if c not in GROUP_BY_COLUMNS]
    _anchor = _anchor_col[0] if _anchor_col else df.columns[0]

    if not AGGREGATIONS:
        agg_df = (
            df.groupby(GROUP_BY_COLUMNS, as_index=False, sort=False)
            .size()
            .rename(columns={"size": "_row_count"})
        )
    else:
        agg_spec: dict = {}
        for item in AGGREGATIONS:
            col     = str(item.get("column", "*")).strip()
            func    = str(item.get("function", "count")).strip().lower()
            out_col = str(item.get("output_column", "") or f"{col}_{func}").strip()
            if col in ("*", "") or col not in df.columns:
                agg_spec[out_col] = (_anchor, "count")
            else:
                agg_spec[out_col] = (col, func)
        agg_df = df.groupby(GROUP_BY_COLUMNS).agg(**agg_spec).reset_index()

    # ── Merge aggregated columns back onto every original row ─────────────────
    # Use suffixes to avoid column name collision; agg columns win.
    agg_cols = [c for c in agg_df.columns if c not in GROUP_BY_COLUMNS]
    result = df.merge(agg_df[GROUP_BY_COLUMNS + agg_cols], on=GROUP_BY_COLUMNS, how="left")
    return result


def preprocess(input_paths: list) -> str:
    """
    Join LEFT_FILENAME + RIGHT_FILENAME, filter, aggregate, rank, write output.

    Parameters
    ----------
    input_paths : list[str]
        Must contain the two files whose names match LEFT_FILENAME and
        RIGHT_FILENAME. Order does not matter — files are found by name.

    Returns
    -------
    str
        Absolute path to the output file.
    """
    if len(input_paths) < 2:
        raise ValueError(
            f"file_join_filter_agg requires exactly 2 input files; got {len(input_paths)}."
        )

    # ── Step 1: Load files by name ────────────────────────────────────────
    left_path  = _find_input_file(input_paths, LEFT_FILENAME,  0)
    right_path = _find_input_file(input_paths, RIGHT_FILENAME, 1)
    left  = _load_file(left_path)
    right = _load_file(right_path)

    # ── Step 2: Join ──────────────────────────────────────────────────────
    join_on = JOIN_KEYS[0] if len(JOIN_KEYS) == 1 else JOIN_KEYS

    missing_left  = [k for k in JOIN_KEYS if k not in left.columns]
    missing_right = [k for k in JOIN_KEYS if k not in right.columns]
    if missing_left:
        raise KeyError(
            f"JOIN_KEYS {missing_left} not found in left file: {LEFT_FILENAME}"
        )
    if missing_right:
        raise KeyError(
            f"JOIN_KEYS {missing_right} not found in right file: {RIGHT_FILENAME}"
        )

    joined = left.merge(right, on=join_on, how=JOIN_TYPE)

    # ── Step 3: WHERE filter on joined result ─────────────────────────────
    if WHERE_CONDITION:
        try:
            joined = joined.query(WHERE_CONDITION).reset_index(drop=True)
        except Exception as _exc:
            import warnings as _w
            _w.warn(
                f"WHERE_CONDITION '{WHERE_CONDITION}' failed ({_exc}). "
                "Continuing without filter."
            )

    # ── Step 4: Aggregate ─────────────────────────────────────────────────
    result = _apply_aggregations(joined)

    # ── Step 5: Rank ──────────────────────────────────────────────────────
    if RANK_BY_COLUMN and RANK_BY_COLUMN in result.columns:
        ascending = RANK_ORDER.strip().lower() == "asc"
        result = result.copy()
        result[RANK_COLUMN_NAME] = (
            result[RANK_BY_COLUMN]
            .rank(method="min", ascending=ascending)
            .astype(int)
        )
        result = result.sort_values(RANK_COLUMN_NAME).reset_index(drop=True)
        if KEEP_TOP_N and KEEP_TOP_N > 0:
            result = result[result[RANK_COLUMN_NAME] <= KEEP_TOP_N].reset_index(drop=True)

    # ── Step 6: Write output ──────────────────────────────────────────────
    _out_dir = OUTPUT_DIR if OUTPUT_DIR else os.path.dirname(os.path.abspath(input_paths[0]))
    out_path = os.path.join(_out_dir, OUTPUT_FILENAME)
    return _write_output(result, out_path, OUTPUT_FORMAT)
