"""
Generated by Data Preprocessing Script Library
Template : file_deduplicate  |  PS-10
Purpose  : Remove duplicate rows based on KEY_COLUMNS.
           Produces a clean deduplicated file and a duplicates report.
           KEEP strategy: 'first' | 'last' | 'none'  (none = drop ALL duplicates)
Contract : preprocess(input_path: str) -> str
"""
from __future__ import annotations

import csv as _csv
import json as _json
import os
import tempfile as _tempfile
import zipfile as _zipfile
from pathlib import Path as _Path

import pandas as pd

# ── Configuration (substituted at generation time) ────────────────────────────
KEY_COLUMNS                = {{KEY_COLUMNS}}
KEEP                       = "{{KEEP}}"
OUTPUT_DIR                 = "{{OUTPUT_DIR}}"
OUTPUT_FILENAME            = "{{OUTPUT_FILENAME}}"
DUPLICATES_REPORT_FILENAME = "{{DUPLICATES_REPORT_FILENAME}}"
OUTPUT_FORMAT              = "{{OUTPUT_FORMAT}}"
# ─────────────────────────────────────────────────────────────────────────────


# ── Embedded File Loader ──────────────────────────────────────────────────────
_ENCODINGS = ["utf-8", "cp1252", "latin-1"]


def _load_file(file_path: str) -> pd.DataFrame:
    ext = _Path(file_path).suffix.lower()
    if ext == ".zip":
        return _load_zip(file_path)
    if ext == ".xlsx":
        return pd.read_excel(file_path, engine="openpyxl")
    if ext == ".xls":
        return pd.read_excel(file_path, engine="xlrd")
    if ext == ".json":
        return _load_json(file_path)
    if ext == ".xml":
        return _load_xml(file_path)
    if ext in (".html", ".htm"):
        tables = pd.read_html(file_path)
        return tables[0] if tables else pd.DataFrame()
    return _load_delimited(file_path)


def _load_delimited(file_path: str) -> pd.DataFrame:
    for enc in _ENCODINGS:
        try:
            with open(file_path, "r", encoding=enc, errors="replace") as fh:
                sample = fh.read(8192)
            try:
                sep = _csv.Sniffer().sniff(sample).delimiter
            except _csv.Error:
                sep = ","
            return pd.read_csv(
                file_path, sep=sep, encoding=enc,
                on_bad_lines="skip", low_memory=False,
            )
        except Exception:
            continue
    raise ValueError(f"Cannot load delimited file: {file_path}")


def _load_json(file_path: str) -> pd.DataFrame:
    with open(file_path, "r", encoding="utf-8") as fh:
        data = _json.load(fh)
    return pd.json_normalize(data if isinstance(data, list) else [data])


def _load_xml(file_path: str) -> pd.DataFrame:
    try:
        import lxml.etree as _ET
        root = _ET.parse(file_path).getroot()
    except ImportError:
        import xml.etree.ElementTree as _ET  # type: ignore
        root = _ET.parse(file_path).getroot()
    records = [
        {el.tag: el.text for el in child.iter() if el.text and el.text.strip()}
        for child in root
    ]
    return pd.DataFrame(records)


def _load_zip(file_path: str) -> pd.DataFrame:
    _supported = {".csv", ".tsv", ".txt", ".xlsx", ".xls", ".json", ".xml"}
    with _zipfile.ZipFile(file_path, "r") as z:
        for name in z.namelist():
            if _Path(name).suffix.lower() in _supported:
                with _tempfile.TemporaryDirectory() as tmp_dir:
                    z.extract(name, tmp_dir)
                    return _load_file(os.path.join(tmp_dir, name))
    raise ValueError(f"No loadable file found inside ZIP: {file_path}")


def _write_output(df: pd.DataFrame, out_path: str, fmt: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    _fmt = fmt.lower()
    if _fmt == "csv":
        df.to_csv(out_path, index=False)
    elif _fmt in ("xlsx", "excel"):
        df.to_excel(out_path, index=False, engine="openpyxl")
    elif _fmt == "json":
        df.to_json(out_path, orient="records", indent=2)
    elif _fmt == "parquet":
        df.to_parquet(out_path, index=False)
    elif _fmt == "tsv":
        df.to_csv(out_path, sep="\t", index=False)
    else:
        df.to_csv(out_path, index=False)
    return out_path

# ─────────────────────────────────────────────────────────────────────────────


def preprocess(input_path: str) -> list:
    """
    Deduplicate *input_path* based on KEY_COLUMNS.
    All duplicate rows (all occurrences) are written to the duplicates report.
    The clean file keeps the occurrence specified by KEEP ('first', 'last', or
    'none' to drop all duplicated records).

    Parameters
    ----------
    input_path : str
        Path to the source file.

    Returns
    -------
    str
        Absolute path to the deduplicated output file.
    """
    df = _load_file(input_path)
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    missing_keys = [c for c in KEY_COLUMNS if c not in df.columns]
    if missing_keys:
        raise KeyError(
            f"KEY_COLUMNS {missing_keys} not found in file: {input_path}"
        )

    # Capture all rows involved in any duplication (keep=False marks every one)
    dup_mask      = df.duplicated(subset=KEY_COLUMNS, keep=False)
    duplicates_df = df[dup_mask].copy()

    if not duplicates_df.empty:
        dup_path = os.path.join(OUTPUT_DIR, DUPLICATES_REPORT_FILENAME)
        _write_output(duplicates_df, dup_path, OUTPUT_FORMAT)

    # Resolve KEEP strategy
    keep_arg: str | bool
    if KEEP in ("first", "last"):
        keep_arg = KEEP
    else:
        keep_arg = False  # drop ALL duplicates

    clean_df = df.drop_duplicates(subset=KEY_COLUMNS, keep=keep_arg)

    _out_dir = OUTPUT_DIR if OUTPUT_DIR else os.path.dirname(os.path.abspath(input_path))
    out_path = os.path.join(_out_dir, OUTPUT_FILENAME)
    return [_write_output(clean_df, out_path, OUTPUT_FORMAT)]
